### ISSUE TITLE
update ping and pong packets

### ISSUE THREAD

**Issue by subtly** [ethereum/aleth#1558]
Ping: Add destination endpoint. Rename endpoint property to 'destination' (cosmetic update).
Pong: Add destination endpoint to payload.

**Comment by halfalicious** [comment]
It looks like this was done at some point. 
* PingNode destination: https://github.com/ethereum/aleth/blob/b867f9eba00996765fed90c3b627d86305d53dda/libp2p/NodeTable.h#L347-L358
* Pong destination: https://github.com/ethereum/aleth/blob/b867f9eba00996765fed90c3b627d86305d53dda/libp2p/NodeTable.h#L383-L391
