### ISSUE TITLE
Reapply/rework patch for Fedora 22 here

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/aleth#3052]
From @dvitas.

_"Fedora 22 uses gcc 5.xx with old ABI set as a default and all libraries
are compiled with old ABI. Because gcc 5.xx recognizes _GLIBCXX_USE_CXX11_ABI
we must make sure that it is not defined to avoid ABI incompatibilities."_

See https://github.com/ethereum/libweb3core/pull/94/

@5chdn says ...

_"both cpp-ethereum and webthree-umbrella work for me. the patch suggested by @dvitas breaks the patch for archlinux by @LefterisJP ..."_

Please could you make a new PR here, @dvitas?

Please could you add a link to the URL for that archlinux patch, @5chdn?   Did I already merge that?   I think I did.

**Comment by 5chdn** [comment]
It should be this one: https://github.com/ethereum/libweb3core/commit/48921cef0773288b3b96b708caf0035925062e75

**Comment by halfalicious** [comment]
@chfast : Can we close this?
