### ISSUE TITLE
Easy way to start with NoProof and private network

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/aleth#3104]
_From @LefterisJP on February 11, 2016 17:15_

Provide an easy way to start an eth node with NoProof engine and custom network.

_Copied from original issue: ethereum/webthree-umbrella#199_

**Comment by bobsummerwill** [comment]
_From @smartbitcoin on February 11, 2016 20:4_

Agree with that.  but one thing need to be done first .   the fluidity have a benchmark model which can be used for testing TPS.   We need move those functions into the bench project.

**Comment by bobsummerwill** [comment]
I agree.   We need to manage scope, after harvesting any goodness from flu.

See also https://github.com/ethereum/webthree-umbrella/issues/142.

**Comment by bobsummerwill** [comment]
_From @chriseth on February 12, 2016 11:34_

@LefterisJP what is the actual problem? As far as I understad:
 - fix connectivity to private ip addresses (just create an issue for that)
 - fix the way how the genesis-json is provided

Apart from that, I would really like to add `--dev`, as geth has which creates a random test chain with tiny difficulty.

**Comment by bobsummerwill** [comment]
_From @LefterisJP on February 12, 2016 12:29_

@chriseth A lot of things don't work due to the private chain functionality being half-moved to eth.

Last time I tried to create a private chain with custom genesis json with eth it was impossible.

Having a --dev flag would be highly useful for debugging and developing. :+1:

**Comment by halfalicious** [comment]
@gumb0 / @chfast : Presumably we can close this since we now appear to support creating a private network with a custom genesis.json file (not sure if we support NoProof in private network mode but I did a test with Ethash and it appeared to work fine, I mined ~1000 blocks before I manually killed Aleth)

**Comment by gumb0** [comment]
Yes, `NoProof` is now supported in genesis.
