### ISSUE TITLE
Roll cpp-ethereum ARM binaries into PPA so they are available via apt-get

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/aleth#3111]
_From @phonikg on February 16, 2016 23:0_

I understand it may be a lower priority item, but I believe this is possible, especially by automating the x-compile work that doublethink.co has done.

_Copied from original issue: ethereum/webthree-umbrella#228_

**Comment by bobsummerwill** [comment]
From go-ethereum gitter ...

caktux: the ARM builds have been enabled for a while on Launchpad, so it's just a matter of getting cpp's debian configs in order, wherever those are now

**Comment by phonikg** [comment]
Wait  @bobsummerwill  cpp-ethereum ARM builds are available via launchpad?  I'll give it a try...

**Comment by phonikg** [comment]
Ah, I read that differently... So geth1.4.6 IS available via launchpad now(good to know!), cpp-ethereum is in progress!

**Comment by phonikg** [comment]
Testing https://github.com/ethereum/cpp-ethereum/blob/develop/scripts/install_deps.sh now on RasPi2
