### ISSUE TITLE
eth vs geth on CPU mining bench,  potential  bug there!

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/aleth#3119]
_From @smartbitcoin on March 1, 2016 16:31_

Both eth and geth use ethash module as the fundamental piece for calculation SHA3 and dagger hashimoto algorithm.   But in eth 1.1.3 and geth 1.3.3 ( all the latest version ) , the cpu benchmark have a   huge gap there.

eg:
on my intel i5-6400 cpu

eth -C -t 4 --benchmark   =  450K

geth --mine --minerthreads "4"  = 1.4M.

Pretty sure there was a defect in c++ eth implementation somewhere. ( defect I don't mean the calculation value was wrong instead not implemented in an efficient way )

I almost go through  the whole stack, just can't figure out what's the issue inside c++ eth. Maybe someone can help!

_Copied from original issue: ethereum/webthree-umbrella#288_

**Comment by bobsummerwill** [comment]
_From @chriseth on March 1, 2016 17:13_

I would say as long as the value is calculated correctly, we do not care about the efficiency of the CPU miner. What would be a use case for the CPU miner?
Benchmarking ethash verification is a different issue.

**Comment by bobsummerwill** [comment]
_From @smartbitcoin on March 1, 2016 18:6_

that's exactly the point!   b/c miner and verification is the same module.  it's all about sha3 and fetch dag.  so if cpu benchmark on mining is below normal,  the verification will be the same.

like function EthashAux::eval( seed, header, nonce)  will be affected by this low performance.

**Comment by bobsummerwill** [comment]
Hey @gcolvin - Maybe you and @smartbitcoin can collaborate on triaging this?

@smartbitcoin tells me that he's banging his head on the wall a bit trying to understand what the issue might be here.

This is an important issue.

**Comment by bobsummerwill** [comment]
_From @chriseth on March 29, 2016 14:17_

First investigation shows that this might just be a bug in how the hashrate is calculated.

**Comment by chfast** [comment]
1.4M is not doable on CPU.
