### ISSUE TITLE
UPNP rarely works

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/aleth#3126]
_From @winsvega on March 8, 2016 16:7_

```
Could not punch through NAT (or no NAT in place)
void dev::p2p::Host::start() 2045 ms
```

We have to check whether this is a bug in our code or just a limitation of libminiupnpc.

The fact that the listen IP is 0.0.0.0 is a different problem, tracked in https://github.com/ethereum/webthree-umbrella/issues/31

_Copied from original issue: ethereum/webthree-umbrella#325_

**Comment by bobsummerwill** [comment]
_From @winsvega on March 10, 2016 9:11_

0.0.0.0 is set by eth. 
https://github.com/ethereum/libweb3core/blob/develop/libp2p/UPnP.cpp#L118


local IP addresses seems to be disabled 
https://github.com/ethereum/libweb3core/blob/develop/libp2p/Network.cpp#L87

**Comment by halfalicious** [comment]
@chfast Presumably we can close this because UPNP is off by default and the library that we use has security issues, so any UPNP work would involve replacing the existing library with a new one rather than fixing existing issues?
