### ISSUE TITLE
CM - Add debug configurations to our automated builds

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/aleth#3134]
_From @bobsummerwill on March 18, 2016 17:35_

It appears that we are only building Release configurations, which, for example, left us completely blind to our broken Windows debug configurations.

It would be useful if we could not only build debug configurations, but also if we could publish the binaries too, so that we can ask end users to try debug builds to help to pinpoint problems.

_Copied from original issue: ethereum/webthree-umbrella#373_

**Comment by bobsummerwill** [comment]
_From @chfast on March 18, 2016 18:59_

This is more complex. Debug builds are unusable by end users because are too slow. The reason for that is MSVC instruments every iterator and memory access and uses different runtime library. 

I would suggest (as I was doing for some time) to have "release only" dependencies and debug builds of our software. To do that, debug build should use release version of runtime library.

**Comment by bobsummerwill** [comment]
Right.   As per https://github.com/ethereum/webthree-umbrella/issues/183.

Which is our current plan to resolve https://github.com/ethereum/webthree-umbrella/issues/123.

So you were doing "proper" debug configs for these external libraries for a while, but it was unworkable?   If so, that is good to know, and we can just put a bullet in this plan right now (and I will strip that out of cpp-dependencies too, to avoid any further confusion), and add comments to that effect.

Please could you confirm, @debris?   Thanks!

**Comment by bobsummerwill** [comment]
_From @chfast on May 17, 2016 16:46_

Debug dependencies not needed as of https://github.com/ethereum/webthree-helpers/pull/183. You can build Debug with Visual Studio 2015.

**Comment by bobsummerwill** [comment]
Yeah - this issue isn't about Debug dependencies.

It's about the fact that we don't have any automated builds for Debug configs.   We don't even see build breaks in debug-only code - let alone automated tests in Debug.

**Comment by bobsummerwill** [comment]
_From @chfast on May 18, 2016 9:3_

That's why I have not closed the issue. You can setup Debug build on Windows now.

**Comment by bobsummerwill** [comment]
Yeah - let me see if I can add Debug configs into my TravisCI, CircleCI and Appveyor automation.
Given that we're not dependent on our own physical hardware, and that is entirely parallel activity, this shouldn't slow anything down - as long as we don't get "throttled".

**Comment by halfalicious** [comment]
@chfast : Still relevant or can we close?
