### ISSUE TITLE
No automatic linking in OS X El Capitan Build From Source

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/aleth#3138]
_From @VoR0220 on March 19, 2016 23:40_

I recently got a new Macbook fitted with El Capitan, and per my development on the Solidity compiler I needed to build all of this from source. It became apparent that linking was not an automatic thing for soltest and solc. I assume other binaries would be involved as well. I was able to get this working by automatically hard linking back into usr/local/bin but I think this process needs to be altered for future users so they don't have to experience this pain in the neck. 

_Copied from original issue: ethereum/webthree-umbrella#386_

**Comment by bobsummerwill** [comment]
_From @chriseth on March 23, 2016 11:37_

Can you explain a bit more, what do you mean by "no automatic linking" (library/object-file-linking? symlinking?) and which way to build did you use?

**Comment by bobsummerwill** [comment]
_From @VoR0220 on March 23, 2016 16:48_

Building from source on El Capitan for webthree and Solidity in particular. The binaries ought to be symlinked to usr/local/bin automatically via absolute paths but that is not the case with the build. I had to do it by hand.

**Comment by bobsummerwill** [comment]
I'm thinking this should probably be a `make install` step, right, @chriseth?

**Comment by halfalicious** [comment]
@chfast : Still relevant or can we close?
