### ISSUE TITLE
Ubuntu - TravisCI - web3core test failures

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/aleth#3192]
_From @bobsummerwill on July 7, 2016 15:58_

I can't quite work out what the exact failures are because of the verbosity of the log.

But they are in here:  https://travis-ci.org/bobsummerwill/cpp-ethereum/jobs/142546141

```
*** 2 failures detected in test suite "Web3CoreTest"
The command "./test/libweb3core/test/testweb3core" exited with 201.
```

_Copied from original issue: ethereum/webthree-umbrella#618_

**Comment by bobsummerwill** [comment]
OK - got one of these nailed down, happening on Yosemite:

See https://travis-ci.org/bobsummerwill/cpp-ethereum/jobs/143243580

And here is the log ...

    ⧎ ▢  06:19:38.800|p2p  New session for capability p2pTestCapability ; idOffset: 16 ; protocolID: 0
    ⧎ ◎  06:19:38.800|p2p|merwill/cpp-ethereum/test/libweb3core/test/libp2p/peer.cpp:236: fatal error: in "p2pPeer/requirePeer": critical check disconnect1 == disconnect2 has failed [5 != 65535]

**Comment by bobsummerwill** [comment]
And a second, happening on Ubuntu Trusty:

- https://travis-ci.org/bobsummerwill/cpp-ethereum/jobs/143256403
- https://github.com/bobsummerwill/cpp-ethereum/commit/151e76631fc727e5deb62448215659ab6a0c6457

Shows as:

    07:57:25.595|testweb3core  bytesRef copyTo and toString...
    /home/travis/build/bobsummerwill/cpp-ethereum/test/libweb3core/test/libdevcrypto/crypto.cpp(353): fatal error in "ecies_sharedMacData": critical check bytesConstRef(&b).cropped(0, original.size()).toBytes() == asBytes(original) failed

**Comment by bobsummerwill** [comment]
https://travis-ci.org/bobsummerwill/cpp-ethereum/jobs/147608685

Show as this (Ubuntu Trusty):

    /Users/travis/build/bobsummerwill/cpp-ethereum/test/libweb3core/test/libp2p/capability.cpp:142: fatal error: in "p2pCapability/capability": critical check target == testData.first has failed [64 != 0]

**Comment by halfalicious** [comment]
@chfast : Can we close this?
