### ISSUE TITLE
new node not connecting to peers, can't sync

### ISSUE THREAD

**Issue by Tectract** [ethereum/aleth#3339]
just built a node from source, master branch. I turned off GUI options during build because I didn't want to mess with qt5.

now running the eth executable with -v 10 I see this repeated over and over, not getting any blocks... help?

+P+  19:09:11|p2p  performing random discovery
+P+  19:09:11|p2p  Terminating discover after 0  rounds.
⧫ ◎  19:09:14|eth  Since 2016-10-09 01:08:58.343Z (15): 15ticks
⧎ ▢  19:09:14|p2p  Attempting connection to node ##979b7fa2… @ tcp://5.1.83.226:30303 from ##a8615f04…
⧎ ▢  19:09:14|p2p  Attempting connection to node ##a979fb57… @ tcp://52.16.188.185:30303 from ##a8615f04…
⧎ ▢  19:09:15|p2p  Attempting connection to node ##5374c1bf… @ tcp://92.51.165.126:30300 from ##a8615f04…
⧎ ▢  19:09:15|p2p  Connection refused to node ##979b7fa2… @ tcp://5.1.83.226:30303 ( Connection refused )
⧎ ▢  19:09:15|p2p  Connecting to ##a979fb57… @ tcp://52.16.188.185:30303
⧎ ▢  19:09:15|p2p  p2p.connect.egress sending auth to tcp://52.16.188.185:30303
⧎ ▢  19:09:15|p2p  p2p.connect.egress recving ack from tcp://52.16.188.185:30303
⧎ ▢  19:09:15|p2p  p2p.connect.egress sending capabilities handshake
⧎ ℹ  19:09:15|p2p  p2p.connect.egress recvd hello header
⧎ ◎  19:09:15|p2p  p2p.connect.egress hello frame: invalid packet type
⧎ ▢  19:09:15|p2p  Handshake Failed (I/O Error: Success )
⧎ ▢  19:09:15|p2p  Disconnecting tcp://52.16.188.185:30303  (Handshake Failed)
+P+  19:09:18|p2p  performing random discovery
+P+  19:09:18|p2p  Terminating discover after 0  rounds.
⧎ ▢  19:09:20|p2p  Attempting connection to node ##979b7fa2… @ tcp://5.1.83.226:30303 from ##a8615f04…
⧎ ▢  19:09:20|p2p  Attempting connection to node ##a979fb57… @ tcp://52.16.188.185:30303 from ##a8615f04…
⧎ ▢  19:09:20|p2p  Connection refused to node ##979b7fa2… @ tcp://5.1.83.226:30303 ( Connection refused )
⧎ ▢  19:09:20|p2p  Connecting to ##a979fb57… @ tcp://52.16.188.185:30303
⧎ ▢  19:09:20|p2p  p2p.connect.egress sending auth to tcp://52.16.188.185:30303
⧎ ▢  19:09:20|p2p  p2p.connect.egress recving ack from tcp://52.16.188.185:30303
⧎ ▢  19:09:20|p2p  p2p.connect.egress sending capabilities handshake
⧎ ℹ  19:09:20|p2p  p2p.connect.egress recvd hello header
⧎ ◎  19:09:20|p2p  p2p.connect.egress hello frame: invalid packet type
⧎ ▢  19:09:20|p2p  Handshake Failed (I/O Error: Success )
⧎ ▢  19:09:20|p2p  Disconnecting tcp://52.16.188.185:30303  (Handshake Failed)
⧎ ▢  19:09:25|p2p  Attempting connection to node ##979b7fa2… @ tcp://5.1.83.226:30303 from ##a8615f04…
⧎ ▢  19:09:25|p2p  Attempting connection to node ##a979fb57… @ tcp://52.16.188.185:30303 from ##a8615f04…
⧎ ▢  19:09:25|p2p  Connection refused to node ##979b7fa2… @ tcp://5.1.83.226:30303 ( Connection refused )
⧎ ▢  19:09:25|p2p  Connecting to ##a979fb57… @ tcp://52.16.188.185:30303
⧎ ▢  19:09:25|p2p  p2p.connect.egress sending auth to tcp://52.16.188.185:30303
⧎ ▢  19:09:25|p2p  p2p.connect.egress recving ack from tcp://52.16.188.185:30303
⧎ ▢  19:09:25|p2p  p2p.connect.egress sending capabilities handshake
⧎ ℹ  19:09:25|p2p  p2p.connect.egress recvd hello header
⧎ ◎  19:09:25|p2p  p2p.connect.egress hello frame: invalid packet type
⧎ ▢  19:09:25|p2p  Handshake Failed (I/O Error: Success )
⧎ ▢  19:09:25|p2p  Disconnecting tcp://52.16.188.185:30303  (Handshake Failed)
+P+  19:09:25|p2p  performing random discovery
+P+  19:09:25|p2p  Terminating discover after 0  rounds.
⧫ ◎  19:09:29|eth  Since 2016-10-09 01:09:14.317Z (15): 15ticks
⧎ ▢  19:09:30|p2p  Attempting connection to node ##979b7fa2… @ tcp://5.1.83.226:30303 from ##a8615f04…
⧎ ▢  19:09:30|p2p  Attempting connection to node ##a979fb57… @ tcp://52.16.188.185:30303 from ##a8615f04…
⧎ ▢  19:09:30|p2p  Connection refused to node ##979b7fa2… @ tcp://5.1.83.226:30303 ( Connection refused )
⧎ ▢  19:09:30|p2p  Connecting to ##a979fb57… @ tcp://52.16.188.185:30303
⧎ ▢  19:09:30|p2p  p2p.connect.egress sending auth to tcp://52.16.188.185:30303
⧎ ▢  19:09:30|p2p  p2p.connect.egress recving ack from tcp://52.16.188.185:30303
⧎ ▢  19:09:31|p2p  p2p.connect.egress sending capabilities handshake
⧎ ℹ  19:09:31|p2p  p2p.connect.egress recvd hello header
⧎ ◎  19:09:31|p2p  p2p.connect.egress hello frame: success. starting session.
⧎ ◌  19:09:31|p2p  Hello: Geth/v1.4.15-stable-cb7d7d3d/linux/go1.7.1 V[ 4 ] ##a979fb57… (eth,63) 0
⧎ ℹ  19:09:31|p2p  p2p.host.peer.register ##a979fb57…
⧎ ◌  19:09:31|p2p|a979fb57…|Geth/v1.4.15-stable-cb7d7d3d/linux/go1.7.1  Disconnect (reason: Peer had no use for this node. )
⧎ ▢  19:09:31|p2p|a979fb57…|Geth/v1.4.15-stable-cb7d7d3d/linux/go1.7.1  Closing tcp://52.16.188.185:30303 ( Disconnect was requested. )
⧎ ◌  19:09:31|p2p|a979fb57…|Geth/v1.4.15-stable-cb7d7d3d/linux/go1.7.1  Closing peer session :-(

**Comment by halfalicious** [comment]
Can start syncing fine on both ropsten and mainnet using privately built master sync'd to the following commit:
```

commit df1048c695327854a897ba5da77a442f494265bd (HEAD -> master, origin/master, origin/HEAD)
Merge: b6a176e1e 2cb9d4b67
Author: Pawe<C5><82> Bylica <chfast@gmail.com>
Date:   Wed Feb 13 16:03:38 2019 +0100

    Merge pull request #5487 from ethereum/eip8-unittest

    EIP-8 unittests
```
