### ISSUE TITLE
Update of FreeBSD port

### ISSUE THREAD

**Issue by louisabraham** [ethereum/aleth#3417]
Hello,

The compilation of solidity alone fails on FreeBSD (https://github.com/ethereum/solidity/issues/1388), and when I follow the instructions at http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/freebsd.html, I get a very old version (3.5) that has the corrected issue “solc: exit status 1".
Is is possible to update the FreeBSD port?

**Comment by chfast** [comment]
Is this about solidity or cpp-ethereum? I can help with building cpp-ethereum on FreeBSD.

**Comment by halfalicious** [comment]
@chfast: I think we can close this?
