### ISSUE TITLE
Improve file related doxygen

### ISSUE THREAD

**Issue by winsvega** [ethereum/aleth#3562]
The "file level" Doxygen needs some improvements and fixes. It usually looks like this:
```
/** @file ExtVMFace.h
 * @author Gav Wood <i@gavwood.com>
 * @date 2014
 */
```

1. Having a file name repeated is bad idea, because it is only needed if the documenting comment describes a file other than the one the comment is in. And if you rename the file, Doxygen becomes invalid.
2. Having author here is bad idea (as mentioned in comments).
3. Having date is also bad idea. If we have this stupid-long preface about GPL everywhere, having license/copyright information in Doxygen is pointless (my opinion).

So my suggestion is to have it look like this example:
```
/// This file defines interfaces for Ethereum Virtual Machines.
/// @file
```

The `@file` tag is in the end because it is for machines, not humans. I also prefer `///` comments because they don't add additional lines and alignment complexity.

**Comment by chriseth** [comment]
I think it's best to remove all authors, it does not make a lot of sense and the list is not kept up to date anyway.

**Comment by LefterisJP** [comment]
Yes please remove all authors. There is no need to have a list of authors per file, when the version control system does that for us anyway.

**Comment by chfast** [comment]
I allowed myself to edit the description to extend the issue scope.

If we agree on something, I think we should not make whole repo change at once to change everything, but developers should be free to make changes to meet agreed layout.

**Comment by gcolvin** [comment]
So having nothing but the _@file_ tag means we run the Doxygen machinery just to generate the same information as _ls_?

**Comment by chfast** [comment]
Sorry, I don't understand your question.

**Comment by chriseth** [comment]
Adding the file name has some benefit if the file content is used out of context, but I would be fine with removing it. I'm also fine with changing to triple slashes.

**Comment by Sedherthe** [comment]
I want to contribute to this issue! Can I get the complete details of what all changes are expected?

**Comment by gumb0** [comment]
@Sedherthe Thank you for your interest, unfortunately I don't think there're any particular changes to be done here. This issue was more like a point of discussion about file headers.

Currently we usually replace these headers file-by-file when we make changes in them.

I think this issue can be closed.

**Comment by gumb0** [comment]
(Also I'm not sure why we care about doxygen at all, we never run it on aleth)

**Comment by halfalicious** [comment]
@gumb0 Maybe we should start? See #3564

**Comment by gumb0** [comment]
@chfast I think we can close this?
