### ISSUE TITLE
can't make VS2015 sn

### ISSUE THREAD

**Issue by 200787128** [ethereum/aleth#4119]
C:\Users\Administrator\Desktop\cpp-ethereum\cpp-ethereum\build>cmake ..
-- Could NOT find mhd (missing:  MHD_LIBRARY MHD_INCLUDE_DIR)

------------------------------------------------------------------------
-- Configuring cpp-ethereum
------------------------------------------------------------------------
-- CMake 3.8.2 (C:/Users/Administrator/Downloads/cmake-3.8.2-win32-x86/cmake-3.8
.2-win32-x86/bin/cmake.exe)
-- CMAKE_BUILD_TYPE Build type                               RelWithDebInfo
-- TARGET_PLATFORM  Target platform                          Windows
-- BUILD_SHARED_LIBS                                         OFF
--------------------------------------------------------------- features
--                  Hardware identification support
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  ON
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- PARANOID         -                                        OFF
-- MINIUPNPC        -                                        OFF
------------------------------------------------------------- components
-- TESTS            Build tests                              ON
-- TOOLS            Build tools                              ON
-- EVMJIT           Build LLVM-based JIT EVM                 OFF
------------------------------------------------------------------------

-- Could NOT find leveldb (missing:  LEVELDB_LIBRARY LEVELDB_INCLUDE_DIR)
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND
-- Could NOT find miniupnpc (missing:  MINIUPNPC_LIBRARY MINIUPNPC_INCLUDE_DIR)

-- miniupnpc headers: MINIUPNPC_INCLUDE_DIR-NOTFOUND
-- miniupnpc lib   : iphlpapi;optimized;MINIUPNPC_LIBRARY-NOTFOUND;debug;MINIUPN
PC_LIBRARY_DEBUG-NOTFOUND
-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1;
--eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTes
ts/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --
eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth
_testfile=BlockTests/bcValidBlockTest --eth_threads=10
CMake Error: The following variables are used in this project, but they are set
to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake file
s:
C:/Users/Administrator/Desktop/cpp-ethereum/cpp-ethereum/libdevcore/LEVELDB_INCL
UDE_DIR
   used as include directory in directory C:/Users/Administrator/Desktop/cpp-eth
ereum/cpp-ethereum/libdevcore
LEVELDB_LIBRARY (ADVANCED)
    linked by target "devcore" in directory C:/Users/Administrator/Desktop/cpp-e
thereum/cpp-ethereum/libdevcore
LEVELDB_LIBRARY_DEBUG
    linked by target "devcore" in directory C:/Users/Administrator/Desktop/cpp-e
thereum/cpp-ethereum/libdevcore

-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/Desktop/cpp-ethereum/cpp-ethereum/CMakeFiles/CM
akeOutput.log".

who help me?

**Comment by azimgoogle** [comment]
Facing the same problem. Anyone, to help?

**Comment by rlunaro** [comment]
Same problem, ubuntu 16 on a virtual machine.

**Comment by rlunaro** [comment]
I think I solved it: sudo apt-get install libdeveldb-dev
