### ISSUE TITLE
CMake Configure fail VS2015

### ISSUE THREAD

**Issue by 200787128** [ethereum/aleth#4120]
Could NOT find mhd (missing: MHD_LIBRARY MHD_INCLUDE_DIR)

-- Configuring cpp-ethereum

-- CMake 3.8.2 (C:/Users/Administrator/Downloads/cmake-3.8.2-win32-x86/cmake-3.8.2-win32-x86/bin/cmake.exe)
-- CMAKE_BUILD_TYPE Build type RelWithDebInfo
-- TARGET_PLATFORM Target platform Windows
-- BUILD_SHARED_LIBS OFF
--------------------------------------------------------------- features
-- Hardware identification support
-- VMTRACE VM execution tracing OFF
-- PROFILING Profiling support OFF
-- FATDB Full database exploring ON
-- ROCKSDB Prefer rocksdb to leveldb OFF
-- PARANOID - OFF
-- MINIUPNPC - OFF
------------------------------------------------------------- components
-- TESTS Build tests ON
-- TOOLS Build tools ON
-- EVMJIT Build LLVM-based JIT EVM OFF

Could NOT find leveldb (missing: LEVELDB_LIBRARY LEVELDB_INCLUDE_DIR)
Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
Cpuid lib : CPUID_LIBRARY-NOTFOUND
Could NOT find miniupnpc (missing: MINIUPNPC_LIBRARY MINIUPNPC_INCLUDE_DIR)
miniupnpc headers: MINIUPNPC_INCLUDE_DIR-NOTFOUND
miniupnpc lib : iphlpapi;optimized;MINIUPNPC_LIBRARY-NOTFOUND;debug;MINIUPNPC_LIBRARY_DEBUG-NOTFOUND
test: ClientBase | --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=10
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/Users/Administrator/Desktop/cpp-ethereum/cpp-ethereum/libdevcore/LEVELDB_INCLUDE_DIR
used as include directory in directory C:/Users/Administrator/Desktop/cpp-ethereum/cpp-ethereum/libdevcore
LEVELDB_LIBRARY (ADVANCED)
linked by target "devcore" in directory C:/Users/Administrator/Desktop/cpp-ethereum/cpp-ethereum/libdevcore
LEVELDB_LIBRARY_DEBUG
linked by target "devcore" in directory C:/Users/Administrator/Desktop/cpp-ethereum/cpp-ethereum/libdevcore

Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/Desktop/cpp-ethereum/cpp-ethereum/CMakeFiles/CMakeOutput.log".

How can we generate it?
What is the lack of environment?

**Comment by tcsiwula** [comment]
I got this one too, but appears to work?
`-- Found leveldb: /usr/lib/x86_64-linux-gnu/libleveldb.so  
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND
-- Could NOT find miniupnpc (missing:  MINIUPNPC_LIBRARY MINIUPNPC_INCLUDE_DIR) 
-- miniupnpc headers: MINIUPNPC_INCLUDE_DIR-NOTFOUND
-- miniupnpc lib   : MINIUPNPC_LIBRARY-NOTFOUND
-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=10
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ethserver/cpp-ethereum/build`

**Comment by Bitart** [comment]
I am facing the same problem with slitghtly differences to the output, but the issues are the same:

`-- Could NOT find leveldb (missing:  LEVELDB_LIBRARY LEVELDB_INCLUDE_DIR)
-- Could NOT find miniupnpc (missing:  MINIUPNPC_LIBRARY MINIUPNPC_INCLUDE_DIR)
-- miniupnpc headers: MINIUPNPC_INCLUDE_DIR-NOTFOUND
-- miniupnpc lib   : iphlpapi;optimized;MINIUPNPC_LIBRARY-NOTFOUND;debug;MINIUPNPC_LIBRARY_DEBUG-NOTFOUND`
