### ISSUE TITLE
Can't build on Ubuntu Server 17.04

### ISSUE THREAD

**Issue by tiagosleal** [ethereum/aleth#4121]
The following error occurs when I execute cmake --build . 

Scanning dependencies of target jsoncpp
[  0%] Performing install step for 'jsoncpp'
CMake Error at /home/minerador/cpp-ethereum/deps/src/jsoncpp-stamp/jsoncpp-install-.cmake:16 (message):
  Command failed: 2

   '/usr/bin/make' 'install'

  See also

    /home/minerador/cpp-ethereum/deps/src/jsoncpp-stamp/jsoncpp-install-*.log

CMakeFiles/jsoncpp.dir/build.make:73: recipe for target '../deps/src/jsoncpp-stamp/jsoncpp-install' failed
make[2]: *** [../deps/src/jsoncpp-stamp/jsoncpp-install] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/jsoncpp.dir/all' failed
make[1]: *** [CMakeFiles/jsoncpp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

tks

**Comment by chfast** [comment]
`cat /home/minerador/cpp-ethereum/deps/src/jsoncpp-stamp/jsoncpp-install-*.log`?

**Comment by kryztoval** [comment]
Try adding all those.
sudo apt-get install git cmake libleveldb-dev libjsoncpp-dev libboost-all-dev libgmp-dev libreadline-dev libcurl4-gnutls-dev ocl-icd-libopencl1 opencl-headers mesa-common-dev libmicrohttpd-dev build-essential libjsonrpccpp-dev

**Comment by halfalicious** [comment]
Please re-activate if this is still an issue
