### ISSUE TITLE
"cmake --build ." is stuck for more than 24 hours.

### ISSUE THREAD

**Issue by hard-fault** [ethereum/aleth#4208]
Hi,
I have a problem with building the code base.
I followed all the steps given on the ethereum git home page.
But ran into an issue with this command.

cmake --build . # Build all default targets.

/Users/shreyasm/Desktop/Github/cpp-ethereum/build
bash-3.2$ cmake --build .
[ 0%] Built target BuildInfo.h
[ 1%] Performing download step (download, verify and extract) for 'boost'
-- verifying file...
file='/Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost_1_63_0.tar.gz'
-- SHA256 hash of
/Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost_1_63_0.tar.gz
does not match expected value
expected: 'fe34a4e119798e10b8cc9e565b3b0284e9fd3977ec8a1b19586ad1dec397088b'
actual: 'efe2318e2797d664f9da43f38aa56440cd755b8ae81ba90edfdde4bc422d5711'
-- File already exists but hash mismatch. Removing...
-- Downloading...
dst='/Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost_1_63_0.tar.gz'
timeout='none'
-- Using src='https://github.com/ethereum/cpp-dependencies/releases/download/cache/boost_1_63_0.tar.gz'

It is stuck in that step for more than 24Hrs.

Please help me with this.

I am looking forward to fixing some bugs.

Thanks,
Shreyas Badiger

**Comment by pirapira** [comment]
Which operating system are you using?

**Comment by hard-fault** [comment]
I am using Mac OS X Yosemite

**Comment by pirapira** [comment]
I would use `pstree` to see what kind of child processes does `cmake` have.

**Comment by hard-fault** [comment]
Does this help?

shreyasm-mbp:cpp-ethereum shreyasm$ pstree | grep cmake
 | |     \--- 13287 shreyasm grep cmake
 |     \-+= 50046 shreyasm cmake --build .
 |             \-+- 50071 shreyasm /bin/sh -c cd /Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src && /usr/local/bin/cmake -P /Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost-stamp/download-boost.cmake
 |               \--- 50072 shreyasm /usr/local/bin/cmake -P /Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost-stamp/download-boost.cmake

**Comment by pirapira** [comment]
So, I guess this process 50072 is being stuck.  Let me try to reproduce this when I get home.

By the way, have you done `git submodule update --init --recursive`?

**Comment by hard-fault** [comment]
I hadn't done "git submodule update --init --recursive" before. Tried that and I have kept it for the build. I am not sure how much time will the build take this time. I will update on that.

**Comment by chriseth** [comment]
It seems that the download does not work. Your build machine needs access to the internet to download dependencies.

**Comment by hard-fault** [comment]
I am connected to the net all the while. Tried downloading it manually through link. Download didn't go to through. Any problem with the link?

**Comment by hard-fault** [comment]
pirapira. Were you able to get any solution for this? Please help.

**Comment by chriseth** [comment]
The url works fine for me (you are talking about https://github.com/ethereum/cpp-dependencies/releases/download/cache/boost_1_63_0.tar.gz right?)

**Comment by hard-fault** [comment]
I was able to download it manually.
But some problem through the "cmake --build ." command. 
It is still stuck for long though the file is hardly 90 odd Mbs.

bash-3.2$ cmake --build .
[  0%] Built target BuildInfo.h
[  1%] Performing download step (download, verify and extract) for 'boost'
-- verifying file...
       file='/Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost_1_63_0.tar.gz'
-- SHA256 hash of
    /Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost_1_63_0.tar.gz
  does not match expected value
    expected: 'fe34a4e119798e10b8cc9e565b3b0284e9fd3977ec8a1b19586ad1dec397088b'
      actual: 'b027d844bb30d24f62fe8072e7f6a80b6fa51caab3e4e5e5308a366a8f44d50d'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost_1_63_0.tar.gz'
   timeout='none'
-- Using src='https://github.com/ethereum/cpp-dependencies/releases/download/cache/boost_1_63_0.tar.gz'


How do I go about this one now? Can I bypass the downloading part from the script and point it to the one I manually downloaded?

**Comment by hard-fault** [comment]
I forked another repository and tried the steps once again. This time I replaced the manually downloaded file in - /Users/shreyasm/Desktop/Github/cpp-ethereum/deps/src/boost_1_63_0.tar.gz

and I facing new set of errors. Please help.
error logs - https://shrib.com/#hardfault

**Comment by pirapira** [comment]
You need to upgrade your llvm toolchain.  For that, you can follow `.travis.yml` script in `cpp-ethereum`.

**Comment by hard-fault** [comment]
Hi Pirapira,

I did update it according to the script.

shreyasm-mbp:cpp-ethereum shreyasm$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

The build is still failing. exact logs as above. (https://shrib.com/#hardfault)

**Comment by pirapira** [comment]
I don't believe `cmake --build .` appears anywhere in the Travis script or the bash scripts called from it.

**Comment by hard-fault** [comment]
Used this script - ./scripts/build.sh $TRAVIS_BUILD_TYPE
still facing errors. (https://shrib.com/#hardfault)

**Comment by pirapira** [comment]
I don't know any other way from following manually all commands in `travis.yml`.

**Comment by hard-fault** [comment]
Becuase some of the steps are not supported in mac-os-x

**Comment by hard-fault** [comment]
Is there any other way that I can go about? I am not giving up so easily :D

**Comment by pirapira** [comment]
I did folllow `travis.yml` on my Mac succesfully.  Which is the step not supported?

**Comment by thomaskey** [comment]
Not sure if this is same - 

But I was seeing hash mismatch on BOOST_1_64_0 after download and after each download during the hash check it would have different checksum from the same URL.  

It turns out my disk space wasn't large enough on my hard drive.  

Would be nice if cmake reported disk IO errors instead of repeating download in a loop...  I was in VM, I increased disk space and the build worked OK.
