### ISSUE TITLE
Error after ** BUILD SUCCEEDED ** 

### ISSUE THREAD

**Issue by CSPRNG** [ethereum/aleth#4223]
Hello

Please let me know what to change or try next. Thanks in advance.

Here is the END of the long listing, only showing the errors after ** BUILD SUCCEEDED **:

=== BUILD TARGET cryptopp-static OF PROJECT cryptopp WITH CONFIGURATION Release ===

Check dependencies

=== BUILD AGGREGATE TARGET ALL_BUILD OF PROJECT cryptopp WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/cryptopp.build/Release/ALL_BUILD.build/Script-190380F7B3834B99AE19E784.sh
chmod 0755 /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/cryptopp.build/Release/ALL_BUILD.build/Script-190380F7B3834B99AE19E784.sh

PhaseScriptExecution CMake\ Rules /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/cryptopp.build/Release/ALL_BUILD.build/Script-190380F7B3834B99AE19E784.sh
    cd /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp
    /bin/sh -c /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/cryptopp.build/Release/ALL_BUILD.build/Script-190380F7B3834B99AE19E784.sh
echo ""

echo Build\ all\ projects
Build all projects

** BUILD SUCCEEDED **

cd /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build && /usr/local/Cellar/cmake/3.8.2/bin/cmake -E touch /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-stamp/Debug/cryptopp-build
echo "Performing install step for 'cryptopp'"
Performing install step for 'cryptopp'
cd /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build && /usr/local/Cellar/cmake/3.8.2/bin/cmake -Dconfig=Debug -P /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-stamp/cryptopp-install-Debug.cmake
CMake Error at /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-stamp/cryptopp-install-Debug.cmake:16 (message):
  Command failed: 65

   '/usr/local/Cellar/cmake/3.8.2/bin/cmake' '--build' '/Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build' '--config' 'Release' '--target' 'install'

  See also

    /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-stamp/cryptopp-install-*.log

make: *** [/Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-stamp/Debug/cryptopp-install] Error 1
Command /bin/sh failed with exit code 2

**Comment by MarkKlein1** [comment]
Here is the end of log  /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-stamp/cryptopp-install-*.log  mentioning that libcryptopp.a was not found:
(I ran the one line script  ./scripts/install_deps.sh  to install external dependencies)
Where can  I find libcryptopp.a ?

=== BUILD AGGREGATE TARGET install OF PROJECT cryptopp WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/cryptopp.build/Release/install.build/Script-E2F74AAA7A054854A8E06A0C.sh
chmod 0755 /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/cryptopp.build/Release/install.build/Script-E2F74AAA7A054854A8E06A0C.sh

PhaseScriptExecution CMake\ PostBuild\ Rules /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/cryptopp.build/Release/install.build/Script-E2F74AAA7A054854A8E06A0C.sh
    cd /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp
    /bin/sh -c /Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/cryptopp.build/Release/install.build/Script-E2F74AAA7A054854A8E06A0C.sh
/usr/local/Cellar/cmake/3.8.2/bin/cmake -DBUILD_TYPE=Release -P cmake_install.cmake
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:38 (file):
  file INSTALL cannot find
  "/Users/benutzer/Documents/cpp-ethereum/deps/src/cryptopp-build/Release/libcryptopp.a".

make[1]: *** [install_buildpart_0] Error 1
Command /bin/sh failed with exit code 2

**Comment by halfalicious** [comment]
Please reactivate if you're still hitting this
