### ISSUE TITLE
[build-system] Most projects fail to load

### ISSUE THREAD

**Issue by Reed-gh** [ethereum/aleth#4292]
I am very new to bitcoin mining. I follow every step listed @ http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html, but when I open the generated solution in visual studio, most projects don't load. The project output log is [here](https://pastebin.com/raw/XT5QiC7U ) and a screen recording of the entire process is  [here](https://youtu.be/VDbp9F3Nbbo). Any help is appreciated.

-Reed

**Comment by chfast** [comment]
Nothing here is about bitcoin mining. But if you still want to build this project, follow instructions in the README: https://github.com/ethereum/cpp-ethereum#building-from-source.

**Comment by halfalicious** [comment]
Closing since I don't hit issues building on Win10 (using VS2015 and the instructions listed in the [README](https://github.com/ethereum/aleth/blob/master/README.md))
