### ISSUE TITLE
Prepare docker image for building cpp-ethereum

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#4377]
There are multiple reasons this is useful. 2 of them: some CI supports docker images naively, we can also test builds in isolated environment.

- [x] Choose the name.
- [x] Choose the versioning.
- [x] Choose the base.
- [x] Create Dockerfile in cpp-ethereum repo.
- [x] Enable auto-builds on https://hub.docker.com/r/ethereum.

As the base I suggest Ubuntu LTS or latest Debian. Debian would increase diversity as almost all devs use Ubuntu.

It would be nice to have versions with different compilers (or have multiple compilers in single image). This affects versioning. The size is not critical.

Please check:
- https://github.com/ethereum/cpp-ethereum/tree/develop/scripts/docker
- https://github.com/ethereum/cpp-ethereum/tree/develop/scripts/Dockerfile
- https://github.com/ethereum/solidity/blob/develop/scripts/Dockerfile

**Comment by tcsiwula** [comment]
^ mine! Hey @chfast working on ethereum/cpp-build-env docker automated builds now. Where should I place script in repo? Also do I need access to this to set up new automated build repo or would it exist altogether as new ethereum/cpp-build-env repo?

**Comment by chfast** [comment]
I would place it here in cpp-ethereum repo, as `scripts/docker/cpp-build-env.dockerfile`.

**Comment by chfast** [comment]
Please create a PR first. You can point Docker Hub to your PR first, then we will change this.

**Comment by tcsiwula** [comment]
Okay cool cool, finish today 😀👍🏻

**Comment by tcsiwula** [comment]
Hopefully we can iterate off of this one, I was having trouble finding multiple version of compilers on Debian apt-cache search my-package-name.

**Comment by axic** [comment]
@chfast isn't this done?

**Comment by chfast** [comment]
See #4811.

**Comment by axic** [comment]
Also see:
- https://github.com/karalabe/hive/issues/92
- https://github.com/karalabe/hive/tree/master/clients/cpp-ethereum:develop

**Comment by chfast** [comment]
I have problem with Docker Hub builds: https://hub.docker.com/r/ethereum/eth/builds/

**Comment by holiman** [comment]
It errors out with `Build failed: Dockerfile not found at ./Dockerfile`. Could it be https://docs.docker.com/docker-hub/builds/#create-an-automated-build : 

> It assumes the Dockerfile lives at the root of your source.

**Comment by chfast** [comment]
Yes, there was second build config entry there.

But the correct one also fails: https://hub.docker.com/r/ethereum/eth/builds/bedrgzgat9tjqkmjbbvccat/.

Maybe Docker Hub does not understand mulit-stage builds...

**Comment by chfast** [comment]
Do you know how to get build logs from https://hub.docker.com/r/ethereum/eth/builds/bvnvl4cha4acjorwyve2bze/ ?

It looks the build takes some time so it is doing something.

**Comment by halfalicious** [comment]
@chfast Can we close this or is there still work that needs to be done?
