### ISSUE TITLE
Generate DAG on demand

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#4390]
Just an idea. Because we don't support high performance mining, can we skip generating DAGs and storing them in filesystem. Instead allocate memory for DAG and fill it with zeros. When ethash search function asks for a DAG element it is taken from the DAG. If null (all zeros), the element must be generated and stored in the DAG. In other words -- classic cache.

The memory requirements is the same, but we don't have to pregenerate DAGs (takes a lot of time) nor maintain DAG storage on-disk.

**Comment by tiendq** [comment]
@chfast It's almost a year now, is there any progress you want to share? :)

Where can I look at (in code) to get more detail about your idea?

Thanks,

**Comment by chfast** [comment]
This is done. No DAG files any more.
