### ISSUE TITLE
RPC test failures in nightly tests

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#4582]
I strongly suspect that these regular failures on the test server:
```
TEST_mineBlockOnNode1 FAILED
TEST_mineBlockOnNode2 FAILED
```
are caused by mining beneficiary not being set.

Try running the nodes with `-a` parameter (probably add a parameter to `function startNode` in `ethconsole.js` to allow this)

**Comment by winsvega** [comment]
why is it working locally but failing on server?

**Comment by gumb0** [comment]
Because (I think) locally you have an author already set for your eth

**Comment by chfast** [comment]
It can also be ok locally because you have any Ethereum account created.

**Comment by gumb0** [comment]
Let's just get the full debug log from test server and see what's happening. Is it possible @winsvega ?

**Comment by gumb0** [comment]
As I remember the last thing happened here was @winsvega reporting that adding `-a` didn't help with failures on server.

cc @pirapira

**Comment by halfalicious** [comment]
@gumb0 : can we close this?

**Comment by gumb0** [comment]
We don't run those tests anymore

**Comment by chfast** [comment]
We do: https://circleci.com/workflow-run/95c0ec42-8955-4a1e-941b-43bb200284b4.

**Comment by gumb0** [comment]
@chfast We run nightly tests, but I don't think we run those @winsvega's RPC tests that I referred to here - those were run with `cd tests/RPCTests; node main.js cpp-ethereum/build/eth/eth`

**Comment by winsvega** [comment]
that RPC tests I deleted. now have a new test suite for retesteth.
