### ISSUE TITLE
UPnP device availability not periodically checked

### ISSUE THREAD

**Issue by trungtt1981** [ethereum/aleth#4717]
When starting "eth" node in private mode (using the option --private), if UPnP device is not found then we get the below messages:

p2p  UPnP device not found.
p2p  Listen address 10.0.1.45 differs from local address 0.0.0.0 returned by UPnP!
p2p  p2p.started id: ##854495ba…
eth  void dev::p2p::Host::start() 8010 ms

After that, if UPnP device is enabled and thus available, then looks like that the "eth" node doesn't check again the UPnP device availability.

Suggestion is that "eth" node has to periodically check the UPnP device availability.

**Comment by chfast** [comment]
We don't support UPnP any more. We just left it as it was (disabled by default).

**Comment by halfalicious** [comment]
@chfast : Can we close this?
