### ISSUE TITLE
Win10 x64, VS2017 with VS15 and VS14 toolchains, MSBuild/hunter failing at build

### ISSUE THREAD

**Issue by SteelPh0enix** [ethereum/aleth#4732]
All right, so i've tried to build it today. I have updated Win10, with updated Visual Studio 2017, and i've installed v140 toolchain, because on build site it says that this is compatible only with VS14 2015. I have installed MSBuild too, and added to PATH. And yes, i've ran install_deps ealier.

So, when i try to run
`cmake -G "Visual Studio 14 2015 Win64" ..`
i get this: https://hastebin.com/raw/aremeracur
I have only "The system is: Windows - 10.0.16299 - AMD64" in CMakeOutput.log, no other logs.

So, i thought it's worth a try to build it using VS15 toolchain, maybe this will work *somehow*.

So, cleaned up the build dir, ran `cmake -G "Visual Studio 15 2017 Win64" ..`, aaaand...
this is  the output: https://hastebin.com/raw/dimawiniba
this is CMakeOutput.log: https://hastebin.com/raw/asuhomijez
And this is CMakeError.log: https://hastebin.com/raw/zedaqemuxu (translated a little, because it was in polish)

My CMake version is 3.10.0-rc3. I'm not suprised it doesn't work on VS15 toolchain, but why do i get this error from VS14 try? Isn't VS2017 completely supported, should i install VS2015 to build it, even when i have v140 toolchain installed?

**Comment by chfast** [comment]
Polish is fine.

I'm not sure exactly, but Hunter had problems with building Boost with VS2017. We have not upgraded the Hunter yet, so this might be the case.

What you can do now is to make sure you fully deleted the build dir and Hunter dir (C:\Hunter). Try again with clean build dir.

Still, I'm not sure you will be able to build with VS2017, because we have leveldb prebuilt with VS2015 and nobody had time to upgrade it yet.

**Comment by SteelPh0enix** [comment]
Tried the clean build, still, it appears that i don't have Hunter dir in C:/ (neither Hunter nor .hunter), seems like it was automatically deleted.

**Comment by timtait** [comment]
Had this same issue, solved it by installing 2015 build tools - http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by halfalicious** [comment]
@chfast : I have no problems building using 2015 or 2017 and according to @timtait it looks like installing the 2015 build tools solves the issue, perhaps we can close this?
