### ISSUE TITLE
centos7.3 build failed 

### ISSUE THREAD

**Issue by hitstabber** [ethereum/aleth#4737]
...patience...
...found 1021 targets...
...updating 40 targets...
common.mkdir stage
common.mkdir bin.v2/libs
common.mkdir stage/lib
common.mkdir bin.v2/libs/program_options
common.mkdir bin.v2/libs/program_options/build
common.mkdir bin.v2/libs/program_options/build/gcc-7
common.mkdir bin.v2/libs/program_options/build/gcc-7/debug
common.mkdir bin.v2/libs/program_options/build/gcc-7/release
common.mkdir bin.v2/libs/program_options/build/gcc-7/debug/link-static
common.mkdir bin.v2/libs/program_options/build/gcc-7/release/link-static
common.mkdir bin.v2/libs/program_options/build/gcc-7/debug/link-static/threading-multi
common.mkdir bin.v2/libs/program_options/build/gcc-7/release/link-static/threading-multi
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/debug/link-static/threading-multi/config_file.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/debug/link-static/threading-multi/cmdline.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.

    "/opt/rh/devtoolset-7/root/usr/bin/c++" "-std=c++11"   -O0 -fno-inline -Wall -g -pthread -m64  -DBOOST_ALL_NO_LIB=1  -I"." -c -o "bin.v2/libs/program_options/build/gcc-7/debug/link-static/threading-multi/cmdline.o" "libs/program_options/src/cmdline.cpp"

...failed gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/debug/link-static/threading-multi/cmdline.o...

**Comment by hitstabber** [comment]
What should I do?

**Comment by chfast** [comment]
You are running out of memory? How much RAM do you have?

**Comment by chfast** [comment]
In main CMakeLists.txt, change `set(HUNTER_JOBS_NUMBER 4)` to `1`. Tell me if it helps.
