### ISSUE TITLE
AlethZero : issue with contact creation

### ISSUE THREAD

**Issue by yann300** [ethereum/aleth#481]
Newly created contracts appeared (after mining) in the BlockChain panel but not in the Contracts Panel.

If we try to get the contract using JavaScript API we get a null value (0x) : 
var contractAddress = '0x23ad1d3f61ed6c760011045e891351b6e974a6a0';
web3.eth.stateAt(contractAddress, "77dfd757197320708ea50455467e1edeb2ca773f").then(function(res){ 
        document.getElementById('resultContract').innerText = res; //web3.toDecimal(res); 
}); 

Contract code : 
init:
    contract.storage[msg.sender] = 10000
code:
    to = msg.data[0]
    from = msg.sender
    value = msg.data[1]
    if contract.storage[from] >= value:
        contract.storage[from] = contract.storage[from]  - value
        contract.storage[to] = contract.storage[to] + value

**Comment by phaldenby** [comment]
Looks like on v0.8.2 it is back to not working.. have you tried it lately, @yann300 ? 

http://forum.ethereum.org/discussion/1634/tutorial-1-your-first-contract/p1

**Comment by yann300** [comment]
I will check that, but I suggest to use Solidity instead of Serpent (as
this is more advanced than Serpent). You can find some examples there:
https://github.com/ethereum/dapp-bin

2015-03-11 21:37 GMT+01:00 phaldenby <notifications@github.com>:

**Comment by yann300** [comment]
So you should definitely use Solidity instead of Serpent, Solidity is our
primary language and Serpent is not always up to date.
Here some links related to Solidity:

https://github.com/ethereum/wiki/wiki/Solidity,-Docs-and-ABI
https://github.com/ethereum/wiki/wiki/Solidity-Tutorial
https://github.com/ethereum/wiki/wiki/Solidity-Features

2015-03-12 9:54 GMT+01:00 Yann Levreau <yann.levreau@gmail.com>:
