### ISSUE TITLE
compile eth client from source but starts happened with p2p  UPnP device not found.

### ISSUE THREAD

**Issue by wangmaodong** [ethereum/aleth#4839]
~/develop/cpp-ethereum/build/eth/eth 
cpp-ethereum, a C++ Ethereum client
cpp-ethereum 1.3.0
  By cpp-ethereum contributors, (c) 2013-2018.
  See the README for contributors and credits.
  ℹ  01:35:40 PM.396|**p2p  UPnP device not found.**
Node ID: enode://eb2336d314e7aecbb99d98b59b7e8c1a2256fb778d4d8b2ed1cd915c0257e4785ec206e136f991cec448df02cb6c24141ba938808130f381b9adb61319bdac8d@0.0.0.0:0
JSONRPC Admin Session Key: +SToxbdA/JI=
⧎ ✘  01:35:41 PM.065|p2p|bd335bee…|Parity/v1.7.9-stable-12940e4-20171113/x86_64-linux-gnu/rustc1.21.0  **Error reading - Abrupt peer disconnect: End of file**
⧎ ✘  01:35:41 PM.104|p2p|827ed216…|Parity/v1.7.9-stable-12940e4-20171113/x86_64-linux-gnu/rustc1.21.0  **Error reading - Abrupt peer disconnect: End of file**
⧎ ✘  01:35:41 PM.107|p2p|6377f4a1…|Parity/v1.7.9-stable-12940e4-20171113/x86_64-linux-gnu/rustc1.21.0  **Error reading - Abrupt peer disconnect: End of file**
#

**Comment by halfalicious** [comment]
This is expected, we disable UPNP by default at compile time because our UPNP implementation has security issues.
