### ISSUE TITLE
build error with latest pull from develop branch

### ISSUE THREAD

**Issue by boosth** [ethereum/aleth#4849]
Previous build from a couple of weeks back was successful. Experiencing crashes while syncing the blockchain. Updated with git pull and now seeing this build error:

[ 40%] Building CXX object libevm/CMakeFiles/evm.dir/ExtVMFace.cpp.o
/usr/local/src/cpp-ethereum/libevm/ExtVMFace.cpp: In function ‘void dev::eth::{anonymous}::create(evm_result*, dev::eth::ExtVMFace&, const evm_message*)’:
/usr/local/src/cpp-ethereum/libevm/ExtVMFace.cpp:157:30: error: ‘const struct evm_message’ has no member named ‘input_data’; did you mean ‘input_size’?
  bytesConstRef init = {_msg->input_data, _msg->input_size};
                              ^~~~~~~~~~
/usr/local/src/cpp-ethereum/libevm/ExtVMFace.cpp:157:58: error: could not convert ‘{<expression error>, _msg->evm_message::input_size}’ from ‘<brace-enclosed initializer list>’ to ‘dev::bytesConstRef {aka dev::vector_ref<const unsigned char>}’
  bytesConstRef init = {_msg->input_data, _msg->input_size};
                                                          ^
/usr/local/src/cpp-ethereum/libevm/ExtVMFace.cpp: In function ‘void dev::eth::{anonymous}::call(evm_result*, evm_context*, const evm_message*)’:
/usr/local/src/cpp-ethereum/libevm/ExtVMFace.cpp:218:38: error: ‘const struct evm_message’ has no member named ‘destination’
  params.codeAddress = fromEvmC(_msg->destination);
                                      ^~~~~~~~~~~
/usr/local/src/cpp-ethereum/libevm/ExtVMFace.cpp:221:23: error: ‘const struct evm_message’ has no member named ‘input_data’; did you mean ‘input_size’?
  params.data = {_msg->input_data, _msg->input_size};
                       ^~~~~~~~~~
/usr/local/src/cpp-ethereum/libevm/ExtVMFace.cpp:221:51: error: no match for ‘operator=’ (operand types are ‘dev::bytesConstRef {aka dev::vector_ref<const unsigned char>}’ and ‘<brace-enclosed initializer list>’)
  params.data = {_msg->input_data, _msg->input_size};
                                                   ^
In file included from /usr/local/src/cpp-ethereum/libdevcore/Common.h:54:0,
                 from /usr/local/src/cpp-ethereum/libethcore/BlockHeader.h:25,
                 from /usr/local/src/cpp-ethereum/libevm/ExtVMFace.h:22,
                 from /usr/local/src/cpp-ethereum/libevm/ExtVMFace.cpp:18:
/usr/local/src/cpp-ethereum/libdevcore/vector_ref.h:21:7: note: candidate: dev::vector_ref<const unsigned char>& dev::vector_ref<const unsigned char>::operator=(const dev::vector_ref<const unsigned char>&)
 class vector_ref
       ^~~~~~~~~~
/usr/local/src/cpp-ethereum/libdevcore/vector_ref.h:21:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const dev::vector_ref<const unsigned char>&’
/usr/local/src/cpp-ethereum/libdevcore/vector_ref.h:21:7: note: candidate: dev::vector_ref<const unsigned char>& dev::vector_ref<const unsigned char>::operator=(dev::vector_ref<const unsigned char>&&)
/usr/local/src/cpp-ethereum/libdevcore/vector_ref.h:21:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘dev::vector_ref<const unsigned char>&&’
libevm/CMakeFiles/evm.dir/build.make:62: recipe for target 'libevm/CMakeFiles/evm.dir/ExtVMFace.cpp.o' failed
make[2]: *** [libevm/CMakeFiles/evm.dir/ExtVMFace.cpp.o] Error 1
CMakeFiles/Makefile2:597: recipe for target 'libevm/CMakeFiles/evm.dir/all' failed
make[1]: *** [libevm/CMakeFiles/evm.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gumb0** [comment]
`git submodule update` should help

**Comment by gumb0** [comment]
@boosth Did it help?
