### ISSUE TITLE
Lack of bootnode mechanism

### ISSUE THREAD

**Issue by trungtt1981** [ethereum/aleth#4855]
The current implementation (at the time of writing) of cpp-ethereum lacks of the bootnode implementation when compared against the go-ethereum.
We do need to have a C++ implementation of bootnode. Otherwise, we must borrow the "bootnode" from go-ethereum. However, it is impossible to use this kind of "bootnode" for bootstrapping the "eth" nodes to p2p network. This is because "bootnode" initiates UDP endpoints whereas the "eth" nodes accept only TCP endpoints. 
Alternative to the C++ implementation of bootnode, we can change the cpp-ethereum implementation in such a way that it accepts UDP endpoint. Particularly, the change can happen inside the following function:
```

//libp2p/Host.cpp
void Host::connect(std::shared_ptr<Peer> const& _p)
{
    ....
    bi::tcp::endpoint ep(_p->endpoint);
}
```
Furthermore, go-ethereum client supports the option "--bootnodes" which is also missing in cpp-ethereum. We should support this nice option as well.

**Comment by gumb0** [comment]
Similar or the same: https://github.com/ethereum/cpp-ethereum/issues/4703

**Comment by trungtt1981** [comment]
My understanding is that the current (or latest or stable at the time of writing) release of cpp-ethereum does not have a real mechanism of bootstrapping. Although the default behavior has a boolean flag "bootstrap", but it is just a fake bootstrap because all what it does is exactly like the addPeer process which is based on TCP and doesn't accept UDP. This is a bug.

**Comment by gumb0** [comment]
`--bootstrap` means connect to existing known bootnodes of the network (main net or ropsten)
Running the bootnode requires `--mode peer` (not working now)

My understanding is that lower-level node discovery protocol is based on UDP, it is for sure present in cpp-ethereum, see `NodeTable` class
Higher-level devp2p protocol uses TCP.

Then, bootnode is a node that runs only this node discovery protocol, but not devp2p.

**Comment by trungtt1981** [comment]
@gumb0 
At first, thanks very much for your feedback on my stuffs although I can rarely received positive feedbacks from the gitter channel.

In file "eth/main.cpp", at the function main(), we have the boolean flag "bootstrap" set to true by default. This flag is used right here:

if (bootstrap && privateChain.empty())
        for (auto const& i: Host::pocHosts())
            web3.requirePeer(i.first, i.second);

Where:
Host::pocHosts() will return a list of hard-coded Ethereum nodes which I strongly believe that they are not bootnodes from go-ethereum. Instead, they are full nodes of go-ethereum or some parity. None of them are from cpp-ethereum. Why I believe this is because if they are bootnodes, then the web3.requirePeer() will be failed due to conflict between TCP and UDP.

web3.requirePeer() will actually invoke the addPeer() that uses only TCP. This means that even if we have a running "--mode peer" of cpp-ethereum, then we still cannot use it because "--mode peer" would use UDP only.

**Comment by trungtt1981** [comment]
I have a suggestion to improve the bootstrapping mechanism for cpp-ethereum.
1. 
We can implement a separate bootstrap server (in any form). Any "eth" clients, when started, can connect to this bootstrap server to obtain the list of available "eth" nodes (i.e. peers). After that, the "eth" client can iteratively addPeer() with this list.

2. 
In the folder "cpp-ethereum/eth" where the main.cpp file is contained, we can add some config file which includes several IP:port entries of the bootstrap server (mentioned above). This way, we can avoid hard-coding the list of bootstrap servers.

3.
We will modify the function main() of "cpp-ethereum/eth/main.cpp" so that it will read the config file mentioned above to get the list of available bootstrap servers from which the list of peers can be obtained. Then, "eth" client can iteratively addPeer.

What would you evaluate my suggestion?

**Comment by gumb0** [comment]
> web3.requirePeer() will actually invoke the addPeer() that uses only TCP.

I don't think so, `requirePeer` adds the peer to `NodeTable` and so includes it in the node discovery, too.
There is no conflict between TCP and UDP.
