### ISSUE TITLE
Windows build from develop branch does not compile or configure.

### ISSUE THREAD

**Issue by sundansx** [ethereum/aleth#4866]
I followed directions for building the 'develop' branch Windows build with Visual studio 2015 (using community ed.).  when I run the config step, it almost ends, but fails when trying to configure:
 Boost include path:
 ```
 C:/.hunter/_Base/a412c45/1737dfc/391719a/Install/include
  Could not find the following static Boost libraries:
          boost_fiber
Call Stack (most recent call first):
  C:/.hunter/_Base/a412c45/1737dfc/391719a/Install/lib/cmake/Boost/BoostConfig.cmake:40 (find_package)
  CMakeLists.txt:107 (find_package)
[hunter ** INTERNAL **] Library not exists: Boost_FIBER_LIBRARY_DEBUG-NOTFOUND
[hunter ** INTERNAL **] [Directory:C:/.hunter/_Base/a412c45/1737dfc/391719a/Install/lib/cmake/Boost]

CMake Error at C:/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.19.232/a412c45/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  C:/.hunter/_Base/a412c45/1737dfc/391719a/Install/lib/cmake/Boost/BoostConfig.cmake:88 (hunter_internal_error)
  CMakeLists.txt:107 (find_package)
```
I then just copied the boost_fiber binary libs from my latest version boost install (and renamed) to the .hunter folder and the config continued and built the VS solution properly.

When I tried to compile the solution in VS2015 I got many errors, with nearly all of them of these two types:
```
Error	C2039	'literals': is not a member of 'boost::multiprecision' (compiling source file E:\temp\CKprogramming\VC2015\cpp-ethereum\libdevcore\CommonData.cpp)	devcore	e:\temp\ckprogramming\vc2015\cpp-ethereum\libdevcore\Common.h	69	Build	
Error	C2871	'literals': a namespace with this name does not exist (compiling source file E:\temp

\CKprogramming\VC2015\cpp-ethereum\libdevcore\CommonData.cpp)	devcore	e:\temp\ckprogramming\vc2015\cpp-ethereum\libdevcore\Common.h	69	Build	
Error	C2177	constant too big (compiling source file E:\temp\CKprogramming\VC2015\cpp-ethereum\libdevcore\CommonData.cpp)	devcore	e:\temp\ckprogramming\vc2015\cpp-ethereum\libdevcore\Common.h	155	Build	
```
I looked at the boost headers and I don't see a literals namespace or class anywhere in the multiprecision library.  I am not sure what is going on with the too big error.  I configured both the 64bit and 32bit projects and tried debug and release...same result.
please help.

**Comment by gumb0** [comment]
What is your exact version of VS2015 ?
It works for me with `Version 14.0.25431.01 Update 3`

**Comment by sundansx** [comment]
Community edition 2015, Version 14.0.25123.00 Update 2.  I will update VS2015 to update 3.  Did you do anything special like build in the developer command prompt?

**Comment by gumb0** [comment]
No, I build from VS

**Comment by chfast** [comment]
Modifying Hunter build dir is bad idea. Try again because we upgraded Hunter since then.

**Comment by halfalicious** [comment]
@chfast : Can we close this?

**Comment by sundansx** [comment]
yes, you can close this.
