### ISSUE TITLE
Node Discovery security improvements

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#4959]
1. When we receive Pong packet, we should validate that it's a response to some of the Pings that we've sent.
https://github.com/ethereum/devp2p/blob/master/discv4.md#endpoint-proof

See also related fix of the Pong packet https://github.com/ethereum/cpp-ethereum/pull/4915

**Comment by gumb0** [comment]
Also before sending `FindNode` ourselves, we need to check whether we've send this node our `Pong` in the last 12 hours, and initiate `Ping` if we didn't
https://github.com/ethereum/go-ethereum/blob/a7501d0c419f8c1dc8b4004c115dd2d4e3b524b7/p2p/discover/udp.go#L326-L331

**Comment by halfalicious** [comment]
I’ll work on #2, the fix should be fairly trivial so I should have something ready for PR (including unit tests) soon

**Comment by gumb0** [comment]
3 is left to implement here

**Comment by halfalicious** [comment]
I'm working on item 3 and should have something ready in the next day or 2 (I've finished the feature changes and have created a test but I think I want to make the test more stable).
