### ISSUE TITLE
make error...

### ISSUE THREAD

**Issue by willfu** [ethereum/aleth#4990]
centos 7, follow http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/index.html

when make in build dir, below errors occur.
[root@abc build]# make
[  4%] Built target secp256k1
[  7%] Built target mpir
[ 11%] Built target libff
[ 14%] Built target binaryen
[ 14%] Built target BuildInfo.h
[ 23%] Built target devcore
[ 23%] Building CXX object libdevcrypto/CMakeFiles/devcrypto.dir/SecretStore.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [libdevcrypto/CMakeFiles/devcrypto.dir/SecretStore.cpp.o] Error 4
make[1]: *** [libdevcrypto/CMakeFiles/devcrypto.dir/all] Error 2
make: *** [all] Error 2

**Comment by jwasinger** [comment]
I think your build environment doesn't have enough memory to compile the project.

**Comment by chfast** [comment]
@jwasinger is right. What hardware are you building it on @willfu ?

**Comment by willfu** [comment]
the ram is 1GB, does this require more? what's the basic requirement of hardware?

**Comment by chfast** [comment]
This is quite low memory for C++ compiler. But you can cross-compile for target platform on some PC.
