### ISSUE TITLE
Could I install cpp-ethereum on macOS Sierra?

### ISSUE THREAD

**Issue by GogoBoom** [ethereum/aleth#5015]
Hi guys,

Can you install cpp-ethereum on macOS Sierra(10.12.6)?
I tried to do it, but I got the error:CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:90 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180511-3958-nbzk1u/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

**Comment by halfalicious** [comment]
@chfast: Can we close this?
