### ISSUE TITLE
install_cmake.sh is not working

### ISSUE THREAD

**Issue by ghostric** [ethereum/aleth#5032]
C:\cpp-ethereum\scripts>install_deps.bat
'cmake' is not recognized as an internal or external command,
operable program or batch file.

im running this in my command prompt and i followed the readme file in the cpp-ethereum folder also reading  https://ethereumbuilders.gitbooks.io/guide/content/en/win_cpp_build.html which i read somewhere it was an older version. 
whenever i try to get the dependencies and start the project the book has for setup i get the cmake issue above. again being new im probably missing something simple. i followed the first part of the book (the git function for windows) but im stuck on step number two getting the dependencies. any help and tips are much appreciated as i made it my goal to learn as much as i can about solidity block chains and ethereum over the summer

**Comment by ghostric** [comment]
Yes i have cmake installed but i probably did something wrong when installing I'll try again but use the alternate method they give

**Comment by gumb0** [comment]
@ghostric Is your issue resolved?

**Comment by ghostric** [comment]
No still unable to get the dependencies but havent had time to work on it properly and installing cmake from the cpp folder wasnt working for what i tried, dont have an example at the time.

**Comment by ghostric** [comment]
$ scripts/install_cmake.sh --prefix cmake
Downloading CMake (https://cmake.org/files/v3.7/cmake-3.7.1-MINGW64_NT-10.0-x86_64.tar.gz)...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

file location:  ~/ether/cpp-ethereum (develop)
$ scripts/install_cmake.sh --prefix /usr/local
Downloading CMake (https://cmake.org/files/v3.7/cmake-3.7.1-MINGW64_NT-10.0-x86_64.tar.gz)...
mkdir: cannot create directory ‘/usr/local’: Permission denied

this is whats happening do i have it in an improper location or am i missing something i need to add?

**Comment by halfalicious** [comment]
@gumb0: Can we close this old bug? I don’t have any issues running the script on Windows (as long as I install cmake first and add it to my path)

**Comment by gumb0** [comment]
The script looks to be working for me on Linux, too.
