### ISSUE TITLE
createIntermediateState should warn after Byzantium

### ISSUE THREAD

**Issue by winsvega** [ethereum/aleth#5033]
createIntermediateState function does not work properly after Byzantium fork and should warn upon execution call that it should not be used.

**Comment by gumb0** [comment]
Warn how? It's a lower-level function.

And it should work after Byzantium by re-executing transactions in the block

**Comment by winsvega** [comment]
warn like a message to log saying that you are trying to use intemidiate state that is not supported or super slow.

**Comment by gumb0** [comment]
It is used by RPC methods, RPC method users don't normally see the log, it's not a good way to communicate anything to an RPC caller through log.

**Comment by winsvega** [comment]
How to get the final state then?

**Comment by gumb0** [comment]
Final state of the block after applying the rewards, according to the block header state root hash:
`debug_storageRangeAt(blockNum + 1, 0, begin, maxResults)`

**Comment by winsvega** [comment]
maybe just return final state of the block with rewards with 
`debug_storageRangeAt(blockNum, trNumber + 1, begin, maxResults)`

**Comment by gumb0** [comment]
That would be a new non-obvious agreement around calling this method, which sounds like a bad interface design to me.

To get the final state of the latest block: `debug_storageRangeAt("pending", 0, begin, maxResults)`
(that is, the state before the 0th transaction of the pending block)
But this call doesn't work at the moment, should be fixed.

**Comment by gumb0** [comment]
Maybe it's better to handle a special case of `blockNum + 1` when `blockNum` is latest instead of supporting "pending", it'd not much difference in implementation.
I asked for opinions in #testing channel in Discord.

**Comment by gumb0** [comment]
> maybe just return final state of the block with rewards with
debug_storageRangeAt(blockNum, maxTransactions + 1, begin, maxResults)

@winsvega I implemented this, is this issue resolved?

**Comment by winsvega** [comment]
Yes
