### ISSUE TITLE
client run a transaction again with each eth_get  RPC request

### ISSUE THREAD

**Issue by winsvega** [ethereum/aleth#5034]
Here is the issue.
A transaction impoted with a block and executed. 
[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"debug_accountRangeAt","params":["1", 1000, "0", 1000],"id":5}
transaction executed again

A returned is list of accounts.
for each account from that list 
{

[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"eth_getBalance","params":["a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "1"],"id":6}

a transaction is executed again

[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"eth_getCode","params":["a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "1"],"id":7}

a transaction is executed again

[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "1"],"id":8}

a transaction is executed again

[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"debug_storageRangeAt","params":["1", 1000, "a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "0", 1000],"id":9}

a transaction is executed again

}

**Comment by gumb0** [comment]
It shouldn't unless it accesses intermediate state in the block after Byzantium

**Comment by gumb0** [comment]
Why?

**Comment by winsvega** [comment]
Because it is very slow. At least there should be alternative with the most recent post state

**Comment by gumb0** [comment]
How slow? It's still useful.

You can always get the post-block state without re-executing transactions.

**Comment by winsvega** [comment]
```
Here is the issue.
A transaction impoted with a block and executed. 
[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"debug_accountRangeAt","params":["1", 1000, "0", 1000],"id":5}
transaction executed again

A returned is list of accounts.
for each account from that list 
{

[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"eth_getBalance","params":["a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "1"],"id":6}

a transaction is executed again

[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"eth_getCode","params":["a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "1"],"id":7}

a transaction is executed again

[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "1"],"id":8}

a transaction is executed again

[35m2018-05-25 18:13:37[0m [34meth[0m rpc {"jsonrpc":"2.0","method":"debug_storageRangeAt","params":["1", 1000, "a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "0", 1000],"id":9}

a transaction is executed again

}
```

**Comment by winsvega** [comment]
So each time a Block(hash) class is constructed. all its transactions are executed again
https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/Block.cpp#L186

**Comment by gumb0** [comment]
Right, weird. I wonder why it was implemented like that, perhaps the intention was to get the state after all transactions but before applying rewards.

We could change this to constructing the state from the state root hash of the block (it would include applying rewards), but first we'd need to investigate
- which tests and what else it could break
- which state exactly does geth return from `eth_getBalance` etc.

**Comment by gumb0** [comment]
@halfalicious  Could you please check how this works, if you have time?

The issue here is that RPC methods, that access the state according to requested block, recreate the state at the end of the block by re-running all the block transactions. We could optimize it by accessing the final state directly via state root hash.

First, I'd like to check which state does geth return - it's either the one at the very end of the block after applying rewards to the block beneficiary, or the one before applying rewards. This can be checked by calling `eth_getBalance` for block beneficiary for any block.
Then compare to what aleth returns in the similar case - according to @winsvega's investigation we return the state before applying rewards.

If it's really different from geth, we could fix it, potentially improving RPC performance significantly.

**Comment by halfalicious** [comment]
@gumb0 Will start looking at this this week if I have the time

**Comment by halfalicious** [comment]
> 
> 
> @halfalicious Could you please check how this works, if you have time?
> 
> The issue here is that RPC methods, that access the state according to requested block, recreate the state at the end of the block by re-running all the block transactions. We could optimize it by accessing the final state directly via state root hash.
> 
> First, I'd like to check which state does geth return - it's either the one at the very end of the block after applying rewards to the block beneficiary, or the one before applying rewards. This can be checked by calling `eth_getBalance` for block beneficiary for any block.
> Then compare to what aleth returns in the similar case - according to @winsvega's investigation we return the state before applying rewards.
> 
> If it's really different from geth, we could fix it, potentially improving RPC performance significantly.

A couple of questions:
* Where in `block.cpp` is the offending code, @winsvega 's link no longer resolves? I took a quick look at `Block.cpp:186` which is a call into `Block::sync` with the latest block hash - if this is still the correct location, is the problem that the RPC functions are calling this before they query the state?
* Regarding this:

> 
> First, I'd like to check which state does geth return - it's either the one at the very end of the block after applying rewards to the block beneficiary, or the one before applying rewards. This can be checked by calling eth_getBalance for block beneficiary for any block.
> Then compare to what aleth returns in the similar case - according to @winsvega's investigation we return the state before applying rewards.
> 
> If it's really different from geth, we could fix it, potentially improving RPC performance significantly.

To verify that I understand this correctly - if Geth also returns the account balance w/o the block reward, this means that Geth is also executing all of the txs in the block rather than looking it up via the state root since the pre-block-reward balance isn't a part of the final state?

**Comment by halfalicious** [comment]
@gumb0 Ah, I think I see the problem - for example, `Eth::eth_getBalanceAt` calls `ClientBase::balanceAt `which calls `ClientBase::blockByNumber` which constructs a new block, and constructing a new block takes the parent block's state root and then builds the requested block's state root by replaying all of the transactions (`Block::populateFromChain`)

**Comment by halfalicious** [comment]
@gumb0 / @winsvega I'm seeing Geth report the same balance (946.25 ether) for the block beneficiary (`0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89`) for [block 20365 on mainnet](https://etherscan.io/block/20365):

**Geth**
```
geth attach ipc:\\.\pipe\geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.27-stable-4bcc0a37/windows-amd64/go1.11.5
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
> web3.eth.syncing
{
  currentBlock: 20365,
  highestBlock: 8306617,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 0
}
> web3.eth.getBlock(20365)
{
  difficulty: 992664657586,
  extraData: "0x616c6c6120686f7070",
  gasLimit: 5000,
  gasUsed: 0,
  hash: "0xbc16ec8bd9a33fafb31f7dde81b6309dad199287b1046aaeedafdb522ff74b2b",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",
  mixHash: "0xca4ce299a6dbe7ba712fc5c9f1a7fe5399a6f9e62b836d423cf245f36170a6a9",
  nonce: "0xe1897e4350804c7e",
  number: 20365,
  parentHash: "0x538ee2fc49703085ee44b8507ca5faeb8ee54e5e697a5071aeb4064e6af47460",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 523,
  stateRoot: "0x049a838203b095fd50c6c02b07f9125a73e9f78949f46d5d2908e89d7406109f",
  timestamp: 1438494603,
  totalDifficulty: 10936284678681386,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
> web3.fromWei(web3.eth.getBalance("0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",20365))
946.25
```

**Aleth**
```
geth attach ipc:\\.\pipe\geth.ipc
Welcome to the Geth JavaScript console!

instance: aleth/1.7.0-alpha.1-38+commit.0faec9d1.dirty/windows/msvc19.22.27905.0/release
coinbase: 0x0038aed9783f127776f2a6a175f7efd1b9a2e97c
at block: 502739 (Fri, 06 Nov 2015 23:12:41 PST)
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 web3:1.0

> web3.eth.getBlock(20365)
{
  author: "0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",
  boundary: "0x00000000011b8e11293cde98ea348d7f3fda00d29c7c3e7b028063c71fee92b0",
  difficulty: 992664657586,
  extraData: "0x616c6c6120686f7070",
  gasLimit: 5000,
  gasUsed: 0,
  hash: "0xbc16ec8bd9a33fafb31f7dde81b6309dad199287b1046aaeedafdb522ff74b2b",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",
  mixHash: "0xca4ce299a6dbe7ba712fc5c9f1a7fe5399a6f9e62b836d423cf245f36170a6a9",
  nonce: "0xe1897e4350804c7e",
  number: 20365,
  parentHash: "0x538ee2fc49703085ee44b8507ca5faeb8ee54e5e697a5071aeb4064e6af47460",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  seedHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 0,
  stateRoot: "0x049a838203b095fd50c6c02b07f9125a73e9f78949f46d5d2908e89d7406109f",
  timestamp: 1438494603,
  totalDifficulty: 10936284678681386,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
> web3.fromWei(web3.eth.getBalance("0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",20365))
946.25
```

**Comment by halfalicious** [comment]
> 
> 
> @gumb0 / @winsvega I'm seeing Geth report the same balance (946.25 ether) for the block beneficiary (`0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89`) for [block 20365 on mainnet](https://etherscan.io/block/20365) so it looks like Geth is also retrieving the pre-rewards balance:
> 
> **Geth**
> 
> ```
> geth attach ipc:\\.\pipe\geth.ipc
> Welcome to the Geth JavaScript console!
> 
> instance: Geth/v1.8.27-stable-4bcc0a37/windows-amd64/go1.11.5
>  modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
> > web3.eth.syncing
> {
>   currentBlock: 20365,
>   highestBlock: 8306617,
>   knownStates: 0,
>   pulledStates: 0,
>   startingBlock: 0
> }
> > web3.eth.getBlock(20365)
> {
>   difficulty: 992664657586,
>   extraData: "0x616c6c6120686f7070",
>   gasLimit: 5000,
>   gasUsed: 0,
>   hash: "0xbc16ec8bd9a33fafb31f7dde81b6309dad199287b1046aaeedafdb522ff74b2b",
>   logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>   miner: "0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",
>   mixHash: "0xca4ce299a6dbe7ba712fc5c9f1a7fe5399a6f9e62b836d423cf245f36170a6a9",
>   nonce: "0xe1897e4350804c7e",
>   number: 20365,
>   parentHash: "0x538ee2fc49703085ee44b8507ca5faeb8ee54e5e697a5071aeb4064e6af47460",
>   receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
>   size: 523,
>   stateRoot: "0x049a838203b095fd50c6c02b07f9125a73e9f78949f46d5d2908e89d7406109f",
>   timestamp: 1438494603,
>   totalDifficulty: 10936284678681386,
>   transactions: [],
>   transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   uncles: []
> }
> > web3.fromWei(web3.eth.getBalance("0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",20365))
> 946.25
> ```
> 
> **Aleth**
> 
> ```
> geth attach ipc:\\.\pipe\geth.ipc
> Welcome to the Geth JavaScript console!
> 
> instance: aleth/1.7.0-alpha.1-38+commit.0faec9d1.dirty/windows/msvc19.22.27905.0/release
> coinbase: 0x0038aed9783f127776f2a6a175f7efd1b9a2e97c
> at block: 502739 (Fri, 06 Nov 2015 23:12:41 PST)
>  modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 web3:1.0
> 
> > web3.eth.getBlock(20365)
> {
>   author: "0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",
>   boundary: "0x00000000011b8e11293cde98ea348d7f3fda00d29c7c3e7b028063c71fee92b0",
>   difficulty: 992664657586,
>   extraData: "0x616c6c6120686f7070",
>   gasLimit: 5000,
>   gasUsed: 0,
>   hash: "0xbc16ec8bd9a33fafb31f7dde81b6309dad199287b1046aaeedafdb522ff74b2b",
>   logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>   miner: "0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",
>   mixHash: "0xca4ce299a6dbe7ba712fc5c9f1a7fe5399a6f9e62b836d423cf245f36170a6a9",
>   nonce: "0xe1897e4350804c7e",
>   number: 20365,
>   parentHash: "0x538ee2fc49703085ee44b8507ca5faeb8ee54e5e697a5071aeb4064e6af47460",
>   receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   seedHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
>   sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
>   size: 0,
>   stateRoot: "0x049a838203b095fd50c6c02b07f9125a73e9f78949f46d5d2908e89d7406109f",
>   timestamp: 1438494603,
>   totalDifficulty: 10936284678681386,
>   transactions: [],
>   transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   uncles: []
> }
> > web3.fromWei(web3.eth.getBalance("0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89",20365))
> 946.25
> ```

@winsvega / @gumb0 How do we know that Aleth is returning the pre-block-reward balance...have we confirmed this?

**Comment by halfalicious** [comment]
@winsvega / @gumb0 It looks like the result returned by `web3.eth.getBalance` for Aleth includes the block reward - I checked the balance of the beneficiary for [block 20365](https://etherscan.io/block/20365) in the previous block and it was 5 ether less. Additionally, I confirmed that the beneficiary of the block reward for [20364 ](https://etherscan.io/block/20364) was a different address (`0xbb12b5a9b85d4ab8cde6056e9c1b2a4a337d2261` instead of 
`0xab84940b570d6358ed6a9dbf7e0bc8ec8f5a6e89`)

So, it looks like the issue that @winsvega is seeing is purely a perf-related one that we should be able to address by retrieving the balance from the final state (rather than replaying each tx).

**Comment by halfalicious** [comment]
@winsvega / @gumb0 Block reward is applied during `Block::enact ` after all of the txs have been executed here: https://github.com/ethereum/aleth/blob/a3cdc87abb8fb30a4293ca3bef28004c5b3ce2d3/libethereum/Block.cpp#L591

**Comment by gumb0** [comment]
@winsvega would be nice if you could try how RPC methods work for you now
