### ISSUE TITLE
No Clique PoA support in eth

### ISSUE THREAD

**Issue by rustyx** [ethereum/aleth#5057]
It seems like the [Clique PoA](https://github.com/ethereum/EIPs/issues/225) algorithm isn't implemented in eth.

Does it mean eth supports only PoW mining?

How to get PoA mining to work for a private net?

**Comment by halfalicious** [comment]
@rustyx : Yes, Aleth currently only supports PoW mining (via a CPU mining algorithm which means realistically you can only mine on Ropsten or a private chain), but we are putting a plan together for Clique PoA support. Please see #5522
