### ISSUE TITLE
c++: error: unrecognized argument in option ‘-mtune=generic’ on IBM Power8

### ISSUE THREAD

**Issue by locomx** [ethereum/aleth#5181]
Hi
When i run the cmake give this error trying to compile ethash 0.3.0
mining/cpp-ethereum/build # cmake ..
-- [cable ] Cable 0.2.9 initialized
-- [cable ] Build type: RelWithDebInfo
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /root/.hunter
-- [hunter] [ Hunter-ID: aa1facc | Toolchain-ID: b1aeed5 | Config-ID: 852a159 ]
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.65.1)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.65.1)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.65.1)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.65.1)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.65.1)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.65.1)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.65.1)
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.65.1)
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   thread
--   context
--   fiber
--   log
-- [hunter] JSONCPP_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.8.0)
-- [hunter] SNAPPY_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.1.6-p0)
-- [hunter] CRYPTOPP_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 5.6.5-p0)
-- [hunter] LIBJSON-RPC-CPP_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 0.7.0-p3)
-- [hunter] LIBSCRYPT_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 1.21-p1)
-- [hunter] ETHASH_ROOT: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Install (ver.: 0.3.0)
-- [hunter] Building ethash
loading initial cache file /root/.hunter/_Base/aa1facc/b1aeed5/852a159/cache.cmake
loading initial cache file /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Build/ethash/args.cmake
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/at11.0/bin/cc
-- Check for working C compiler: /opt/at11.0/bin/cc -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/at11.0/bin/c++
-- Check for working CXX compiler: /opt/at11.0/bin/c++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Build/ethash/Build
Scanning dependencies of target ethash-Release
[ 12%] Creating directories for 'ethash-Release'
[ 25%] Performing download step (download, verify and extract) for 'ethash-Release'
-- verifying file...
     file='/root/.hunter/_Base/Download/ethash/0.3.0/42597f3/v0.3.0.tar.gz'
-- verifying file... done
-- extracting...
     src='/root/.hunter/_Base/Download/ethash/0.3.0/42597f3/v0.3.0.tar.gz'
     dst='/root/.hunter/_Base/aa1facc/b1aeed5/852a159/Build/ethash/Source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 37%] No patch step for 'ethash-Release'
[ 50%] No update step for 'ethash-Release'
[ 62%] Performing configure step for 'ethash-Release'
loading initial cache file /root/.hunter/_Base/aa1facc/b1aeed5/852a159/cache.cmake
loading initial cache file /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Build/ethash/args.cmake
-- [cable ] Cable 0.2.0 initialized
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/at11.0/bin/cc
-- Check for working C compiler: /opt/at11.0/bin/cc -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/at11.0/bin/c++
-- Check for working CXX compiler: /opt/at11.0/bin/c++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [cable ] Build type: Release
-- Performing Test fstack-protector
-- Performing Test fstack-protector - Success
-- Performing Test Wimplicit-fallthrough
-- Performing Test Wimplicit-fallthrough - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Build/ethash/Build/ethash-Release-prefix/src/ethash-Release-build
[ 75%] Performing build step for 'ethash-Release'
Scanning dependencies of target ethash
[ 16%] Building CXX object lib/ethash/CMakeFiles/ethash.dir/ethash.cpp.o
[ 33%] Building C object lib/ethash/CMakeFiles/ethash.dir/keccak.c.o
[ 66%] Building C object lib/ethash/CMakeFiles/ethash.dir/keccakf1600.c.o
[ 66%] Building CXX object lib/ethash/CMakeFiles/ethash.dir/managed.cpp.o
c++: error: unrecognized argument in option ‘-mtune=generic’
c++: note: valid arguments to ‘-mtune=’ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
c++: error: unrecognized argument in option ‘-mtune=generic’
cc: error: unrecognized argument in option ‘-mtune=generic’
cc: error: unrecognized argument in option ‘-mtune=generic’
c++: note: valid arguments to ‘-mtune=’ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
cc: note: valid arguments to ‘-mtune=’ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
cc: note: valid arguments to ‘-mtune=’ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
lib/ethash/CMakeFiles/ethash.dir/build.make:62: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/ethash.cpp.o' failed
gmake[5]: *** [lib/ethash/CMakeFiles/ethash.dir/ethash.cpp.o] Error 1
gmake[5]: *** Waiting for unfinished jobs....
lib/ethash/CMakeFiles/ethash.dir/build.make:86: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/managed.cpp.o' failed
gmake[5]: *** [lib/ethash/CMakeFiles/ethash.dir/managed.cpp.o] Error 1
lib/ethash/CMakeFiles/ethash.dir/build.make:134: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/keccakf1600.c.o' failed
gmake[5]: *** [lib/ethash/CMakeFiles/ethash.dir/keccakf1600.c.o] Error 1
lib/ethash/CMakeFiles/ethash.dir/build.make:110: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/keccak.c.o' failed
gmake[5]: *** [lib/ethash/CMakeFiles/ethash.dir/keccak.c.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/all' failed
gmake[4]: *** [lib/ethash/CMakeFiles/ethash.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
gmake[3]: *** [all] Error 2
CMakeFiles/ethash-Release.dir/build.make:114: recipe for target 'ethash-Release-prefix/src/ethash-Release-stamp/ethash-Release-build' failed
gmake[2]: *** [ethash-Release-prefix/src/ethash-Release-stamp/ethash-Release-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ethash-Release.dir/all' failed
gmake[1]: *** [CMakeFiles/ethash-Release.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /root/.hunter/_Base/aa1facc/b1aeed5/852a159/Build/ethash
[hunter ** FATAL ERROR **] [Directory:/root/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/projects/ethash]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at /root/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /root/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  /root/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_download.cmake:672 (hunter_fatal_error)
  /root/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/projects/ethash/hunter.cmake:52 (hunter_download)
  /root/.hunter/_Base/Download/Hunter/0.21.16/aa1facc/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:89 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/home/mining/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".
See also "/home/mining/cpp-ethereum/build/CMakeFiles/CMakeError.log".
=====================================================================
Here is the erro log

/mining/cpp-ethereum/build # cat /home/mining/cpp-ethereum/build/CMakeFiles/CMakeError.log
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/mining/cpp-ethereum/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_247af/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_247af.dir/build.make CMakeFiles/cmTC_247af.dir/build
gmake[1]: Entering directory '/home/mining/cpp-ethereum/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_247af.dir/CheckSymbolExists.c.o
/opt/at11.0/bin/cc    -fPIC    -o CMakeFiles/cmTC_247af.dir/CheckSymbolExists.c.o   -c /home/mining/cpp-ethereum/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_247af
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_247af.dir/link.txt --verbose=1
/opt/at11.0/bin/cc  -fPIC    -fuse-ld=gold  CMakeFiles/cmTC_247af.dir/CheckSymbolExists.c.o  -o cmTC_247af 
CMakeFiles/cmTC_247af.dir/CheckSymbolExists.c.o(.toc+0x0): error: undefined reference to 'pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_247af.dir/build.make:97: recipe for target 'cmTC_247af' failed
gmake[1]: *** [cmTC_247af] Error 1
gmake[1]: Leaving directory '/home/mining/cpp-ethereum/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_247af/fast' failed
gmake: *** [cmTC_247af/fast] Error 2

File /home/mining/cpp-ethereum/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/mining/cpp-ethereum/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_9d093/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_9d093.dir/build.make CMakeFiles/cmTC_9d093.dir/build
gmake[1]: Entering directory '/home/mining/cpp-ethereum/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9d093.dir/CheckFunctionExists.c.o
/opt/at11.0/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_9d093.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_9d093
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9d093.dir/link.txt --verbose=1
/opt/at11.0/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -fuse-ld=gold  CMakeFiles/cmTC_9d093.dir/CheckFunctionExists.c.o  -o cmTC_9d093 -lpthreads 
/opt/at11.0/lib/gcc/powerpc64le-linux-gnu/7.3.1/../../../../powerpc64le-linux-gnu/bin/ld.gold: error: cannot find -lpthreads
CMakeFiles/cmTC_9d093.dir/CheckFunctionExists.c.o:CheckFunctionExists.c:function main: error: undefined reference to 'pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_9d093.dir/build.make:97: recipe for target 'cmTC_9d093' failed
gmake[1]: *** [cmTC_9d093] Error 1
gmake[1]: Leaving directory '/home/mining/cpp-ethereum/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_9d093/fast' failed
gmake: *** [cmTC_9d093/fast] Error 2
=========================================================
If i run the cmake system info it's OK!
# cmake --system-information | grep mtune
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_72ca4' '-mtune=power8' '-mcpu=power8'
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_72ca4' '-mtune=power8' '-mcpu=power8'
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_72ca4' '-mtune=power8' '-mcpu=power8']
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_6adcf' '-shared-libgcc' '-mtune=power8' '-mcpu=power8'
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_6adcf' '-shared-libgcc' '-mtune=power8' '-mcpu=power8'
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_6adcf' '-shared-libgcc' '-mtune=power8' '-mcpu=power8']

did some whant's to help me!!

Thanks

**Comment by slimsamu** [comment]
Curious to know if there was a solution implemented or a workaround implemented for this?

**Comment by chfast** [comment]
Thanks for reporting, I will fix it.

**Comment by chfast** [comment]
This should fix it: https://github.com/chfast/ethash/pull/125. You can point Aleth to this version of ethash. I will release it and update Aleth soon.

**Comment by locomx** [comment]
Thanks!! I will try again.

**Comment by thsitthisak** [comment]
hi locomx
     how to fixed please help me.
      i download and found same error

"-- Build files have been written to: /home/sith/.hunter/_Base/c4cfcc0/1309eb4/ef3c3eb/Build/ethash/Build/ethash-Release-p
lease-build
[ 75%] Performing build step for 'ethash-Release'
Scanning dependencies of target ethash
[ 25%] Building CXX object lib/ethash/CMakeFiles/ethash.dir/ethash.cpp.o
[ 25%] Building CXX object lib/ethash/CMakeFiles/ethash.dir/managed.cpp.o
c++: error: unrecognized argument in option  € -mtune=generic €
c++: note: valid arguments to  € -mtune= €  are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604
400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power
er5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
c++: error: unrecognized argument in option  € -mtune=generic €
c++: note: valid arguments to  € -mtune= €  are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp "

thank a lot for help me ^^

**Comment by chfast** [comment]
@thsitthisak not integrated here. I will work on this.

**Comment by thsitthisak** [comment]
waiting to fix ^^

**Comment by thsitthisak** [comment]
[ 75%] Performing build step for 'ethash-Release'
Scanning dependencies of target ethash
[ 12%] Building CXX object lib/ethash/CMakeFiles/ethash.dir/ethash.cpp.o
[ 25%] Building CXX object lib/ethash/CMakeFiles/ethash.dir/managed.cpp.o
[ 37%] Building C object lib/ethash/CMakeFiles/ethash.dir/keccakf800.c.o
[ 50%] Building C object lib/ethash/CMakeFiles/ethash.dir/keccak.c.o
cc: error: unrecognized argument in option โ€-mtune=genericโ€
cc: error: unrecognized argument in option โ€-mtune=genericโ€
cc: note: valid arguments to โ€-mtune=โ€ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620
630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power
3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
cc: note: valid arguments to โ€-mtune=โ€ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620
630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power
3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
lib/ethash/CMakeFiles/ethash.dir/build.make:101: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/keccakf800.c.o' failed
make[5]: *** [lib/ethash/CMakeFiles/ethash.dir/keccakf800.c.o] Error 1
make[5]: *** Waiting for unfinished jobs....
lib/ethash/CMakeFiles/ethash.dir/build.make:88: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/keccak.c.o' failed
make[5]: *** [lib/ethash/CMakeFiles/ethash.dir/keccak.c.o] Error 1
c++: error: unrecognized argument in option โ€-mtune=genericโ€
c++: error: unrecognized argument in option โ€-mtune=genericโ€
c++: note: valid arguments to โ€-mtune=โ€ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620
 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native powe
r3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
c++: note: valid arguments to โ€-mtune=โ€ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620
 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native powe
r3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
lib/ethash/CMakeFiles/ethash.dir/build.make:62: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/ethash.cpp.o' failed
make[5]: *** [lib/ethash/CMakeFiles/ethash.dir/ethash.cpp.o] Error 1
lib/ethash/CMakeFiles/ethash.dir/build.make:75: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/managed.cpp.o' failed
make[5]: *** [lib/ethash/CMakeFiles/ethash.dir/managed.cpp.o] Error 1
CMakeFiles/Makefile2:90: recipe for target 'lib/ethash/CMakeFiles/ethash.dir/all' failed
make[4]: *** [lib/ethash/CMakeFiles/ethash.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ethash-Release.dir/build.make:114: recipe for target 'ethash-Release-prefix/src/ethash-Release-stamp/ethash-Release-bui
ld' failed
make[2]: *** [ethash-Release-prefix/src/ethash-Release-stamp/ethash-Release-build] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/ethash-Release.dir/all' failed
make[1]: *** [CMakeFiles/ethash-Release.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/sith/.hunter/_Base/c4cfcc0/6ca4f3f/ef3c3eb/Build/ethash
[hunter ** FATAL ERROR **] [Directory:/home/sith/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/projects/ethash]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at /home/sith/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /home/sith/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  /home/sith/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_download.cmake:614 (hunter_fatal_error)
  /home/sith/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/projects/ethash/hunter.cmake:52 (hunter_download)
  /home/sith/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  CMakeLists.txt:83 (hunter_add_package)

**Comment by chfast** [comment]
Should be fixed by #5560, to be included in 1.6.0 release.

**Comment by thsitthisak** [comment]
thk a lot sir

I'am new to miner 

now can complied, but don't know how to used, 
please help to sample to run ./aleth

./aleth stratum1+tcp://ETH_WALLET.WORKERNAME@eth.2miners.com:2020
./aleth stratum1+tcp://0x17071Fed33fDc18fbfDd4B3E201fDC9780e604Ae.sith@eth.2miners.com:2020

**Comment by chfast** [comment]
Wrong project. https://github.com/ethereum-mining/ethminer

**Comment by thsitthisak** [comment]
Hi Pawel

    For IBM power8 can only mine eth with cpu only ?  and do you know estimate hash rate  for 22 cores ?

Thank you for respond krub


________________________________
จาก: Paweł Bylica <notifications@github.com>
ส่ง: 12 เมษายน 2562 0:58
ถึง: ethereum/aleth
สำเนาถึง: thsitthisak; Mention
ชื่อเรื่อง: Re: [ethereum/aleth] c++: error: unrecognized argument in option ‘-mtune=generic’ on IBM Power8 (#5181)


Wrong project. https://github.com/ethereum-mining/ethminer
