### ISSUE TITLE
Mining option --mining-threads is not used

### ISSUE THREAD

**Issue by tiendq** [ethereum/aleth#5183]
`--mining-threads` option (run `aleth --help` to see its usage) is not used, result in `MinerCLI::m_miningThreads` is always assigned `UINT_MAX`.

**Comment by tiendq** [comment]
Aha, I just found mining options are handled in `MinerCLI::interpretOption`. I missed it because it uses input data named `unrecognisedOptions` :).  These options are also not handled in the way other options are handled via `boost::program_options`.

**Comment by tiendq** [comment]
@chfast I think I could make it's easier to read e.g. using `boost::program_options`, is it worth a PR?

**Comment by chfast** [comment]
I think there are two options.

1. Return an options group dedicated to mining similar to `vmProgramOptions()`.
2. Just merge mining options to `aleth/main.cpp` as they are not shared with other tools any more.

**Comment by tiendq** [comment]
I will go with option #1, I think we should not make `main()` function longer, it's already pretty long :)
