### ISSUE TITLE
Duplicated call to Ethash::init() and NoProof::init()

### ISSUE THREAD

**Issue by tiendq** [ethereum/aleth#5187]
These functions are called first in `aleth/main.cpp` `main()` and then called again in `MinerCLI::MinerCLI`. They register seal engines and I think they do no harm, just duplicate work. Which one should be removed?

**Comment by gumb0** [comment]
`MinerCLI` is mostly responsible for command line arguments handling, so I'd leave engine initialization in main.cpp

**Comment by tiendq** [comment]
I think so too, should make a tiny PR soon :)
