### ISSUE TITLE
Speeding up initialization

### ISSUE THREAD

**Issue by lrettig** [ethereum/aleth#5192]
When I fire up `aleth` it takes 5-10 minutes until the first block is mined. Subsequent blocks are mined in a few seconds. I always thought this was because it was generating the ethhash DAG but @chfast suggested this should not be an issue. What's causing this delay and can we speed it up?

Here's the command I'm running: `> aleth -K -d /tmp/ewasm-node/0002 --listen 4201 --no-bootstrap -m on -t 1 -a 0x031159dF845ADe415202e6DA299223cb640B9DB0 --log-verbosity 4 --no-discovery --test --config ewasm-testnet-cpp-config.json --vm ~/eth/hera/build/src/libhera.dylib --evmc fallback=true`

json file is here: https://github.com/ewasm/testnet/blob/master/ewasm-testnet-cpp-config.json

Here's a trace: https://gist.github.com/lrettig/f33e58466dd4ebf4f5ccd9c83ef76325

**Comment by gumb0** [comment]
Still it should have something to do with mining if not with libethash

**Comment by chfast** [comment]
It's problem in libethash, not easy to workaround directly there.

I'd look at the difficulty setting. If the difficulty is 1024 there are only ~1024 hashes to check? This should take seconds. But chains might have also minimum difficulty configured... maybe this is one of the problems.

**Comment by chfast** [comment]
Fixed in config.

**Comment by lrettig** [comment]
Was fixed here: https://github.com/ewasm/testnet/pull/73
