### ISSUE TITLE
Support enode:// addresses in --peerset command line argument handing

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#5197]
This causes confusion all the time.

Currently the only allowed way to use it is like
```
./aleth --peerset "required:68e6383c649935649723fc44bb4a94bd2019c29a828cb7ee8151abda9567417797fec213f4b60b59d84faac62577814d63cc5d7cc7d4bc09730ea4f43e9f44db@127.0.0.1:30303"
```
We should allow also
```
./aleth --peerset "required:enode://68e6383c649935649723fc44bb4a94bd2019c29a828cb7ee8151abda9567417797fec213f4b60b59d84faac62577814d63cc5d7cc7d4bc09730ea4f43e9f44db@127.0.0.1:30303"
```

See also how parsing is done in `NodeSpec` constructor and maybe reuse this `NodeSpec` class for this.

**Comment by chfast** [comment]
@gumb0 if you are going to work on this, base a PR on `release/1.4` branch.

**Comment by tiendq** [comment]
@chfast is it supporting `enode://` in the address? and what does `release/1.4` mean? branching from that branch for this PR?

**Comment by gumb0** [comment]
@tiendq  `enode://` is supported in other places, like RPC method `admin_addPeer`.

When creating a PR choose that you want to merge to `release/1.4` instead of `master`
I guess the local branch should better be based on it, too, but that's not strictly necessary

**Comment by tiendq** [comment]
@chfast I'm working on this one, will I choose `master` or `release/1.4` for PR? my branch based on `master`.

**Comment by chfast** [comment]
Can be `master`.

**Comment by halfalicious** [comment]
Fixed by 5338
