### ISSUE TITLE
Invalid transactions should not be dropped

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5212]
```
2018-08-20 19:51:48 eth exec Paying 3 finney from sender for gas (3000000 gas at 1 Gwei)
Executing...
importGlobals
InternalError: Unsupported import called: ethereum::return (2 arguments)
2018-08-20 19:51:48 eth warn Internal VM Error (-1)
/home/builder/project/libevm/EVMC.cpp(83): Throw in function virtual dev::eth::owning_bytes_ref dev::eth::EVMC::exec(dev::u256 &, dev::eth::ExtVMFace &, const dev::eth::OnOpFunc &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InternalVMError>
[dev::eth::tag_evmcStatusCode*] = -1

2018-08-20 19:51:48 eth block #f074a402… Dropping invalid transaction: /home/builder/project/libevm/EVMC.cpp(83): Throw in function virtual dev::eth::owning_bytes_ref dev::eth::EVMC::exec(dev::u256 &, dev::eth::ExtVMFace &, const dev::eth::OnOpFunc &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InternalVMError>
[dev::eth::tag_evmcStatusCode*] = -1
```

"invalid transactions" shouldn't be dropped. they should be mined and consume gas
if they have valid signatures and the account that signed them has balance

**Comment by chfast** [comment]
@gumb0 Can you help with this?

**Comment by axic** [comment]
I actually think `aleth` should `abort` on an internal error because it is an uncertain state. Unrecoverable.

**Comment by axic** [comment]
But just dropping is a bad idea, because it could consume resources (gas), yet being dropped, essentially a DoS surface.

**Comment by chfast** [comment]
I missed the fact it returns internal error.

**Comment by gumb0** [comment]
@axic just aborting is even worse attack surface I think (it would be enough to send one transaction to get all aleth nodes down)

**Comment by gumb0** [comment]
Currently we have four ways to handle the exceptions from VM:
1. revert changes and consume the rest of the gas
2. revert changes and don't consume the rest of the gas
3. `InternalVMError` - revert changes and don't include in the block
4. General `Exception` and `std::exception` - abort

It's easy to change 3 to any other type.
https://github.com/ethereum/aleth/blob/949da062e6c1534c2ecf15ac9032b4d2364dddb8/libethereum/Executive.cpp#L485-L520

**Comment by axic** [comment]
> just aborting is even worse attack surface I think (it would be enough to send one transaction to get all aleth nodes down)

It is much easier to detect during testing though.

The only reasonable way to not have it as an attack surface is to charge for as a failed transaction and include it in the block. However then it is a huge question of consensus.

**Comment by chfast** [comment]
I'm for leaving it as it is, just clean up the logs. There should be "error" level log for this case and exceptions should be hidden.

**Comment by chfast** [comment]
Because a part of your application is crashing it sounds rather as non-fatal error to me. But can be "warning" if we don't have error level.
