### ISSUE TITLE
BOOST_VERSION and CRYPTOPP_VERSION

### ISSUE THREAD

**Issue by iamyh** [ethereum/aleth#5222]
hei，guys，i have two questions which confuses me.

the first one is in libdevcore/FileSystem.cpp

```
static_assert(BOOST_VERSION >= 106400, "Wrong boost headers version");
```
is there something new in this BOOST_VERSION? because this file only use boost::filesystem::path,so why require so mush high version?

the second one is in libdevcrypto/CryptoPP.cpp 

```
CryptoPP.cpp:static_assert(CRYPTOPP_VERSION == 565, "Wrong Crypto++ version");
```
is there also something new here?

thanks guys!

**Comment by chfast** [comment]
This checks if the local builds of Crypto++ and Boost are included, not the system ones.
