### ISSUE TITLE
POP instruction ?

### ISSUE THREAD

**Issue by sunhe741** [ethereum/aleth#5248]
In  POP instruction, why used the --m_SP,  if instead of  ++m_SP  operation , is it avaliable ?
CASE(POP) {
            ON_OP();
            updateIOGas();

            --m_SP;
        }

**Comment by chfast** [comment]
I don't understand the question.

**Comment by sunhe741** [comment]
I'm so sorry , I mean  that in file cpp-ethereum/libevm/LegacyVM.cpp , The  instruction `POP`   
`
CASE(POP) {
            ON_OP();
            updateIOGas();

            --m_SP;
        }
        NEXT
`
could be instead by the follow code ?
`
CASE(POP) {
            ON_OP();
            updateIOGas();

            ++m_SP;
        }
        NEXT
`

**Comment by chfast** [comment]
No, it cannot. You want to skip the top stack item.

**Comment by xieguilu** [comment]
The stack size is 1024, we assume there  is only one item in stack, then m_SP points to &stack[1023], right? when --m_SP is called,  m_SP points to &stack[1022] now, but stack[1022] has not been pushed yet. skip the top stack item is right , but I think ++m_SP make sense.   thx.

**Comment by chfast** [comment]
The -- works for sure. Changing it to ++ will definitely not work.
