### ISSUE TITLE
Solidity unexpected identifier  in Sublime Text

### ISSUE THREAD

**Issue by dleave0109** [ethereum/aleth#5264]
I've been installed the ethereum packages like 【EthereumSoliditySnippets】& 【Ethereum 】 and I've pasted the code
 `import urllib.request,os,hashlib; h = 'df21e130d211cfc94d9b0905775a7c0f' + '1e3d39e33b79698005270310898eea76'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)` 
in **Sublime** console, but there's some error when I tried to run my Solidity code.

As the following ：

 `(function (exports, require, module, __filename, __dirname) { pragma solidity ^0.4.19;
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 ^^^^^^^^`
`SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
[Finished in 0.1s with exit code 1]
[cmd: ['C:/Program Files/nodejs/node.exe', 'C:\\Users\\abb\\Desktop\\Program\\exercise\\Contract\\originate.sol']]
[dir: C:\Users\abb\Desktop\Program\exercise\Contract]
[path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\_sts-bundle\jdk1.8.0_162\bin;C:\Program Files\dotnet\;C:\Users\abb\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;;C:\Users\abb\AppData\Local\Programs\Microsoft VS Code\bin;C:\_sts-bundle\jdk1.8.0_162\bin;node_modules;C:\Users\abb\AppData\Roaming\npm;C:\Users\abb\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git]`

As I'm a newbie, hope there's someone senior can give me some great solution. Thans a lot !

**Comment by chfast** [comment]
This is completely different project
