### ISSUE TITLE
Use Semantic Versioning syntax

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5276]
The Semantic Versioning become some kind of standard in Ethereum related projects.

Currently we have 3 types of versions:
- stable: `X.Y.Z`,
- release candidate: `X.Y.ZrcN`,
- development snapshots: `X.Y.Z.devN`.

This syntax comes from PEP 440.
The rc versions helps stabilizing stable releases.
The dev snapshots are done on requests just for convenience. 

I propose the following changes:

- Change `X.Y.ZrcN` to `X.Y.Z-rc.N` to be aligned with semver syntax.
- Change `X.Y.Z.devN` to `X.Y.Z-alpha.N` to be aligned with semver syntax. The semver sytax is very dump so we have to change `dev` to `alpha` to be before hypothetical `beta`.

**Comment by chfast** [comment]
cc @axic @gumb0 @halfalicious

**Comment by axic** [comment]
Sounds good.
