### ISSUE TITLE
Creating new chain with aleth

### ISSUE THREAD

**Issue by frods** [ethereum/aleth#5285]
Hello, I'm experimenting with creating a new chain with aleth at tag v1.4.0rc7.

I've updated the ```libethashseal/genisis/mainNetwork.cpp``` with content in this gist https://gist.github.com/frods/329089bdc3a428c1ec425403374ec96c
I also changed the port used to connect to hosts in the code to ensure that it doesn't try to sync with existing nodes.

I'm building on macos 10.13.6

I then:
- imported the key for the account ```00195f4b51509e358eadf8e5bd568a5240e8805f``` which is set to have some ether in the ```mainNetwork.cpp``` file
- launch aleth with no arguments
- connect with [ethereum-console](https://www.npmjs.com/package/ethereum-console)

I am able to query the balance and see the correct value for the above account.

When I try to transfer funds with:
```
> eth.sendTransaction({to:"003d05ebe55c928e16e328a40f83f86c7bacd338", from:"00195f4b51509e358eadf8e5bd568a5240e8805f", value:5000000, gas:22000})
```

I get the following output
```
Error: Returned error: Block gas limit reached.
    at Object.ErrorResponse (/Users/philip/Work/ethereumconsole/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/Users/philip/Work/ethereumconsole/node_modules/web3-core-requestmanager/src/index.js:140:36)
    at callback (/Users/philip/Work/ethereumconsole/node_modules/web3-providers-ipc/src/index.js:65:40)
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/Users/philip/Work/ethereumconsole/node_modules/web3-providers-ipc/src/index.js:76:51)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I have tried with different gas amounts and always get errors even though it is within the min and max range set in the ```mainNetwork.cpp```

What is missing/wrong with my setup? I guess something is wrong with the ```mainNetwork.cpp``` configuration.

**Comment by frods** [comment]
An update on this. 

Adjusting the genesis gasLimit to 0x1000000 in mainNetwork.cpp fixes the gas limit issue on transaction creation.

No matter how long I wait I'm not seeing any transactions going through. 
My setup is.
- The above changes plus reduced the difficulty in ```mainNetwork.cpp``` to 0x4000 to reduce the wait time.
- Set the enode address and ip to my server in Host.cpp
- Launched the miner on my server with ```aleth -m on -s [enodeaddress]```
- Then my local client and issued the transaction from above.

Even after the miner generated 2 more blocks
```
INFO  09-26 00:54:32 p2p  sync   186de922…|aleth/1.4.0rc7/linux/gnu5.4.0/relwithdebinfo Starting full sync
INFO  09-26 00:54:33 eth  client 2 blocks imported in 1 ms (1962.71 blocks/s) in #4
```
the balances for the accounts haven't changed.

I've been reading the docs in the repo, source, and googling and am still stuck. Any help would be greatly appreciated.

**Comment by frods** [comment]
I found the other issues related to private chains https://github.com/ethereum/aleth/issues/5251 https://github.com/ethereum/aleth/issues/4412 https://github.com/ethereum/aleth/issues/4958

Setting ```"allowFutureBlocks" : true``` in the params gets blocks flying. 

However balances of the accounts still don't change. From what I can see the transaction is accepted correctly. The miner and client are clearly communicating with one another. I guess it's still a configuration issue, but which one?

**Comment by gumb0** [comment]
The last error is probably indication that there's already your transaction in there transaction pool and it doesn't accept another one with the same nonce.

Why the first transaction is not being included into the mined blocks I'm not sure, will have to look into it.

I didn't get a couple of things in your setup:
> Set the enode address and ip to my server in Host.cpp

What exactly did you change and what did you try to achieve?

> Launched the miner on my server with aleth -m on -s [enodeaddress]

What do you try to achieve with `-s`? It's for importing private key

```
INFO  09-26 00:54:32 p2p  sync   186de922…|aleth/1.4.0rc7/linux/gnu5.4.0/relwithdebinfo Starting full sync
```

Sync shouldn't start if it's just one node. Try adding `--pin --no-discovery`

**Comment by gumb0** [comment]
@halfalicious You might want to look at this and check how `eth.sendTransaction` works in the private net

**Comment by frods** [comment]
This is probably easiest. You can find my changes on this branch: https://github.com/frods/aleth/tree/PrivateNetwork

Sorry that was a typo in the launch command it is acutally:
```
aleth -m on -a [enodeaddress]
```
To specify the mining address.

I have two nodes running. One on a remote server who's address is defined in the Host.cpp file (as you can see in the branch above), the other locally.

**Comment by frods** [comment]
I have been passing the account not the enode this whole time.

I realize I could also define the peerset through the command line, I don't mind maintaining my own fork and merging with the main reopo which is why I did it this way.

Any idea on why I can't issue transactions over the private network?

**Comment by frods** [comment]
I figure that it is an issue with the configuration (in mainNetwork.cpp) that conflicts with some assumptions the code makes about the main network.

I have spend significant time adding logs and tracing through what is happening on both the client node and the mining node. From what I have found the transaction reaches the mining node fine with a message of the form:

```
16 [ 0x3F, 0x1, 0x4000, 0x1297
F52D7B47AA825685092C044F25D800CF6B15D29A32554A940DB718D07296, 0x1297F52D7B47AA825685092C044F25D800CF6
B15D29A32554A940DB718D07296 ]
```
When I mine with my local node, transactions are processed and I can see the account balances changing as expected.

**Comment by frods** [comment]
Thanks I'll add some logging at those locations and come back with my findings.

Should I sync with master and try there instead of v1.4.0rc7 where I am now.

**Comment by frods** [comment]
I had to update the enode address of the remote node to be what the current address is then the transactions were being processed. This was also with the logging, so I'll remove the logging and try again to ensure it is not some artifact of the log output slowing things down.

Is there a way to define the enode address of the node so that the one in the configuration doesn't get out of sync?

**Comment by frods** [comment]
An update for anyone who comes across this issue. After updating the enodeaddress of the remote node the private network is working. The ednodeaddress had changed while iterating through the tests above.

**Comment by gumb0** [comment]
enode address is regenerated only when `~/.ethereum/network.rlp` is deleted, otherwise stays the same
