### ISSUE TITLE
Constantinople: Wrong cost for blockhash

### ISSUE THREAD

**Issue by holiman** [ethereum/aleth#5313]
See 
https://github.com/ethereum/aleth/blob/246d5a515c19a3f8970554b4470260084ecab671/libethcore/EVMSchedule.h#L137

`BLOCKHASH` is defined as `800` gas in Constantinople, not `20`. This is likely a leftover from the old [EIP 210](https://eips.ethereum.org/EIPS/eip-210) which is _not_ included in Constantinople.

**Comment by holiman** [comment]
In this commit: https://github.com/ethereum/aleth/commit/20ef95b57054741f4ae1e11404a24e72bcbdbb94, you got most of them @gumb0 , but you missed that particular one.

**Comment by gumb0** [comment]
Thanks, nice job finding it!
