### ISSUE TITLE
Update Blockchain tests to use MemoryDB for block and state storage

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5318]
Update the Blockchain tests to have the option of being run with the new MemoryDB or LevelDB. Update the unit tests to only run using MemoryDB. The rationale behind having the Blockchain tests run using either MemoryDB or LevelDB is that they are considered to be integration tests and exercise user scenarios, whereas the unit tests are targeted at very specific functionality.

**Comment by halfalicious** [comment]
I've done a quick search through the test code and here's where `TransientDirectory `is used to store block / state data:

* **TestBlock::initBlockFromJsonHeader:** https://github.com/ethereum/aleth/blob/8daa6e1c56e874e88e894d96f89f1ff8c9412a63/test/tools/libtesteth/BlockChainHelper.cpp#L103-L107
* **TestBlock::copyStateFrom**: https://github.com/ethereum/aleth/blob/8daa6e1c56e874e88e894d96f89f1ff8c9412a63/test/tools/libtesteth/BlockChainHelper.cpp#L454-L459
* **TestBlockChain::reset**:
https://github.com/ethereum/aleth/blob/8daa6e1c56e874e88e894d96f89f1ff8c9412a63/test/tools/libtesteth/BlockChainHelper.cpp#L502-L510
* **BlockChainFrontierSuite::opendb**: https://github.com/ethereum/aleth/blob/5fbdf1ef8a0aba8e0aa19e453cfb889951bc9302/test/unittests/libethereum/BlockChain.cpp#L53-L61
* **GasPricer::trivialGasPricer**:  https://github.com/ethereum/aleth/blob/5fbdf1ef8a0aba8e0aa19e453cfb889951bc9302/test/unittests/libethereum/GasPricer.cpp#L56-L65

**Comment by gumb0** [comment]
Also all tests in jsonrpc.cpp use real database now, we should make them use MemoryDB
https://github.com/ethereum/aleth/blob/561485d36d2690f5c74b4cfd743ab572e6ab80b5/test/unittests/libweb3jsonrpc/jsonrpc.cpp#L132-L137

**Comment by halfalicious** [comment]
I've started working on this...I'm trying to build a stock Aleth without any changes so I can figure out how to run the consensus tests and verify that I know which test code they invoke but I'm hitting the following build errors: 

```
Build FAILED.

"C:\Users\nilse\Documents\Code\aleth\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\nilse\Documents\Code\aleth\build\aleth\aleth.vcxproj" (default target) (3) ->
"C:\Users\nilse\Documents\Code\aleth\build\libaleth-interpreter\aleth-interpreter.vcxproj" (default target) (6) ->
(ClCompile target) ->
  C:\Users\nilse\Documents\Code\aleth\libaleth-interpreter\VM.cpp(370): error C2197: 'const evmc_get_balance_fn': too many arguments for call [C:\Users\nilse\Documents\Code\aleth\build\libaleth-interpreter\aleth-interpreter.vcxproj]
  C:\Users\nilse\Documents\Code\aleth\libaleth-interpreter\VMCalls.cpp(132): error C2197: 'const evmc_get_balance_fn': too many arguments for call [C:\Users\nilse\Documents\Code\aleth\build\libaleth-interpreter\aleth-interpreter.vcxproj
]
  C:\Users\nilse\Documents\Code\aleth\libaleth-interpreter\VM.cpp(904): error C2197: 'const evmc_get_balance_fn': too many arguments for call [C:\Users\nilse\Documents\Code\aleth\build\libaleth-interpreter\aleth-interpreter.vcxproj]
  C:\Users\nilse\Documents\Code\aleth\libaleth-interpreter\VMCalls.cpp(278): error C2197: 'const evmc_get_balance_fn': too many arguments for call [C:\Users\nilse\Documents\Code\aleth\build\libaleth-interpreter\aleth-interpreter.vcxproj
]
  C:\Users\nilse\Documents\Code\aleth\libaleth-interpreter\VM.cpp(1033): error C2197: 'const evmc_get_code_hash_fn': too many arguments for call [C:\Users\nilse\Documents\Code\aleth\build\libaleth-interpreter\aleth-interpreter.vcxproj]
  C:\Users\nilse\Documents\Code\aleth\libaleth-interpreter\VM.cpp(1345): error C2197: 'const evmc_get_storage_fn': too many arguments for call [C:\Users\nilse\Documents\Code\aleth\build\libaleth-interpreter\aleth-interpreter.vcxproj]

    0 Warning(s)
    6 Error(s)

Time Elapsed 00:00:06.88
```

My local enlistment is up-to-date, here's the latest commit:

```
commit 561485d36d2690f5c74b4cfd743ab572e6ab80b5 (HEAD -> master, origin/master, origin/HEAD, update-tests-memorydb)
Merge: 196c93bb2 d954f24d8
Author: Pawe<C5><82> Bylica <chfast@gmail.com>
Date:   Tue Oct 16 15:56:31 2018 +0200

    Merge pull request #5322 from ethereum/boundary

    ethash: Optimize difficulty to boundary implementation

```
Any ideas? I'm building the Debug configuration. 

Some notes/questions about the tests since I'm blocked from running the consensus tests: 

- Just to verify, all tests under `test/unittests` are unit tests and we can therefore have them only use `MemoryDB`, correct? 
- If this is correct, I think we should keep using `LevelDB `(or `RocksDB `when we move to it) in the following test: https://github.com/ethereum/aleth/blob/561485d36d2690f5c74b4cfd743ab572e6ab80b5/test/unittests/libethereum/BlockChain.cpp#L53-L61

This is because it tests an end-user scenario (attempting to open 2 instances of the blockchain database).
- Presumably the blockchain/state tests (i.e. the ones whose database we want to be configurable at runtime) are those which use `TestBlockChain `and `TestBlock`?

**Comment by gumb0** [comment]
Try `git submodule update`

**Comment by gumb0** [comment]
> Just to verify, all tests under test/unittests are unit tests and we can therefore have them only use MemoryDB, correct?

Yes.

> If this is correct, I think we should keep using LevelDB (or RocksDB when we move to it) in the following test:

Ok, let's leave it.

> Presumably the blockchain/state tests (i.e. the ones whose database we want to be configurable at runtime) are those which use TestBlockChain and TestBlock?

They are the tests that are run from `test\tools\jsontests`.

See also testeth's command line handling in `test\tools\libtesteth\Options.cpp`, especially `--vm` handling might be similar to what we need

**Comment by halfalicious** [comment]
> Try `git submodule update`

Thanks! I thought I had already done that but it looks like I hadn't.

**Comment by chfast** [comment]
> > Try `git submodule update`
> 
> Thanks! I thought I had already done that but it looks like I hadn't.

You need to do it every time you check out different commit.

**Comment by halfalicious** [comment]
Sounds like I need to do some reading on git submodule. Thanks guys!
