### ISSUE TITLE
Replace scripts/jsonrpcproxy.py with dopple

### ISSUE THREAD

**Issue by axic** [ethereum/aleth#5324]
Dopple is ["maintained"](https://github.com/ethereum/dopple/issues/1) at: https://github.com/ethereum/dopple

It would make sense to import it as a git submodule or subtree and be used that way.

**Comment by axic** [comment]
Since it is only used during docker image generation it may be better doing wget within docker to fetch it. Tagged the last version as `v0.3.0`.

**Comment by chfast** [comment]
This is also used by @gumb0 for ethstats.
