### ISSUE TITLE
Log execution trace of aleth-vm

### ISSUE THREAD

**Issue by ireneGP** [ethereum/aleth#5334]
Hello,

I am opening an issue about the execution trace log of `aleth-vm`.  I have talked with Paweł Bylica via the public channel of `aleth` on the gitter.

I am aware that `evm` and `parity-vm` has a debug mode which prints out the stack usage at each step. I cannot find such an option in `aleth-vm` (newest version, aleth-vm 1.5.0-alpha.3-4+commit.816e52de).

I tried the following commands but it does not work.

    ./aleth-vm --code 60026000556001600055 --log-verbosity 4
    ./aleth-vm trace --code 60026000556001600055 --log-verbosity 4

Here are some outputs on my computer, by running the `aleth-vm` with some sample inputs:

    aleth-vm git:(master) ./aleth-vm --code 60026000556001600055 --log-verbosity 20
     Gas used: 25012 (+21000 for transaction, -0 refunded)
    Output:
    0 logs.
    7 operations in 1.5e-05 seconds. 
    Maximum memory usage: 0 bytes
    Expensive operations:
      SSTORE x 2 (0 gas)
    DEBUG 10-30 14:55:56 aleth-vm overlaydb Closing state DB

**Comment by gumb0** [comment]
I believe you need to compile it with `VMTRACE` flag to enable it (`cmake .. -DVMTRACE=ON`)

**Comment by ireneGP** [comment]
@werew  Thanks. One followup question, why it cannot print out the corresponding opcode each step?

**Comment by werew** [comment]
@ireneGP adding `st.setShowMnemonics();` in the main function will do the job:
```
$ ./aleth-vm trace --code 60026000556001600055                                                                                     
[                                                                                                                                                     
   {                                                                                                                                                  
      "depth" : "0",                                                                                                                                  
      "gas" : "9223372036854775807",
      "gasCost" : "3",
      "memory" : [],
      "op" : "PUSH1",
      "pc" : "0",
      "stack" : [],
      "storage" : {}
   },
   {
      "depth" : "0",
      "gas" : "9223372036854775804",
      "gasCost" : "3",
      "op" : "PUSH1",
      "pc" : "2",
      "stack" : [ "0x02" ]
   },
   ...
]
```

**Comment by ireneGP** [comment]
@werew Perfect, thanks a lot!

**Comment by gumb0** [comment]
I believe this is resolved, thanks @werew
