### ISSUE TITLE
RocksDB performs significantly worse than LevelDB in tests

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5340]
RocksDB support is being added in this PR: #4844 

When running the Aleth tests, RocksDB currently performs significantly worse than LevelDB. For example, a full test run using RocksDB (and TestEth compiled with the RelWithDebInfo configuration) takes approximately 70% longer than when using LevelDB (timing performed via TestEth's `--exectimelog` argument). From the PR:

> 	@gumb0 / @chfast : I've successfully sync'd a few thousand Ropsten blocks on both Windows and Linux so I think these changes are ready for review. One note - the tests took approximately 70% longer to run when using RocksDB so it looks like RocksDB has worse performance, at least for the read/write patterns used in the tests. I didn't quiet my machine before running the tests so these aren't scientific performance comparisons but I didn't have anything intensive running in the background and I didn't use my machine while the tests were being executed so I think the results are somewhat accurate. Regarding hard numbers, I ran 2 iterations of the tests using LevelDB (results: 982 and 1019) and 2 iterations using RocksDB (results: 1738 and 1769).

I took a quick look at the RocksDB interface that Aleth uses to interact with RocksDB and noticed a couple of small differences compared to the LevelDB interface:
	• **RocksDBWriteBatch::insert**: The status is checked after `m_writeBatch.put()`. No status check is performed in **LevelDBWriteBatch::insert**
	• **RocksDBWriteBatch::kill**: The status is checked after `m_writeBatch.delete()`. No status check is performed in **LevelDBWriteBatch::kill**
	• **RocksDB::exists**: The status is checked via `IsNotFound()` before the call to `checkStatus()`. This check is not performed in **LevelDB::exists**.

However, these differences aren't causing any noticeable performance issues since I removed the code from RocksDB and re-ran the tests but the perf delta remained. 

Note that for some tests, the perf delta can be 100+%. For example:
* BlockchainTests/bcStateTests:
**- LevelDB:** 21.4428
**- RocksDB:** 44.3357
**- Delta:** 106%
* BlockchainTests/bcBlockGasLimitTest:
**- LevelDB:** 8.98981
**- RocksDB:** 18.1722
**- Delta:** 102%

Output from test runs:
* [leveldb_run_00.txt](https://github.com/ethereum/aleth/files/2546943/leveldb_run_00.txt)
* [leveldb_run_01.txt](https://github.com/ethereum/aleth/files/2546945/leveldb_run_01.txt)
* [rocksdb_run_00.txt](https://github.com/ethereum/aleth/files/2546946/rocksdb_run_00.txt)
* [rocksdb_run_01.txt](https://github.com/ethereum/aleth/files/2546944/rocksdb_run_01.txt)

I've done some brief searching online and haven't found anything indicating that RocksDB performance is expected to be significantly worse than LevelDB performance. As such, these significant performance differences are not expected and should be investigated.

**Comment by chfast** [comment]
Hey.
First thing to try would be to build with LITE option. https://github.com/facebook/rocksdb/blob/master/ROCKSDB_LITE.md
I don't think we need any fancy server features.

The `ROCKSDB_LITE` should be applied in Hunter config like here: https://github.com/ethereum/aleth/blob/master/cmake/Hunter/config.cmake#L4

Secondly, parity has found good config options for rocksdb. You can either find them in parity's code or ask them on some chat channel. Options: https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning.

**Comment by chfast** [comment]
I've found this PR: https://github.com/paritytech/parity-ethereum/pull/7348.

**Comment by halfalicious** [comment]
> 
> 
> Hey.
> First thing to try would be to build with LITE option. https://github.com/facebook/rocksdb/blob/master/ROCKSDB_LITE.md
> I don't think we need any fancy server features.
> 
> The `ROCKSDB_LITE` should be applied in Hunter config like here: https://github.com/ethereum/aleth/blob/master/cmake/Hunter/config.cmake#L4
> 
> Secondly, parity has found good config options for rocksdb. You can either find them in parity's code or ask them on some chat channel. Options: https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning.

We chatted about this offline but just to call this out here for posterity - `ROCKSDB_LITE` doesn't work, I hit the following error when running the blockchain state tests: 

```
C:\Users\nilse\Documents\Code\aleth_ref\build\test\RelWithDebInfo>testeth -t BlockchainTests/bcStateTests -- --exectimelog --db rocksdb
Running tests using path: "C:\Users\nilse\Documents\Code\aleth\test\jsontests"
Running 1 test case...
Test Case "bcStateTests":
unknown location(0): fatal error: in "BlockchainTests/bcStateTests": class std::length_error: vector<T> too long
```

I also tried setting simple database config options based on what Parity has in the PR you shared, here's the relevant code file (from the PR since the file appears to have been removed from the repo): https://github.com/paritytech/parity-ethereum/blob/27564e6672285642f02e7a287f91b8de096d50dd/util/kvdb-rocksdb/src/lib.rs

Here are the database options I set:
* options.use_fsync = false;
* options.keep_log_file_num = 1;
* options.bytes_per_sync = 1048576;
* options.db_write_buffer_size = 128 * 1024 * 1024 / 2;
* options.IncreaseParallelism(std::max(1, (int)std::thread::hardware_concurrency() / 2));
* options.create_if_missing = true;
* options.max_open_files = 512;

Setting these options had no impact on performance when running the bcStateTests test. I also tried setting the `verify_checksums=false` read option and `disable_wal=true` write option but those actually decreased performance (they increased the average runtime of the bcStateTests test approximately 10%). 

Next I'm going to try playing with the more complicated options e.g. BlockBasedTableOptions, compaction profiles, and column options.

**Comment by gumb0** [comment]
On Parity's DB tuning there's also this doc https://gist.github.com/andresilva/a71c251995ef97806715441074a10f57#file-rocksdb-tuning-org

**Comment by halfalicious** [comment]
> 
> 
> On Parity's DB tuning there's also this doc https://gist.github.com/andresilva/a71c251995ef97806715441074a10f57#file-rocksdb-tuning-org

Thanks @gumb0 ! I set those options but the test `BlockchainTests/bcStateTests` hits the following error when run with RocksDB:

```
C:\Users\nilse\Documents\Code\aleth\build\test\RelWithDebInfo>testeth -t BlockchainTests/bcStateTests -- --exectimelog --db rocksdb
Running tests using path: "C:\Users\nilse\Documents\Code\aleth\test\jsontests"
Running 1 test case...
Test Case "bcStateTests":
C:\Users\nilse\Documents\Code\aleth\libethereum\State.cpp(99): fatal error: in "class dev::OverlayDB __cdecl dev::eth::State::openDB(const class boost::filesystem::path &,const class dev::FixedHash<32> &,enum dev::WithExisting)": class boost::exception_detail::clone_impl<struct dev::eth::DatabaseAlreadyOpen>: C:\Users\nilse\Documents\Code\aleth\libethereum\State.cpp(99): Throw in function class dev::OverlayDB __cdecl dev::eth::State::openDB(const class boost::filesystem::path &,const class dev::FixedHash<32> &,enum dev::WithExisting)
Dynamic exception type: class boost::exception_detail::clone_impl<struct dev::eth::DatabaseAlreadyOpen>

C:\Users\nilse\Documents\Code\aleth\test\tools\jsontests\BlockChainTests.cpp(152): last checkpoint

*** 1 failure is detected (5 failures are expected) in the test module "Master Test Suite"
Total Time:                                       : 0
```

I'll do some debugging to see if I can figure out what the issue is.

**Comment by gumb0** [comment]
Maybe you can see the message from line 85 if you increase verbosity of testeth run

**Comment by halfalicious** [comment]
> 
> 
> Maybe you can see the message from line 85 if you increase verbosity of testeth run

Thanks, setting --verbosity to 3 did the trick...turned out I hadn't set the `create_if_missing` option. 

Unfortunately RocksDB is still performing more than 2x slower (for BlockchainTests/bcStateTests) than LevelDB...I'm going to take a closer look at the meaning of each of the tuning options to see if I can come up with better values for them.

**Comment by halfalicious** [comment]
> 
> 
> > Maybe you can see the message from line 85 if you increase verbosity of testeth run
> 
> Thanks, setting --verbosity to 3 did the trick and I figured it out.
> 
> Unfortunately RocksDB is still performing more than 2x slower (for BlockchainTests/bcStateTests) than LevelDB...I'm going to take a closer look at the meaning of each of the tuning options to see if I can come up with better values for them.

Since digging into the tuning options is going to take a bit of time, I first tried to set the exact same defaults as LevelDB...this involved setting:
*  `write_buffer_size` to 4MB (which is significantly less than RocksDB's default of 64MB)
* `paranoid_checks`: false
* `max_open_files`: 256 (RocksDB keeps all files open by default)
* (read option) `verify_checksums`: false

The results were pretty much the same as our current settings (which is just `max_open_files: 256`)...here are the timing results (average of 3 runs of `BlockchainTests/bcStateTests` using a testeth Release build:
* **MemoryDB**: 1.73124s
* **LevelDB**: 18.8866s
* **RocksDB** (LevelDB defaults): 39.514s
* **RocksDB** (current defaults): 39.956s

Next I'm going to throw together some microbenchmarks (e.g. insert 1000 blocks into the database directly and read back the same 1000 blocks) to determine what sorts of perf deltas we're seeing for reads vs writes, since this will help guide my optimizations.

**Comment by halfalicious** [comment]
I created a simple test which inserts 1000 blocks (each containing 1 tx) and reads back the blocks. I timed the insertions and reads separately (using std::chrono) and I’m seeing RocksDB take approx 50 percent longer for the reads and approx 2.5x longer for the writes.

**Comment by gumb0** [comment]
@halfalicious Could you share this test? I would try it on my machines

**Comment by chfast** [comment]
I cannot help with this, but if you want to switch to rocksdb on Windows to be able to upgrade to VS 2017, I'm ok with this.

**Comment by gumb0** [comment]
I'm getting the similar results on both Windows and Linux machine, or even worse, insertion is several times slower for RocksDB. While LevelDB performs very comparable to MemoryDB.

**Comment by chfast** [comment]
1. We can start asking questions on GitHub, like https://github.com/facebook/rocksdb/issues/608.
2. Compare with https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks#test-3-random-write.
3. All is done in single thread, right?
4. I also found this paper: https://brage.bibsys.no/xmlui/bitstream/handle/11250/2506148/19718_FULLTEXT.pdf?sequence=1

**Comment by halfalicious** [comment]
Closing since we've removed RocksDB support
