### ISSUE TITLE
Boot node host data should be moved from code into separate configuration file

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5341]
There's boot node data hard-coded in the Aleth source code - in `Host::pocHosts`:

https://github.com/ethereum/aleth/blob/9c4db26c10c0b6fe0f7d622a3ba3bf6cf0d58427/libp2p/Host.cpp#L487-L502

This data should be moved out of the source code and into a separate configuration file (even a simple comma-delimited text file would do) so that host changes don't cause code churn. 

`main()` calls into `Host::pocHosts` to retrieve each node and attempts to connect to it here: https://github.com/ethereum/aleth/blob/19ad7d95d7689d2378730faa3eb4330a74cf1d1c/aleth/main.cpp#L1115-L1117

**Comment by gumb0** [comment]
I'm not sure about this, I think both geth and parity have bootnodes hard-coded. We'd need to provide the additional config file to connect to mainnet or ropsten, sounds like more things that could go wrong potentially...
@chfast thoughts?


Though I'm in favor of finding a better place for these constants, outside of libp2p, perhaps closer to chain configs.

**Comment by chfast** [comment]
We can think about better place for having those, e.g. having a place in config YML files for those.
But some default config must be embedded, because this makes distribution much easier (i.e. you anly need the aleth binary to take with you).

**Comment by halfalicious** [comment]
> I'm not sure about this, I think both geth and parity have bootnodes hard-coded. We'd need to provide the additional config file to connect to mainnet or ropsten, sounds like more things that could go wrong potentially

You're right, Geth has the info in `bootnodes.go`: https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go

I agree that leaving this in the code and moving it to a better location would be a good idea (maybe we add something to `libethereum `e.g. a new static class called `BootNodes`)?

**Comment by gumb0** [comment]
It is not needed by anything but `aleth` executable, so maybe putting it to `aleth` dir would be fine.

Another option is to put it closer to chain configs in `libethashseal/genesis`. But it's weird enough that we have these chain configs in the library about Ethash consensus engine.

**Comment by gumb0** [comment]
fixed now?

**Comment by halfalicious** [comment]
Fixed by #5485
