### ISSUE TITLE
Upstream boost mutiprecision unit tests

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5349]
There are some boost multiprecision unit tests located in https://github.com/ethereum/aleth/blob/master/test/unittests/external-dependencies/boost.cpp.

Send them to the upstream project (https://github.com/boostorg/multiprecision) and remove from here.

This cases might have been covered by the upstream project already as we reported some bug related to the test cases. Confirming the tests exist upstream is also accepted solution.

**Comment by MetalBaba98** [comment]
So the  given code has to be copied into the specified directory?

**Comment by lhendre** [comment]
I have some working code for one of the tests, but I am only seeing one test that is specifically referencing the Boost project?  Which ones are hte specific ones you are looking for(i have it for issue 31) . I am going to open an issue on their end to see the status

**Comment by lhendre** [comment]
https://github.com/boostorg/multiprecision/pull/124 .

 'I've pulled all those tests into #124
The PR won't be merged now till after the next release.'  The tests have been confirmed upstream

**Comment by chfast** [comment]
Great! This is big help.
We don't need to wait for Boost release, but we should wait for the PR being merged or at least get feedback that it is going to be merged in near future.

**Comment by lhendre** [comment]
I asked the, their response was 'It'll be merged as soon as the current release is out.'  If that isnt enough ill add in reminders to check back periodically and update this issue when it is taken care of?

**Comment by chfast** [comment]
This is enough. You can remove these tests from this repo.

**Comment by lhendre** [comment]
Sounds good, Ill remove them today

**Comment by lhendre** [comment]
I went line by line and nearly the entire test has been duplicated so I removed the file,  the line 
constexpr auto int64_min = std::numeric_limits<int64_t>::min();
static_assert(int64_min >> 1 == int64_min / 2, "I cannot shift!"); 

was not, if you would like me to add it back in or add it somewhere else let me know. Im making a PR shortly

**Comment by lhendre** [comment]
#5518

**Comment by chfast** [comment]
Thank you.

**Comment by lhendre** [comment]
No Problem!
