### ISSUE TITLE
Aleth's "peer" mode option isn't actually supported

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5358]
According to Aleth's command-line help message, one can supply "peer" and "full" values for the "mode" argument:
`
  -o [ --mode ] <full/peer>               Start a full node or a peer node (default: full)`

However, I've looked at the processing of this argument in main.cpp and it appears that nothing actually happens when the "peer" option is supplied. I've confirmed that running Aleth with the "peer" option results in Aleth immediately quitting:

```
C:\Users\nilse\Documents\Code\aleth\build\aleth\Debug>aleth --mode peer
aleth, a C++ Ethereum client
INFO  11-18 20:35:31 main net    Id: ##132397b7ΓÇª
aleth 1.5.0-alpha.6-7+commit.3f95c5f6.dirty
INFO  11-18 20:35:33 p2p  info   UPnP device not found.
Node ID: enode://132397b7af351f81826080e0ff9ba2187d5c1f1b5fb010b656722f15e26c922787cfcc8a8005a28f1400aff6699cfccb1cde560f7290e9a2aae05bd4d4cab231@0.0.0.0:0

C:\Users\nilse\Documents\Code\aleth\build\aleth\Debug>
```

**Comment by gumb0** [comment]
Looks like uncaught exception doesn't output any error on Windows, but on Linux it does https://github.com/ethereum/aleth/issues/4703

This is the bootnode that is broken and I think should be fixed

**Comment by halfalicious** [comment]
Let's use your old issue to track this, I'll close this one.
