### ISSUE TITLE
Can i run aleth client on embedded board?

### ISSUE THREAD

**Issue by saumilsdk** [ethereum/aleth#5365]
I have an embedded linux arm based board having 256MB RAM and 1GHz CPU power. Can it run this aleth client? What is the requirements of aleth? Can smart contract run on the embedded board with aleth?

**Comment by chfast** [comment]
No. It needs much more memory and anything.

**Comment by saumilsdk** [comment]
@chfast Is that confirmed? Can you please provide some requirement document of resources to run aleth client? can you please answer my remaining questions?

**Comment by moneroexamples** [comment]
@saumilsdk 

Embeded boards like this usually lack AES instructions set (https://en.wikipedia.org/wiki/AES_instruction_set) to make processing cryptography at the hardware level. Add to this that full ethereum node is about 1TB. Board like this will struggle to process so much data. 

If you want to run aleth node on a board better get latest ones such as RPI 3B+ or Rock64 which support AES, are multicore and have 2-4 GB ram.
