### ISSUE TITLE
Aleth doesn't log abridged node ids correctly in Windows 10 console

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5366]
Here's how Aleth logs abridged (shortened) node ids in the Windows 10 console (version 10.0.17134.407) (note the strange terminating characters):

C:\Users\nilse\Documents\Code\aleth\build\aleth\Debug>aleth --ropsten
	aleth, a C++ Ethereum client
	INFO  11-25 17:35:30 main net    Id: **##1e1a6445GÇª**
	aleth 1.5.0-alpha.6-59+commit.064b04d2
	INFO  11-25 17:35:32 p2p  info   UPnP device not found.
	Node ID: enode://1e1a6445c16516dc3956b15163111c2f82ee1f3696dbbbd9bf51902cc4a2788c1a3458ecc1452433fbca64238177b68f1bcd5f523e71d40ac082963513979680@0.0.0.0:0
	INFO  11-25 17:35:32 main rpc    JSON-RPC socket path: \\.\pipe\\geth.ipc
	JSONRPC Admin Session Key: NNxiC1EH+XM=
	INFO  11-25 17:35:33 p2p  sync   **94c15d1bGÇª**|Parity/v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0 Starting full sync
	INFO  11-25 17:35:35 eth  client 2 blocks imported in 122 ms (16.2982 blocks/s) in #10518
	INFO  11-25 17:35:36 eth  client 50 blocks imported in 156 ms (319.275 blocks/s) in #10568
	INFO  11-25 17:35:36 eth  client 56 blocks imported in 175 ms (319.194 blocks/s) in #10624
	INFO  11-25 17:35:36 eth  client 62 blocks imported in 124 ms (496.163 blocks/s) in #10686
	INFO  11-25 17:35:36 eth  client 69 blocks imported in 113 ms (609.449 blocks/s) in #10755
	INFO  11-25 17:35:36 eth  client 76 blocks imported in 154 ms (491.655 blocks/s) in #10831

Building the abridged node ID string is performed in this function: https://github.com/ethereum/aleth/blob/064b04d27a6637252ece880ef81c7381e46efc79/libdevcore/FixedHash.h#L122-L123
	
The 3 escaped characters aren't rendered correctly in the default Windows 10 console

**Comment by halfalicious** [comment]
Note that the URLs are logged correctly on (Ubuntu) Linux:

```
nilsf@NILSF-TEST-VM01:~/aleth/build/aleth$ ./aleth --ropsten
aleth, a C++ Ethereum client
INFO  11-25 19:03:55 aleth net    Id: ##33ef0f7a…
aleth 1.5.0-alpha.6-59+commit.064b04d2
INFO  11-25 19:03:56 p2p  info   UPnP device not found.
Node ID: enode://33ef0f7a0e1e250f51d9dd9593cb2e7551f2e673e6f8db0e2488c6c722af514db1211dad326916d10616c56dabec6a925af62be6a7eec3276d39b47420c92c7b@0.0.0.0:0
INFO  11-25 19:03:56 aleth rpc    JSON-RPC socket path: /home/nilsf/.ethereum/geth.ipc
JSONRPC Admin Session Key: Y+HDFo+QmiM=
INFO  11-25 19:03:57 p2p  sync   6332792c…|Parity-Ethereum/v2.2.1-beta-5c56fc5-20181114/x86_64-linux-gnu/rustc1.30.1 Starting full sync

```

**Comment by gumb0** [comment]
The duplicate https://github.com/ethereum/aleth/issues/5236
