### ISSUE TITLE
aleth --test mode is failing with DBError

### ISSUE THREAD

**Issue by winsvega** [ethereum/aleth#5368]
Looks like if db-path is not set manually it fails with error: 
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::db::DatabaseError>'
  what():  /home/wins/Ethereum/cpp-ethereum/libdevcore/LevelDB.cpp(57): Throw in function void dev::db::{anonymous}::checkStatus(const leveldb::Status&, const boost::filesystem::path&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::db::DatabaseError>
[dev::db::tag_dbStatusCode*] = [ type: dev::db::DatabaseStatus, size: 4, dump: 02 00 00 00 ]
[dev::db::tag_dbStatusString*] = Corruption: corrupted compressed block contents
```

**Comment by halfalicious** [comment]
Are you running on Linux and have you sync'd recently? I ask because we upgraded LevelDB a couple of months ago and this new version is probably incompatible with the old version. If you're trying to resume syncing to an existing database using the upgraded Aleth then that could explain the behavior you're seeing. Here's the PR: #5293 

I'm able to start a fresh sync on Windows 10 using Aleth built from source with HEAD pointing to the following commit:

```
commit 030ad9ca2e5b41043554096af7a10216a9fb2fe9 (HEAD -> master, origin/master, origin/HEAD)
Merge: 064b04d27 c2e339bb9
Author: Pawe<C5><82> Bylica <chfast@gmail.com>
Date:   Mon Nov 26 15:11:24 2018 +0100

    Merge pull request #5361 from ethereum/unittests

    Unittests conversions
```

Console output:

```
Z:\temp\aleth_ref\build\aleth\Debug>aleth --test --bootstrap
aleth, a C++ Ethereum client
INFO  11-26 19:56:33 main net    Id: ##73da14c9ΓÇª
aleth 1.5.0-alpha.6-60+commit.030ad9ca
INFO  11-26 19:56:35 p2p  info   UPnP device not found.
Node ID: enode://73da14c99fcfd373a226bb00109f21162da571ea71fa16255476f23359cb22fbbc356e1b88545185848c0022aca6d10087466c64a497965ba7ef500e3d537c3e@0.0.0.0:0
INFO  11-26 19:56:35 main rpc    JSON-RPC socket path: \\.\pipe\\geth.ipc
JSONRPC Admin Session Key: l9iWy5RAeEI=
INFO  11-26 19:56:45 p2p  sync   a979fb57ΓÇª|Geth/v1.8.11-stable/linux-amd64/go1.10 Starting full sync
INFO  11-26 19:56:47 eth  client 20 blocks imported in 94 ms (210.893 blocks/s) in #20
INFO  11-26 19:56:47 eth  client 50 blocks imported in 119 ms (419.967 blocks/s) in #70
INFO  11-26 19:56:47 eth  client 56 blocks imported in 224 ms (249.342 blocks/s) in #126
INFO  11-26 19:56:47 eth  client 62 blocks imported in 142 ms (433.858 blocks/s) in #188
INFO  11-26 19:56:47 eth  client 69 blocks imported in 143 ms (480.358 blocks/s) in #257
INFO  11-26 19:56:48 eth  client 76 blocks imported in 265 ms (286.063 blocks/s) in #333
INFO  11-26 19:56:48 eth  client 84 blocks imported in 311 ms (269.916 blocks/s) in #417
INFO  11-26 19:56:48 eth  client 93 blocks imported in 234 ms (397.343 blocks/s) in #510
```

**Comment by winsvega** [comment]
yes. I guess if --db-path not provided the one that is set by default is definetly not upgraded.

**Comment by gumb0** [comment]
@winsvega does `aleth --test -K` helps?

**Comment by gumb0** [comment]
@winsvega side-note: you should use `--db memorydb` for your test purposes

**Comment by winsvega** [comment]
Thanks. I will try it with memorydb

**Comment by halfalicious** [comment]
Are you still seeing issues @winsvega ?

**Comment by winsvega** [comment]
I guess I have a very old version of DB at my local path. if it works for everybody without this option then it is fine. error handling might be better though.

**Comment by ekpyron** [comment]
I got the same error with the 1.5.0-alpha.7 release binaries on current Archlinux (using ``aleth --test`` without ``--db memorydb``). ``aleth --test --db memorydb`` worked, though.

After removing my old local database (I removed ``~/.ethereum`` entirely), however, ``aleth --test`` works again even without ``--db memorydb``.
So an old local database sometimes seem to break things.

**Comment by halfalicious** [comment]
@gumb0 This is related to the LevelDB upgrade and is by design, what do we want to do about this?

**Comment by gumb0** [comment]
We'll include a note that old DB should be deleted in 1.5 release
