### ISSUE TITLE
doCheckEvictions  

### ISSUE THREAD

**Issue by lyy4j** [ethereum/aleth#5375]
https://github.com/ethereum/aleth/blob/e9c2b9b9055fbd1f878def6a8e123414235f95e9/libp2p/NodeTable.cpp#L566

why not put  e.first()[_leastSeen->id],  but put the _new->id ? DId it delete the _new node

**Comment by gumb0** [comment]
I believe it was a bug, already fixed in https://github.com/ethereum/aleth/pull/5377 (it should delete the "least seen" now)
