### ISSUE TITLE
Aleth sends redundant ping packet when receiving ping packet from new node

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5386]
Aleth sends an unnecessary ping packet when it receives a ping packet from a new node. The impact of this bug is some unnecessary network traffic (1 extra UDP packet sent from each node) when nodes first start communicating. 

Note the "Received Ping from ##16ff0f98…" followed by "Sending Ping to ##16ff0f98…" in the console output below:

```
C:\Users\nilse\Documents\Code\aleth\build\aleth-bootnode\Debug>aleth-bootnode -v 4
aleth-bootnode, a C++ Ethereum bootnode implementation
INFO  12-07 20:37:37 main net    Id: ##51bb204f…
INFO  12-07 20:37:37 p2p  info   UPnP device not found.
TRACE 12-07 20:37:37 p2p  net    Listening on local port 30303 (public: 0.0.0.0:0)
DEBUG 12-07 20:37:37 p2p  net    p2p.started id: ##51bb204f…
Node ID: enode://51bb204f454971eaa0360c33fb33e9afdd63a6a7020d0d0c00bb709c4a506d1f74e3220050521e57195f04cfee6e71bccec31c18b78b5c8b6676a2fb33cec50e@0.0.0.0:0
DEBUG 12-07 20:37:44 p2p  discov performing random discovery
DEBUG 12-07 20:37:44 p2p  discov Terminating discover after 0 rounds.
DEBUG 12-07 20:37:45 p2p  discov Received Ping from ##16ff0f98…@127.0.0.1:30305
DEBUG 12-07 20:37:45 p2p  discov addNode pending for ##16ff0f98…@127.0.0.1 UDP 30305 TCP 30305
DEBUG 12-07 20:37:45 p2p  discov Sending Ping to ##16ff0f98…@127.0.0.1 UDP 30305 TCP 30305
DEBUG 12-07 20:37:45 p2p  discov Sending Pong to ##16ff0f98…@127.0.0.1:30305
DEBUG 12-07 20:37:45 p2p  discov Received Pong from ##16ff0f98…@127.0.0.1:30305
```

The problem is that `NodeTable::addNode` automatically pings the node being added:

https://github.com/ethereum/aleth/blob/dc0b5a2f706333951e94a56453186849a41a03ac/libp2p/NodeTable.cpp#L104-L108

However, `NodeTable::addNode` can be invoked in response to Aleth receiving a ping packet - in `NodeTable::onPacketReceived`:

https://github.com/ethereum/aleth/blob/dc0b5a2f706333951e94a56453186849a41a03ac/libp2p/NodeTable.cpp#L493-L506

**Comment by gumb0** [comment]
Sending a PING to a new node that just sent a PING to us is totally correct and required. The issue I address in https://github.com/ethereum/aleth/pull/5380 is to avoid communication with the node until we receive a valid PONG from it. So if PONG was never received before, sending PING is required.

Although we could optimize by skipping sending PING here in case we saw a valid PONG in the last 12 hours. This should be done after https://github.com/ethereum/aleth/pull/5380 is merged.

**Comment by halfalicious** [comment]
> 
> 
> Sending a PING to a new node that just sent a PING to us is totally correct and required. The issue I address in #5380 is to avoid communication with the node until we receive a valid PONG from it. So if PONG was never received before, sending PING is required.
> 
> Although we could optimize by skipping sending PING here in case we saw a valid PONG in the last 12 hours. This should be done after #5380 is merged.

I'll repurpose this bug to track this PING optimization.

**Comment by halfalicious** [comment]
This is actually a dupe of item 3 in #4959
