### ISSUE TITLE
Change copyright notice

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5403]
So I propose to change the copyright notice in each file to something simpler. Inspired by golang project.

```cpp
// Aleth: Ethereum C++ client, tools and libraries.
// Copyright 2018 Aleth Authors.
// Licensed under the GNU General Public License, Version 3.
```

First line is the project "title" as on GitHub.
The second line is the minimal copyright statement. We might want to have the AUTHORS file link to GitHub contributors page in README. E.g. https://github.com/ethereum/evmc/blob/master/AUTHORS.md

I prefer to change the file header to this one instead of only changing cpp-ethereum to Aleth. But I do not propose to change everything at once.

**Comment by gumb0** [comment]
You probably know that GPL seems to prescribe having it the way we currently do https://www.gnu.org/copyleft/gpl.html#header ("How to Apply These Terms to Your New Programs")

I don't know what could be the legal implications of this change, so I don't have an opinion.
