### ISSUE TITLE
Cannot build on Ubuntu Xenial (or anything else)

### ISSUE THREAD

**Issue by SpinMD** [ethereum/aleth#5410]
Additional, it won't work with gcc (actually, you seem to need both gcc and clang installed, and even then it won't work). Tried on Bionic, and it does not work there either. 

-- [cable ] Cable 0.2.15 initialized
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang
-- Check for working CXX compiler: /usr/bin/clang -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [cable ] Build type: RelWithDebInfo
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Performing Test fstack-protector-strong
-- Performing Test fstack-protector-strong - Success
-- Performing Test Wimplicit-fallthrough
-- Performing Test Wimplicit-fallthrough - Success
-- [hunter] Calculating Toolchain-SHA1

[hunter ** INTERNAL **] Compilation of /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/scripts/ShowPredefined.cpp failed. Result: FALSE

[hunter ** INTERNAL **] Output:
--- OUTPUT BEGIN ---
Change Dir: /home/ethereum/cpp-ethereum/build/_3rdParty/Hunter/toolchain/_builds/_test/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6e30e/fast"
/usr/bin/make -f CMakeFiles/cmTC_6e30e.dir/build.make CMakeFiles/cmTC_6e30e.dir/build
make[1]: Entering directory '/home/ethereum/cpp-ethereum/build/_3rdParty/Hunter/toolchain/_builds/_test/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_6e30e.dir/ShowPredefined.cpp.o
/usr/bin/clang    -fPIE   -std=c++11 -o CMakeFiles/cmTC_6e30e.dir/ShowPredefined.cpp.o -c /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/scripts/ShowPredefined.cpp
/root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/scripts/ShowPredefined.cpp:12:10: fatal error: 'exception' file not found
#include <exception> // Check std library version
         ^~~~~~~~~~~
1 error generated.
CMakeFiles/cmTC_6e30e.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_6e30e.dir/ShowPredefined.cpp.o' failed
make[1]: *** [CMakeFiles/cmTC_6e30e.dir/ShowPredefined.cpp.o] Error 1
make[1]: Leaving directory '/home/ethereum/cpp-ethereum/build/_3rdParty/Hunter/toolchain/_builds/_test/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_6e30e/fast' failed
make: *** [cmTC_6e30e/fast] Error 2

--- OUTPUT END ---
[hunter ** INTERNAL **] [Directory:/home/ethereum/cpp-ethereum/build/_3rdParty/Hunter/toolchain]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  CMakeLists.txt:85 (hunter_internal_error)

[hunter ** INTERNAL **] Generate failed: exit with code 1
[hunter ** INTERNAL **] [Directory:/home/ethereum/cpp-ethereum]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:110 (hunter_internal_error)
  /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:135 (hunter_calculate_toolchain_sha1)
  /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  /root/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:65 (hunter_add_package)

-- Configuring incomplete, errors occurred!

**Comment by moneroexamples** [comment]
What is your compilation procedure? I just checked on both ubuntu 16.04 and 18.04 and aleth builds without any issues using default gcc. There was no need for clang nor any changes other than using newer cmake on 16.04.

Did you clone current aleth master branch with `--recursive` flag?

**Comment by SpinMD** [comment]
The reason for using clang is that gcc compiles fail with " -c is not a
valid preprocessor directive" - same on both machines, which are Intel Core
something.  (I believe I also had the
same error message on a Sparc64 running OpenBSD, I would not swear to it).

see attached log.

**Comment by moneroexamples** [comment]
I the logs you provided there is no such message " -c is not a valid preprocessor directive". Nevertheless, regarding it I found only [this](https://stackoverflow.com/questions/3299754/cpp-c-is-not-a-valid-option-to-the-preprocessor/3317830#3317830) which leads me to believe that your ubuntu 16.04 or 18.04 has some mixed up settings regarding the compilers. `clang` is not needed to compile aleth. Just default `gcc` bundled with the ubuntu is sufficient. 

And if you want to use clang, you need to specify it before you run cmake, e.g.:
```
# delete current bulld folder of aleth, and then rebuild using
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
mkdir build && cd build
cmake .. 
```

P.s. in your log I see the following now:

```
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
[...]
-- Check for working CXX compiler: /usr/bin/clang
-- Check for working CXX compiler: /usr/bin/clang -- works
```
This is incorrect setup as `cc` and `clang` are both C compilers.

**Comment by SpinMD** [comment]
Sorry, looks like I appended the wrong log file

-------------------%<---------------------------

root@chicago:/home/ethereum/cpp-ethereum/build# cmake ..
-- [cable ] Cable 0.2.15 initialized
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/cpp
-- Check for working CXX compiler: /usr/bin/cpp -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45
(message):
  The C++ compiler

    "/usr/bin/cpp"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/ethereum/cpp-ethereum/build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_59fb0/fast"
    /usr/bin/make -f CMakeFiles/cmTC_59fb0.dir/build.make
CMakeFiles/cmTC_59fb0.dir/build
    make[1]: Entering directory
'/home/ethereum/cpp-ethereum/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_59fb0.dir/testCXXCompiler.cxx.o
    /usr/bin/cpp     -o CMakeFiles/cmTC_59fb0.dir/testCXXCompiler.cxx.o -c
/home/ethereum/cpp-ethereum/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
    compilation terminated.
    CMakeFiles/cmTC_59fb0.dir/build.make:65: recipe for target
'CMakeFiles/cmTC_59fb0.dir/testCXXCompiler.cxx.o' failed
    make[1]: *** [CMakeFiles/cmTC_59fb0.dir/testCXXCompiler.cxx.o] Error 1
    make[1]: Leaving directory
'/home/ethereum/cpp-ethereum/build/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_59fb0/fast' failed
    make: *** [cmTC_59fb0/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:47 (project)


-- Configuring incomplete, errors occurred!
See also "/home/ethereum/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".
See also "/home/ethereum/cpp-ethereum/build/CMakeFiles/CMakeError.log".
-------------------%<---------------------------

This is what I was seeing before I tried using clang.

regards

Andrew

**Comment by SpinMD** [comment]
Thanks. My troubles are over (at least on Xenial). Will let you know about
Sparc64 later ;-)

Andrew
