### ISSUE TITLE
Link error in windows environment.

### ISSUE THREAD

**Issue by tjkim0706** [ethereum/aleth#5413]
hey guys~

Is the static library environment the default?
When I checked the properties of all VS projects I built in the Windows environment, the default was a dynamic library environment (runtime library: multi-threaded DLL).
This causes multiple errors.
Hunter package too.

.......
1>ethcore.lib(KeyManager.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in main.obj
1>libboost_program_options-mt-s.lib(options_description.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in main.obj
1>libboost_filesystem-mt-s.lib(path_traits.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in main.obj
.......

**Comment by chfast** [comment]
Hunter builds all dependencies as static libraries by default.

Here you have problem how the C++ standard library is going to be linked.

We would need following information from you:

1. What is your Visual Studio version?
2. Are you building x64 architecture?
3. Can you find in the project properties where exactly are Boost libraries located?
4. Do you have Boost installed in other way than Hunter?

One thing you can try yourself is to delete whole `C:\.Hunter` directory and start the build from scratch.

**Comment by tjkim0706** [comment]
> * What is your Visual Studio version?
**I used "visual c ++ build tools 2015" to build VisualStudio environment(cmake .. -G "Visual Studio 14 2015 Win64"), and I am using VisualStudio2017 for my current test.**

> * Are you building x64 architecture?
**Yes, it is.**

> * Can you find in the project properties where exactly are Boost libraries located?
**( VS properties -> C/C++ -> Additional include Directories )
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\include
( VS properties -> Linker -> input -> Additional Dependencies )
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_program_options-mt-s.lib
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_filesystem-mt-s.lib
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_system-mt-s.lib
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_log-mt-s.lib
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_thread-mt-s.lib
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\ethash.lib
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\snappy.lib
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\cryptopp-static.lib
C:\\.hunter\_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\scrypt.lib
-It is automatically generated using "cmake .. -G Visual Studio 14 2015 Win64"**

> * Do you have Boost installed in other way than Hunter?
**No, only Hunter.**

Thank you for your answer.
Thank you very much~

**Comment by tjkim0706** [comment]
I closed it by mistake.
sorry~

**Comment by gumb0** [comment]
> C:\.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_program_options-mt-s.lib
> C:\.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_filesystem-mt-s.lib
> C:\.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_system-mt-s.lib
> ...

This is old hunter version, we don't use it since last November. Are you sure you're building from latest `master` ?

**Comment by tjkim0706** [comment]
> > C:.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_program_options-mt-s.lib
> > C:.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_filesystem-mt-s.lib
> > C:.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_system-mt-s.lib
> > ...
> 
> This is old hunter version, we don't use it since last November. Are you sure you're building from latest `master` ?

I recompiled "aleth branch release / 1.4" yesterday and I succeeded in building it.
After changing the encoding type of some files.
What changes are there?
![aleth_branch_release_1 4](https://user-images.githubusercontent.com/6148902/51787007-c505dd00-21af-11e9-8495-bcdf75668ee7.png)

**Comment by tjkim0706** [comment]
> > C:.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_program_options-mt-s.lib
> > C:.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_filesystem-mt-s.lib
> > C:.hunter_Base\aa1facc\22fa2e3\4de1f3d\Install\lib\libboost_system-mt-s.lib
> > ...
> 
> This is old hunter version, we don't use it since last November. Are you sure you're building from latest `master` ?

I recompiled "aleth branch:release/1.4" yesterday and I succeeded in building it.
After changing the encoding type of some files.
Errors that have occurred in the meantime suddenly disappeared.
What changes are there?
thank you very much~!
![aleth_branch_release_1 4](https://user-images.githubusercontent.com/6148902/51787253-db616800-21b2-11e9-9b3b-8d9c5edb516e.png)
