### ISSUE TITLE
Request: remove required fields (nonce + code) in genesis/config

### ISSUE THREAD

**Issue by holiman** [ethereum/aleth#5414]
Aleth requires empty fields to be present in the chain config. This causes some problems in hive. 

Examples:
```
[24d0e1ec] Expected field 'code' not found in config: validateAccountObj
[24d0e1ec] {
[24d0e1ec]     "balance" : "0xde0b6b3a7640000",
[24d0e1ec]     "nonce" : "0xcc6"
[24d0e1ec] }
```
And
```
[1d55a9fe] Expected field 'nonce' not found in config: validateAccountObj
[1d55a9fe] {
[1d55a9fe]     "balance" : "0xde0b6b3a7640000",
[1d55a9fe]     "code" : "0x7f6004600c6000
```

This _can_ be fixed in the bash-script, but it's a bit of a PITA to go through all accounts with `jq` and add zeroes and empty strings to all accounts. So I propose that you default to `empty` code if not specified, and `0` nonce if not specified, which seems to be what both parity and geth does.

**Comment by winsvega** [comment]
The allowed accounts for aleth genesis: 

1) Precompiled account
```
	"0000000000000000000000000000000000000001": {
                "precompiled": { "name": "ecrecover", "linear": { "base": 3000, "word": 0 } } 
       },
```

2) Precompiled account with balance (wei / balance field)
```
	"0000000000000000000000000000000000000001": {
                "precompiled": { "name": "ecrecover", "linear": { "base": 3000, "word": 0 } },
                "balance": "123456"
       },
```

3) Account with only 1 field - balance (wei / balance field)
```
       "1a34bc3400000000000000000000000000000000": {
                "wei": "123456"
       },
```

4) Full account with 4 fields (code/code from file, nonce, storage, balance)
```
	"e20bb9f3966419e14bbbaaaa6789e92496cfa479": {
		"balance": "3465116000000000000000",
                "nonce" : "0",
                "code" : "0x01",
                "storage" : {}
	}
```

**Comment by gumb0** [comment]
I don't mind.

At least it should be possible to set balance and nonce without explicit code; and code without storage; current validation annoys me, too.

**Comment by winsvega** [comment]
if all fields are optional, is it an empty contract or non existent?

**Comment by gumb0** [comment]
I think it should be allowed and create an empty account, this will be useful to reproduce some test scenarios.
(though not sure it will work if Spurious Dragon starts at genesis)
