### ISSUE TITLE
Node sorting does not work

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5470]
I discovered that a container of `Node` objects (including `Peer`) is buggy. It compiles only because `Node` types are implicitly convertible to `bool` so the sort will just put "null" nodes up front.

Please fix it by defining `operator<` for `Node` type.

Add unit test.

**Comment by gumb0** [comment]
Which container, where is it needed?

I removed `Peer::operator<` but maybe I relied on compilation to ensure it's not needed, so maybe it was a mistake
https://github.com/ethereum/aleth/pull/5354

**Comment by gumb0** [comment]
Ah I see that's `Host::saveNetwork()` sorts the peers. Not sure that's useful..

**Comment by chfast** [comment]
Sort is used twice in `saveNetwork()`: https://github.com/ethereum/aleth/pull/5472/commits/56e2f8fc02d3e87abe983b6a39c790d8c91c3d20.

**Comment by gumb0** [comment]
I think I'll remove sorting from the `saveNetwork()` - the order certainly doesn't matter for `NodeTable` nodes, and for peers - I don't think it will be much worse to connect to them in arbitrary order, we usually don't have many peers anyway.

And for this issue I would prefer to remove `operator bool` from Node, it doesn't look like a good idea to have it.

**Comment by chfast** [comment]
The `operator bool` is used in the pattern `if (auto n = getNode())`. I make it explicit in #5472 so this disables buggy sorting and other incorrect uses.
