### ISSUE TITLE
Warning about saving network configuration

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5479]
It happens all the time when Aleth is shutting down.
```
CWARN  02-08 12:10:57 aleth warn   Cannot save network configuration while network is still running.
```

**Comment by halfalicious** [comment]
We need to call` WebThreeDirect::stopNetwork()` before` WebThreeDirect::saveNetwork()` in Aleth's `main.cpp`:

https://github.com/ethereum/aleth/blob/303d11725cb756fa2c2d0820f73ce2d4a22e1247/aleth/main.cpp#L1054-L1059
