### ISSUE TITLE
Discovery timer stops unexpectedly

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#5495]
Sometimes after running `aleth` on Linux (on the mainnet) for some time (~5-10 mins), I observe this
```
DEBUG 02-15 15:09:34 p2p  discov Ping to ##719e0907…@167.99.102.6:50000
DEBUG 02-15 15:09:37 p2p  discov Ping from ##201dd24c…@34.248.64.28:21000
DEBUG 02-15 15:09:37 p2p  discov Adding node ##201dd24c…@34.248.64.28:21000
DEBUG 02-15 15:09:37 p2p  discov Pending ##201dd24c…@34.248.64.28:21000
DEBUG 02-15 15:09:37 p2p  discov Pong to ##201dd24c…@34.248.64.28:21000
DEBUG 02-15 15:09:41 p2p  discov Discovery timer was probably cancelled: 125 Operation canceled
```
Error is returned to the timer's callback, and after that discovery stops.
No idea why, we should look into which error is returned.
(the process doesn't stop, some Pings and Pongs continue to be received/sent)

I observe this on my branch from https://github.com/ethereum/aleth/pull/5483, not sure if the problem existed before those changes.

**Comment by halfalicious** [comment]
Will do some testing to see if I hit this

**Comment by halfalicious** [comment]
Able to hit this on Windows on master sync'd to: 

```
commit df1048c695327854a897ba5da77a442f494265bd (HEAD -> master, origin/master, origin/HEAD)
Merge: b6a176e1e 2cb9d4b67
Author: Pawe<C5><82> Bylica <chfast@gmail.com>
Date:   Wed Feb 13 16:03:38 2019 +0100

    Merge pull request #5487 from ethereum/eip8-unittest

    EIP-8 unittests
```

I'm also seeing the discovery process stop, but the network thread keeps running and we keep interacting with nodes in the node table.

Log (filtered to "discov" channel with verbosity = 4): [mainnet_sync_discov.txt](https://github.com/ethereum/aleth/files/2871338/mainnet_sync_discov.txt)

**Comment by halfalicious** [comment]
And also seeing this when syncing ropsten.

**Comment by halfalicious** [comment]
I'm not able to repro this when running aleth-bootnode with the boostrap change so it looks like this has something to do with non-discovery functionality causing the timer to stop - when running aleth I was able to consistently repro this within a few minutes but I've run aleth-bootnode for 10+ minutes without the timer getting cancelled.

**Comment by moneroexamples** [comment]
> And also seeing this when syncing ropsten.

Are you able to fully sync to ropsten? I keep getting stuck and haven't been able to sync to it since about 1-2 months now. Maybe this is because of that issue.

**Comment by halfalicious** [comment]
@moneroexamples I haven't tried fully syncing ropsten in a long time. Can you please open a new issue?

**Comment by halfalicious** [comment]
Also hitting on 1.5.2

**Comment by moneroexamples** [comment]
yes, I will open new issue once I have anything concrete to report. For not its just try-and-see approach without actually looking into the logs or possible causes.

**Comment by halfalicious** [comment]
I suspect the problem is that `DeadlineOps `(collection of deadline timers) is deleting a timer before its handler has executed. See `DeadlineOps::reap`: https://github.com/ethereum/aleth/blob/b09978bf17442dd9444c55984802dfbcd3c9bce1/libp2p/Common.cpp#L158-L178

Note that `DeadlineOps::reap` iterates through its vector of timers and deletes ones that are expired (one adds timers to this vector via `DeadlineOps::schedule`). However, `DeadlineOp::expired` simply checks if the expiration time is in the past. However, I don't think that the handlers are guaranteed to execute precisely when the timer expires, meaning that there's a race condition where the timer is deleted after its expiration time has occurred but before the handler has been executed. The one variable is that this depends on the synchronous wait call not waiting for the handler to execute. This seemed a little far-fetched to me (but possible since the synchronous wait was occurring after an async wait had already been made) but this was the best theory I had so far, so I decided to test it out - I set a random int as a timer ID in each `DeadlineOp ` on creation and captured this same ID in the scheduled handler. I also added some code to failfast when the discovery timer cancel case was hit. I then checked when the timer cancel case was hit if a timer with the captured ID was in the DeadlineOps timer vector and it wasn't.

**Comment by halfalicious** [comment]
> 
> 
> I suspect the problem is that `DeadlineOps `(collection of boost deadline timers) is deleting a timer before its handler has executed. See `DeadlineOps::reap`:
> 
> [aleth/libp2p/Common.cpp](https://github.com/ethereum/aleth/blob/b09978bf17442dd9444c55984802dfbcd3c9bce1/libp2p/Common.cpp#L158-L178)
> 
> Lines 158 to 178 in [b09978b](/ethereum/aleth/commit/b09978bf17442dd9444c55984802dfbcd3c9bce1)
>  void DeadlineOps::reap() 
>  { 
>      if (m_stopped) 
>          return; 
>   
>      Guard l(x_timers); 
>      auto t = m_timers.begin(); 
>      while (t != m_timers.end()) 
>          if (t->expired()) 
>          { 
>              t->wait(); 
>              t = m_timers.erase(t); 
>          } 
>          else 
>              t++; 
>   
>      m_timers.emplace_back(m_io, m_reapIntervalMs, [this](boost::system::error_code const& ec) { 
>          if (!ec && !m_stopped) 
>              reap(); 
>      }); 
>  } 
> 
> Note that `DeadlineOps::reap` iterates through its vector of timers and deletes ones that are expired (one adds timers to this vector via `DeadlineOps::schedule`). However, `DeadlineOp::expired` simply checks if the expiration time is in the past and I don't think that the handlers are guaranteed to execute precisely when the timer expires, meaning that there's a race condition where the timer is deleted after its expiration time has occurred but before the handler has been executed. The one variable is that this depends on the synchronous wait call not waiting for the handler to execute.
> 
> This seemed a little far-fetched to me (but possible since the synchronous wait was occurring after an async wait had already been started) but this was the best theory I had so far, so I decided to test it out - I set a random int as a timer ID in each `DeadlineOp ` on creation and captured this same ID in the scheduled handler. I also added some code to failfast when the discovery timer cancel case was hit. I then checked when the timer cancel case was hit if a timer with the captured ID was in the `DeadlineOps `timer vector and didn't find any.

According to this boost mailing list thread my suspicion is correct: https://lists.boost.org/Archives/boost/2005/09/94433.php

**Comment by gumb0** [comment]
I'm still not sure I understand what was the exact reason of timer being cancelled.

> Note that DeadlineOps::reap iterates through its vector of timers and deletes ones that are expired (one adds timers to this vector via DeadlineOps::schedule). However, DeadlineOp::expired simply checks if the expiration time is in the past and I don't think that the handlers are guaranteed to execute precisely when the timer expires, meaning that there's a race condition where the timer is deleted after its expiration time has occurred but before the handler has been executed. 

But it does `wait()` before deleting the timer - it should wait until the callback is executed. And only then the timer is deleted.

**Comment by halfalicious** [comment]
> 
> 
> I'm still not sure I understand what was the exact reason of timer being cancelled.
> 
> > Note that DeadlineOps::reap iterates through its vector of timers and deletes ones that are expired (one adds timers to this vector via DeadlineOps::schedule). However, DeadlineOp::expired simply checks if the expiration time is in the past and I don't think that the handlers are guaranteed to execute precisely when the timer expires, meaning that there's a race condition where the timer is deleted after its expiration time has occurred but before the handler has been executed.
> 
> But it does `wait()` before deleting the timer - it should wait until the callback is executed. And only then the timer is deleted.

@gumb0 : Have you confirmed that this actually happens? Because the fact that the bug occurs indicates otherwise...I haven't found any examples where one calls wait() after async_wait(), I'm guessing this is effectively a noop. I'll throw together a little test program to verify my suspicion.
