### ISSUE TITLE
Blockchain tests fail with error: "network not found: ConstantinopleFix"

### ISSUE THREAD

**Issue by mxito3** [ethereum/aleth#5497]
I met following error after run ./testeth in aleth/build/test directory! 
```
/home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": SstoreCallToSelfSubRefundBelowZero network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": SstoreCallToSelfSubRefundBelowZero network not found: ConstantinopleFix 96%... /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: Constantinop
```
This is only a part of the error log. other errors look in the same pattern as above.
And i am at git tag v1.6.0-alpha.0

**Comment by halfalicious** [comment]
> 
> 
> I met following error after run ./testeth in aleth/build/test directory!
> 
> ```
> /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_XtoXto0 network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": SstoreCallToSelfSubRefundBelowZero network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": SstoreCallToSelfSubRefundBelowZero network not found: ConstantinopleFix 96%... /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: ConstantinopleFix /home/yapie/github/aleth/test/tools/libtesteth/TestHelper.cpp(147): error: in "GeneralStateTests/stSStoreTest": sstore_0toXto0toX network not found: Constantinop
> ```
> 
> This is only a part of the error log. other errors look in the same pattern as above.
> And i am at git tag v1.6.0-alpha.0

Thanks for filing this @mxito3 ! I also get this when building master (running Windows 10).

@winsvega : Is this a known issue?

**Comment by winsvega** [comment]
No it shouldn't be like this. Latest testeth is updated to support ConstantinopleFix

**Comment by chfast** [comment]
`git submodule update`

**Comment by halfalicious** [comment]
> 
> 
> `git submodule update`

I did that before building my enlistment

**Comment by winsvega** [comment]
Tell which aleth hash and what tests hash you use. I will try to reproduce

**Comment by chfast** [comment]
Fixed be reclone of the project.

**Comment by winsvega** [comment]
Current aleth automation build scripts are passing the tests.
