### ISSUE TITLE
Ethereum capability work loop can be cancelled prematurely

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5508]
Ethereum capabilities make use of boost deadline timers to schedule their work loop via `Host::scheduleExecution` - for example: https://github.com/ethereum/aleth/blob/9e5a853e69fef515617969646a96f788e2b2feed/libethereum/EthereumCapability.cpp#L413-L417

...and in` EthereumCapability::doBackgroundWork`: https://github.com/ethereum/aleth/blob/9e5a853e69fef515617969646a96f788e2b2feed/libethereum/EthereumCapability.cpp#L488-L490

Note that Host's usage of deadline timers is susceptible to a race condition - `Host::scheduleExecution `creates a new timer, adds it to a list, and performs an async_wait on it. The host then "garbage collects" expired timers in `Host::run`, and it determines if a timer is expired by checking its expiration time: https://github.com/ethereum/aleth/blob/9e5a853e69fef515617969646a96f788e2b2feed/libp2p/Host.cpp#L687-L692

However, note that when a timer expires, its handler is put into a queue rather than being executed immediately - this means that there's a race condition where a handler can be executed after the timer has been deleted, resulting in the handler being executed with boost error code `operation_aborted`, which will result in the handler immediately exiting without executing any of its core logic.

**Comment by halfalicious** [comment]
Anything which uses Host::scheduleExecution or CapabilityHost::scheduleExecution (which in turn calls Host::scheduleExecution) is susceptible to this bug...currently it looks like only the Capability implementations use this. Here is the code which need to be updated:
* Any place where a capability background work loop is scheduled: 
  *  EthereumCapability::onStarting: https://github.com/ethereum/aleth/blob/594f141235e0bbf94b9443b798f20230097fe4ad/libethereum/EthereumCapability.cpp#L413-L417 
  * EthereumCapability::doBackgroundwork: https://github.com/ethereum/aleth/blob/594f141235e0bbf94b9443b798f20230097fe4ad/libethereum/EthereumCapability.cpp#L488-L490
  * WarpCapability::onStarting: https://github.com/ethereum/aleth/blob/594f141235e0bbf94b9443b798f20230097fe4ad/libethereum/WarpCapability.cpp#L326-L330
  * WarpCapability::doBackgroundWork: https://github.com/ethereum/aleth/blob/594f141235e0bbf94b9443b798f20230097fe4ad/libethereum/WarpCapability.cpp#L356-L358

Other capability code: 
* EthereumCapability::reset: https://github.com/ethereum/aleth/blob/594f141235e0bbf94b9443b798f20230097fe4ad/libethereum/EthereumCapability.cpp#L438-L448
* EthereumCapability::onTransactionImported: https://github.com/ethereum/aleth/blob/594f141235e0bbf94b9443b798f20230097fe4ad/libethereum/EthereumCapability.cpp#L646-L673

**Comment by gumb0** [comment]
In any case I'd like for Capability implemenations to stay decoupled from `Host` internals, in particular they shouldn't care about `io_service` or timers.

I guess we could create a timer in `Host` per each registered Capability somehow.

**Comment by halfalicious** [comment]
> `_service` or tim

Yea, off of the top of my head I think we need to do something like that so that Capability implementations can continue to run on the network thread otherwise we'd need to have Capability implementations inherit from Worker which might complicate things.
