### ISSUE TITLE
Add log channels to Aleth command-line help output

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5549]
Aleth logs messages to various Boost log channels and has 4 levels of logging which increase in verbosity from level 0 (no logging) to 4 (verbose logging). The log level can be set at runtime (via `-v<level>`), and similarly log channels can be enabled or disabled via the `--log-channels` and `--log-exclude-channels` args. Aleth's command-line help output (`aleth -h`) lists all of these args, but it doesn't include the list of available channels which can make it difficult for one to determine which channels to enable / disable.

To address this, the command-line help output for Aleth should be updated to include the list of log channels. The logging command line help output is built here: https://github.com/ethereum/aleth/blob/ad7204c9ae7a13359520b7c21ffd8fc7484cf589/libdevcore/LoggingProgramOptions.cpp#L24-L42

Aleth calls the function here: https://github.com/ethereum/aleth/blob/ad7204c9ae7a13359520b7c21ffd8fc7484cf589/aleth/main.cpp#L325-L326

A log channel is defined when a `Logger` object is created - for example, the following `Logger ` writes messages to the "net" channel: https://github.com/ethereum/aleth/blob/ad7204c9ae7a13359520b7c21ffd8fc7484cf589/libp2p/Host.h#L371

You can build a list of all channels by searching the codebase for instances of `Logger m_logger`. Don't include loggers defined in test files (i.e. files under `aleth\tools`)

Also, `createLoggingProgramOptions ` is used by multiple Aleth tools (e.g. `aleth-bootnode`) and these tools don't use the same set of log channels as Aleth, but we still want `createLoggingOptions ` to be general purpose. To address this, you should build the list of log channels in Aleth's `main.cpp` and pass it into `createLoggingProgramOptions ` where you include it in the `boost::program_options:options_description` being built. You can pass in empty strings in the other tools. These tools are:
* **aleth-bootnode**: https://github.com/ethereum/aleth/blob/ad7204c9ae7a13359520b7c21ffd8fc7484cf589/aleth-bootnode/main.cpp#L42-L43
* **aleth-vm**: https://github.com/ethereum/aleth/blob/ad7204c9ae7a13359520b7c21ffd8fc7484cf589/aleth-vm/main.cpp#L124-L125
* **aleth-key**:  https://github.com/ethereum/aleth/blob/ad7204c9ae7a13359520b7c21ffd8fc7484cf589/aleth-key/main.cpp#L41-L42

**Comment by twinstar26** [comment]
Hi,
I am interested in solving this issue.

**Comment by halfalicious** [comment]
Sounds good, it’s yours @twinstar26  😄

**Comment by gumb0** [comment]
Note also: not all loggers are member variables defined as `Logger m_logger`.
There are also global loggers, search for `BOOST_LOG_INLINE_GLOBAL_LOGGER_CTOR_ARGS` to find them (I think they are only in `libdevcore/Log.h` and `libp2p/Common.h`)

**Comment by twinstar26** [comment]
@halfalicious 
Have a doubt regarding the last paragraph,
So when we execute ./aleth -h then and then only we want to display a section which shows list of all channels (irrespective if those channels are applicable for user or not)
and when we execute ./aleth-bootnode -h and other tools then we need not display list of all channels (we can do this by passing empty strings from these tools to `aleth/libdevcore/LoggingProgramOptions.cpp`)

Have I understood the issue correctly?

**Comment by halfalicious** [comment]
> 
> 
> @halfalicious
> Have a doubt regarding the last paragraph,
> So when we execute ./aleth -h then and then only we want to display a section which shows list of all channels (irrespective if those channels are applicable for user or not)
> and when we execute ./aleth-bootnode -h and other tools then we need not display list of all channels (we can do this by passing empty strings from these tools to `aleth/libdevcore/LoggingProgramOptions.cpp`)
> 
> Have I understood the issue correctly?

That's correct. From what I understand, Aleth can log to all channels which is why we want to display the entire list. I'm not sure which channels the other tools log to and will need to do some research, which is why I think we should not log channel lists for them at this point.

**Comment by twinstar26** [comment]
@halfalicious 
So how is this declaration looking??
`    ///List_logging_channels
    const std::multimap<string,string> list_log_channels = {{"VerbosityError","chain"},
                                                            {"VerbosityInfo","sync"},
                                                            {"VerbosityInfo","client"},
                                                            {"VerbosityInfo","snap"},
                                                            {"VerbosityInfo","tq"},
                                                            {"VerbosityDebug","blockhdr"},
                                                            {"VerbosityDebug","block"},
                                                            {"VerbosityDebug","chain"},
                                                            {"VerbosityDebug","sync"},
                                                            {"VerbosityDebug","bq"},
                                                            {"VerbosityDebug","client"},
                                                            {"VerbosityDebug","watch"},
                                                            {"VerbosityDebug","host"},
                                                            {"VerbosityDebug","ethcap"},
                                                            {"VerbosityDebug","impolite"},
                                                            {"VerbosityDebug","peer"},
                                                            {"VerbosityDebug","tq"},
                                                            {"VerbosityDebug","net"},
                                                            {"VerbosityDebug","discov"},
                                                            {"VerbosityTrace","block"},
                                                            {"VerbosityTrace","chain"},
                                                            {"VerbosityTrace","sync"},
                                                            {"VerbosityTrace","bq"},
                                                            {"VerbosityTrace","net"}}`

Declaration can be found over here
https://github.com/ethereum/aleth/blob/dbbfd5bea14dc54726ad9583c4341ad6ac1524b7/libdevcore/Log.h#L65-L73
So that user will come to know for which verbosity which channels are going to remain active.
Currently multimap has <string,string>, which can be changed to <int,string> so that user can understand it better.

https://github.com/ethereum/aleth/issues/5549#issuecomment-480804081
Also I will address this later.

**Comment by gumb0** [comment]
@twinstar26 How exactly do you intend to make it look in help output?
I suspect it would be too much info, which would make it less readable / too overwhelming for a user.

Also too much maintenance pain to support this kind of list (as verbosities might change more often than the channel list)

So I think the list of strings with channel names should be enough.

**Comment by twinstar26** [comment]
@gumb0 
Actually I was thinking of creating an option for aleth (for eg: `./aleth --list_channels`) 
But if we are planning to put this in help menu then I agree with you that it will be less readable.
So should we go with option 1 or 2 or both??

**Comment by twinstar26** [comment]
Also I have made the list of channels hard-coded as this is before runtime (as in this list should be visible to user even before we start execution) which will make it hard to maintain.

Apart from aleth if we are planning the same for other tools then I think creating an option will be wise choice (for eg: `./aleth --list_channels`) not for developers and maintainers but for users. :sweat_smile: :rofl:

**Comment by halfalicious** [comment]
I don't think --list_channels is necessary, I think including the channel list in the --help/-h output is enough. I agree with @gumb0 , I think that we want this information to be lightweight and easy to digest so just including a list of the channel names is sufficient.

**Comment by twinstar26** [comment]
Alright. I will start working straight away.

**Comment by halfalicious** [comment]
@twinstar26: Thank you for your contribution!
