### ISSUE TITLE
testeth reports not built with -DVMTRACE=1 even when it was

### ISSUE THREAD

**Issue by yxliang01** [ethereum/aleth#5565]
This happens when I run testeth with a docker setup. But, I think it has nothing to do with the docker setup.

**Comment by yxliang01** [comment]
The `VMTRACE` option was added to Docker builds in https://github.com/ethereum/aleth/pull/5490 . However, it has no use since it conflicts with `-DCMAKE_BUILD_TYPE=Release` that vmtrace can only be enabled for debug builds. Should the `CMAKE_BUILD_TYPE` be made as a build-time arg? Or, some other solutions?

CC: @gumb0 @chfast

**Comment by chfast** [comment]
The issue is confirmed. I started working on this in the PR attached, but we need more time to finish it so it will not be included in 1.6.0.
