### ISSUE TITLE
Consensus tests related error messages when running unit tests

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#5584]
Now I see error messages from https://github.com/ethereum/aleth/pull/5558 when running unit tests
```
> test/testeth -t network/net/udpOnce
Running tests using path: "../../test/jsontests"
Running 1 test case...
Test Case "udpOnce": 

*** No errors detected
ERROR: Expected a single test to be passed: net/udpOnce
```

Please fix this.

**Comment by winsvega** [comment]
A solution would be to perform this check when 
```
    set<string> const allowedSuites { string{"GeneralStateTests"}, string{"VMTests"}, string{"BlockchainTests"}, string{"BCGeneralStateTests"},
                string{"TransactionTests"}, string{"BCGeneralStateTests"}, string{"TransitionTests"}};
    if (!allowedSuites.count(suite))
        return;
```

or don't print an error. and just return in this case. 
that check ensure that when running a single test case you run at least one test case. which should always be true.

if it false it means the test is not marked as passed / completed in the test logic.
but only those tests are being marked and checked.
