### ISSUE TITLE
cpp-build-env docker image should use a newer version of Cmake

### ISSUE THREAD

**Issue by jwasinger** [ethereum/aleth#5594]
Currently doesn't allow projects like https://github.com/ewasm/hera to be built.

**Comment by jwasinger** [comment]
@chfast I think the image just needs to be rebuilt and pushed to dockerhub.  All the problems I had went away when I built locally and used it.

**Comment by chfast** [comment]
The issue is probably due to the fact the `:latest` is not being updated. The version `:11` has cmake 3.13.4.

I updated the `:latest` to `:11`.
