### ISSUE TITLE
Contract with instructions like 'GAS; CALL' field without eip150Mode enable

### ISSUE THREAD

**Issue by ReeceNee** [ethereum/aleth#5606]
# Description

When the `eip150Mode` in the `libethcore\EVMSchedule.h\EVMSchedule` is `false`( default value), any contract with instructions `GAS; CALL`  can't be execution correctly. Instead, it will throw out-of-gas exception even with enough gas.

The question is in the `bool LegacyVM::caseCallSetup(CallParameters *callParams, bytesRef& o_output)` in [LegacyVMCalls.cpp](https://github.com/ethereum/aleth/blob/0fe8de86f70294bc149eb20bda5b0bad6090b4c0/libevm/LegacyVMCalls.cpp#L201). 

After `GAS` instruction was executed, the top of the EVM's stack will be set to `m_io_gas` ([LegacyVM.cpp](https://github.com/ethereum/aleth/blob/0fe8de86f70294bc149eb20bda5b0bad6090b4c0/libevm/LegacyVM.cpp#L1680), we set the value of m_io_gas now as `x`). 

Then when the `CALL` was being executing, the blamed function `bool LegacyVM::caseCallSetup(CallParameters *callParams, bytesRef& o_output)` will be called. In this function, the `m_run_gas` will be first set as `40` ([line 207](https://github.com/ethereum/aleth/blob/0fe8de86f70294bc149eb20bda5b0bad6090b4c0/libevm/LegacyVMCalls.cpp#L207)), then the `m_io_gas` will be update to `x-40` with the first call to [ updateIOGas()](https://github.com/ethereum/aleth/blob/0fe8de86f70294bc149eb20bda5b0bad6090b4c0/libevm/LegacyVMCalls.cpp#L231). Then in the [line 237](https://github.com/ethereum/aleth/blob/0fe8de86f70294bc149eb20bda5b0bad6090b4c0/libevm/LegacyVMCalls.cpp#L237) and [line 246](https://github.com/ethereum/aleth/blob/0fe8de86f70294bc149eb20bda5b0bad6090b4c0/libevm/LegacyVMCalls.cpp#L246), the m_run_gas will be set to the top value of stack(`x`).

 It means the m_io_gas(`x-40`) is less than m_run_gas(`x`) now. So the contract will definitely throw exception with the second call to [updateIOGas()](https://github.com/ethereum/aleth/blob/0fe8de86f70294bc149eb20bda5b0bad6090b4c0/libevm/LegacyVMCalls.cpp#L247).

# Testcase

The source of test contract is below.
```
pragma solidity ^0.4.24;

contract TXLog{
    uint tx_number = 0;
 
    function update_number(uint n) public returns(uint){
        tx_number += n;
        return tx_number;
    }
}

contract BasicTX{
    uint latest_number;
    
    function oneTX() public{
        TXLog txlog = new TXLog();
        latest_number = txlog.update_number(1);
    }
}

```

After Compiling the source code, we'll get the real contract code of `BasicTX`.  Then we use the binary [aleth-vm](https://github.com/ethereum/aleth/tree/0fe8de86f70294bc149eb20bda5b0bad6090b4c0/aleth-vm) to call the `oneTX()` function. The execution will terminated after `CALL` instruction.

The test command is below.

```
./aleth-vm --mnemonic --code 608060405260043610610041576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806337e0e0d214610046575b600080fd5b34801561005257600080fd5b5061005b61005d565b005b600061006761013a565b604051809103906000f080158015610083573d6000803e3d6000fd5b5090508073ffffffffffffffffffffffffffffffffffffffff166340e0aebe60016040518263ffffffff167c010000000000000000000000000000000000000000000000000000000002815260040180828152602001915050602060405180830381600087803b1580156100f657600080fd5b505af115801561010a573d6000803e3d6000fd5b505050506040513d602081101561012057600080fd5b810190808051906020019092919050505060008190555050565b60405160ec8061014a83390190560060806040526000805534801561001457600080fd5b5060c9806100236000396000f300608060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806340e0aebe146044575b600080fd5b348015604f57600080fd5b50606c600480360381019080803590602001909291905050506082565b6040518082815260200191505060405180910390f35b600081600080828254019250508190555060005490509190505600a165627a7a7230582082d745e71388df138ede39a772f31c09e790421d46d62de601b6d9d61908a4550029a165627a7a72305820dc9dea30ea360f41a44f9fef1a3f293edc51981c90f56a587d324006173a78700029 --input 0x37e0e0d2 trace
```

**Comment by halfalicious** [comment]
cc @chfast

**Comment by chfast** [comment]
Everything you have written in the Description is true and this is expected behavior. If solidity generates bytecode like that the contract will not be able to execute before EIP150 is activated. You have to consult with solidity about this.

cc @axic, @chriseth.

**Comment by chriseth** [comment]
If you want code generated by Solidity to be able to run on non-current EVMs, you have to specify the EVM version you would like to have, in this case, `--evm-version homestead` or `--evm-version tangerineWhistle`.

**Comment by chfast** [comment]
Thanks @chriseth.
