### ISSUE TITLE
Aleth vs Geth peer connectivity investigation

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5607]
During local tests of syncing Aleth on mainnet, I've never seen peer counts greater than 13. However, while browsing the Geth gitter channel I've seen users mention of running Geth and having peer counts of > 60. We should do some experiments to determine how Aleth's peer count compares to Geth and identify work required to close any peer count gap.

**Comment by halfalicious** [comment]
I ran a couple of local experiments where I sync'd Aleth to mainnet for a few hours and then ran the logs through a script which computes some stats on the peer counts per hour, I'm not seeing a peer count > 13:

**Run 1**
05-17 09 :  Count:  59 , Min:  0 , Max:  7 , Average:  3.20338983050847
05-17 10 :  Count:  120 , Min:  4 , Max:  8 , Average:  6.29166666666667
05-17 11 :  Count:  120 , Min:  5 , Max:  8 , Average:  6.275
05-17 12 :  Count:  119 , Min:  5 , Max:  9 , Average:  7.05042016806723
05-17 13 :  Count:  120 , Min:  6 , Max:  10 , Average:  7.89166666666667
05-17 14 :  Count:  120 , Min:  7 , Max:  10 , Average:  8.225
05-17 15 :  Count:  84 , Min:  6 , Max:  9 , Average:  7.48809523809524

**Run 2**
05-17 15 :  Count:  22 , Min:  0 , Max:  6 , Average:  5.04545454545455
05-17 16 :  Count:  120 , Min:  6 , Max:  11 , Average:  8.61666666666667
05-17 17 :  Count:  120 , Min:  9 , Max:  12 , Average:  10.3333333333333
05-17 18 :  Count:  119 , Min:  10 , Max:  12 , Average:  10.7058823529412
05-17 19 :  Count:  120 , Min:  3 , Max:  12 , Average:  7.325
05-17 20 :  Count:  120 , Min:  3 , Max:  7 , Average:  4.21666666666667
05-17 21 :  Count:  119 , Min:  3 , Max:  7 , Average:  4.41176470588235
05-17 22 :  Count:  120 , Min:  3 , Max:  7 , Average:  4.425
05-17 23 :  Count:  120 , Min:  3 , Max:  7 , Average:  4.65833333333333
05-18 00 :  Count:  119 , Min:  4 , Max:  11 , Average:  7.70588235294118
05-18 01 :  Count:  120 , Min:  6 , Max:  12 , Average:  7.86666666666667
05-18 02 :  Count:  120 , Min:  5 , Max:  9 , Average:  6.83333333333333
05-18 03 :  Count:  120 , Min:  5 , Max:  9 , Average:  6.6
05-18 04 :  Count:  119 , Min:  4 , Max:  8 , Average:  5.90756302521008
05-18 05 :  Count:  120 , Min:  5 , Max:  9 , Average:  6.63333333333333
05-18 06 :  Count:  120 , Min:  5 , Max:  9 , Average:  7.03333333333333
05-18 07 :  Count:  120 , Min:  6 , Max:  12 , Average:  9.33333333333333
05-18 08 :  Count:  119 , Min:  9 , Max:  13 , Average:  11.3529411764706
05-18 09 :  Count:  120 , Min:  9 , Max:  12 , Average:  11.0666666666667
05-18 10 :  Count:  62 , Min:  11 , Max:  13 , Average:  11.9516129032258

**Comment by halfalicious** [comment]
> 
> 
> I ran a couple of local experiments where I sync'd Aleth on mainnet for a few hours (starting from genesis and a fresh network config i.e. no peers from a previous sync) and then ran the logs through a script which computes some stats on the peer counts per hour, I'm not seeing a peer count > 13:
> 
> **Run 1**
> Duration: 7 hours
> 05-17 09 : Count: 59 , Min: 0 , Max: 7 , Average: 3.20338983050847
> 05-17 10 : Count: 120 , Min: 4 , Max: 8 , Average: 6.29166666666667
> 05-17 11 : Count: 120 , Min: 5 , Max: 8 , Average: 6.275
> 05-17 12 : Count: 119 , Min: 5 , Max: 9 , Average: 7.05042016806723
> 05-17 13 : Count: 120 , Min: 6 , Max: 10 , Average: 7.89166666666667
> 05-17 14 : Count: 120 , Min: 7 , Max: 10 , Average: 8.225
> 05-17 15 : Count: 84 , Min: 6 , Max: 9 , Average: 7.48809523809524
> 
> **Run 2**
> Duration: 20 hours
> 05-17 15 : Count: 22 , Min: 0 , Max: 6 , Average: 5.04545454545455
> 05-17 16 : Count: 120 , Min: 6 , Max: 11 , Average: 8.61666666666667
> 05-17 17 : Count: 120 , Min: 9 , Max: 12 , Average: 10.3333333333333
> 05-17 18 : Count: 119 , Min: 10 , Max: 12 , Average: 10.7058823529412
> 05-17 19 : Count: 120 , Min: 3 , Max: 12 , Average: 7.325
> 05-17 20 : Count: 120 , Min: 3 , Max: 7 , Average: 4.21666666666667
> 05-17 21 : Count: 119 , Min: 3 , Max: 7 , Average: 4.41176470588235
> 05-17 22 : Count: 120 , Min: 3 , Max: 7 , Average: 4.425
> 05-17 23 : Count: 120 , Min: 3 , Max: 7 , Average: 4.65833333333333
> 05-18 00 : Count: 119 , Min: 4 , Max: 11 , Average: 7.70588235294118
> 05-18 01 : Count: 120 , Min: 6 , Max: 12 , Average: 7.86666666666667
> 05-18 02 : Count: 120 , Min: 5 , Max: 9 , Average: 6.83333333333333
> 05-18 03 : Count: 120 , Min: 5 , Max: 9 , Average: 6.6
> 05-18 04 : Count: 119 , Min: 4 , Max: 8 , Average: 5.90756302521008
> 05-18 05 : Count: 120 , Min: 5 , Max: 9 , Average: 6.63333333333333
> 05-18 06 : Count: 120 , Min: 5 , Max: 9 , Average: 7.03333333333333
> 05-18 07 : Count: 120 , Min: 6 , Max: 12 , Average: 9.33333333333333
> 05-18 08 : Count: 119 , Min: 9 , Max: 13 , Average: 11.3529411764706
> 05-18 09 : Count: 120 , Min: 9 , Max: 12 , Average: 11.0666666666667
> 05-18 10 : Count: 62 , Min: 11 , Max: 13 , Average: 11.9516129032258

Performed another (shorter) run and am seeing similar results:

Duration: 4 hours
05-19 09 :  Count:  58 , Min:  0 , Max:  6 , Average:  3.13793103448276
05-19 10 :  Count:  119 , Min:  2 , Max:  6 , Average:  3.47899159663866
05-19 11 :  Count:  120 , Min:  3 , Max:  6 , Average:  4.4
05-19 12 :  Count:  117 , Min:  1 , Max:  8 , Average:  4.95726495726496

**Comment by halfalicious** [comment]
Performed another run  (duration = ~11 hours)

05-20 09 :  Count:  36 , Min:  0 , Max:  7 , Average:  3.69444444444444
05-20 10 :  Count:  120 , Min:  2 , Max:  7 , Average:  4.29166666666667
05-20 11 :  Count:  119 , Min:  4 , Max:  8 , Average:  5.86554621848739
05-20 12 :  Count:  120 , Min:  3 , Max:  7 , Average:  4.70833333333333
05-20 13 :  Count:  119 , Min:  3 , Max:  6 , Average:  4.26050420168067
05-20 14 :  Count:  120 , Min:  3 , Max:  7 , Average:  4.73333333333333
05-20 15 :  Count:  119 , Min:  3 , Max:  7 , Average:  4.86554621848739
05-20 16 :  Count:  120 , Min:  3 , Max:  7 , Average:  4.1
05-20 17 :  Count:  119 , Min:  3 , Max:  6 , Average:  4.20168067226891
05-20 18 :  Count:  120 , Min:  3 , Max:  6 , Average:  4.15
05-20 19 :  Count:  47 , Min:  0 , Max:  4 , Average:  3.12765957446809

**Comment by gumb0** [comment]
Note that `--peers` and `--peer-stretch` CLI arguments should affect it, by default it allows 11 outgoing and 77 incoming connections.

Also unless you have external IP with forwarded port, incoming connections are expected to be rare.

**Comment by halfalicious** [comment]
> 
> 
> Note that `--peers` and `--peer-stretch` CLI arguments should affect it, by default it allows 11 outgoing and 77 incoming connections.
> 
> Also unless you have external IP with forwarded port, incoming connections are expected to be rare.

@gumb0 Thanks! Right now I'm just testing the default configuration to see what sort of peer counts we get and to better understand the peering process (I'm occasionally seeing over 11 peers which means we're getting some incoming connections), I'll start playing around with the `--peers/--peer-stretch` setting once I've done some more Geth testing (in its default networking configuration) to see how we compare. So far based on my limited Geth testing (a couple of short syncs) I'm seeing similar peer counts.

Note that I'm running behind a NAT so that's probably impacting things as well, once I finish the current round of testing I plan on seeing how port forwarding impacts things.

**Comment by asicminer001** [comment]
yes i agree @CodeShark

**Comment by halfalicious** [comment]
No longer needed since @gumb0  mentioned that he saw 80+ peers when running on an external network
