### ISSUE TITLE
Output ENR text representation in admin.nodeInfo RPC

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#5622]
See https://github.com/ethereum/EIPs/blob/master/EIPS/eip-778.md#text-encoding for the relevant part of ENR spec.

1. Adapt base64 encoding/decoding functions to support URL-safe encoding (basically use `-` instead of `+`, `_` instead of `/` and don't pad with `=`)
https://github.com/ethereum/aleth/blob/master/libdevcore/Base64.h

2. Add method to `ENR` class returning string with text form of ENR (serilize to RLP and base64-encode it)

3. Add `enr` field in the output of `admin_net_nodeInfo` https://github.com/ethereum/aleth/blob/6890d9a8548008419dd4bc054ba7908eac3a933f/libweb3jsonrpc/AdminNet.cpp#L27
You'll need to extend `dev::p2p::NodeInfo` struct for that and fill it in the method `Host::nodeInfo()` with `Host::enr()`.

**Comment by twinstar26** [comment]
Hey @gumb0 I am very much eager to provide a solution and have already figured out most of the things.
Just wanna know how do we serialize to RLP (any existing functions) or some method. Also if you could link some part of aleth where we have already used serialization to RLP that would be very helpful!!

**Comment by gumb0** [comment]
@twinstar26 `ENR` already has a method for that, you don't need to do it yourself
https://github.com/ethereum/aleth/blob/4946ed615b11033db61ec47b2a97ef36bd3c047f/libp2p/ENR.cpp#L88

This is an example of using it:
https://github.com/ethereum/aleth/blob/4946ed615b11033db61ec47b2a97ef36bd3c047f/libp2p/Host.cpp#L1039

Basically it will be something like
```
RLPStream s;
enr.streamRLP(s);
auto data = s.out();
```
