### ISSUE TITLE
Remove PARANOID build option

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5631]
Together with `#define ETH_PARANOIA`.

**Comment by moneroexamples** [comment]
Should entire blocks of code enclosed by `#if  ETH_PARANOIA ` also be removed? Or just the `#if ETH_PARANOIA` should be removed and the blocks be unattached? For example, should the following peace of code be fully removed?

https://github.com/ethereum/aleth/blob/be6ce38cfac2710b1710d951cc93c441dbc80fe2/libethereum/BlockChain.cpp#L923-L944
