### ISSUE TITLE
Where is secp256k1_sha256.h to be found?

### ISSUE THREAD

**Issue by inprosys** [ethereum/aleth#5671]
In the libdevcrypto directory, there is a #include <secp256k1_sha256.h> statement in the Hash.cpp program.  I cannot find the "secp256k1_sha256.h" file anywhere (nor can the compiler).  Where is it?

In general, is there a list anywhere of the dependencies of all of this ethereum C++ code on other libraries -- e.g., boost, etc. ?
Thanks

**Comment by moneroexamples** [comment]
It should be located in your build folder's `deps`. For example: `~/aleth/build/deps/include`.


I don't think there is any up to date dependency list. Most dependencies are managed by hunter: https://github.com/ethereum/aleth/blob/master/doc/dependencies.rst

If you go to Hunter's folder `~/.hunter/_Base/Download` you should be able to find packages that aleth uses. In my case these are: Boost  crc32c  cryptopp  ethash  GTest  Hunter  jsoncpp  leveldb  libjson-rpc-cpp  libscrypt  Snappy

**Comment by inprosys** [comment]
Thank you for looking at this question and your reply.  I understand your position and approach to this as a larger "project."  However, I'm only interested in the source code of a few specific routines (elliptic curve and other ethereum address routines).  I'm not interested in compiling a project in its entirety,  I do not want to install Microsoft Visual Studio of any vintage year, or navigate the vagaries of Hunter.

Thanks for your list of the project dependencies.  I will try downloading the source for each and see if I can find secp256k1_sha256 in one of them.  

Thanks again for your time and help,
Gordon

**Comment by moneroexamples** [comment]
I think this is the original source of this file from bitcoin: https://github.com/ethereum/aleth/issues/5671#event-2490843853

Though aleth uses this version: https://github.com/chfast/secp256k1/blob/export-sha256/include/secp256k1_sha256.h from this repo https://github.com/chfast/secp256k1/tree/export-sha256

**Comment by inprosys** [comment]
That is the file and library exactly!  Excellent sleuthing.  Above and beyond the call of duty.  Much appreciated.  I had already closed this out.  

Thanks for your help,
Gordon
