### ISSUE TITLE
Aleth never clears transaction queue's "dropped transactions" list

### ISSUE THREAD

**Issue by halfalicious** [ethereum/aleth#5688]
Transactions which are dropped during transaction queue import are stored in `TransactionQueue::m_dropped`. A max size isn't enforced on `m_dropped `and `m_dropped `is only cleared when the entire Transaction Queue is cleared (`TransactionQueue::clear`), which doesn't happen during normal execution.

**Comment by chfast** [comment]
Why do we keep them?

**Comment by gumb0** [comment]
@chfast I think to immediately drop them if they come once again over the network

**Comment by chfast** [comment]
Some kind of ring buffer would be nicer here, don't you think?
