### ISSUE TITLE
Fix Aleth presence on ethernodes.org

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5785]
https://ethernodes.org/client/aleth

The Aleth version is not available there. Fix it to get information which Aleth versions are in use on the Ethereum network.

Ethernodes.org contact point:  @ppratscher.

**Comment by ppratscher** [comment]
It looks like our semver library is not able to parse the version string in the client id of aleth.

Aleth uses the following format: `aleth/1.5.2+commit.00fd8416.dirty/linux/gnu7.4.0/relwithdebinfo` while most other nodes use the following: `Geth/v1.9.6-stable-bd059680/linux-amd64/go1.11.5` or `Parity-Ethereum/v2.6.1-beta-7bfbe41-20190814/x86_64-linux-gnu/rustc1.36.0`

**Comment by gumb0** [comment]
We can make the fix in https://github.com/ethereum/aleth/blob/a3cdc87abb8fb30a4293ca3bef28004c5b3ce2d3/libwebthree/WebThree.cpp#L61-L66
(but apparently it won't help with getting info from currently run clients that won't update)

**Comment by halfalicious** [comment]
@gumb0 / @chfast Should we mark this as help wanted since the fix is understood and trivial?

**Comment by chfast** [comment]
Ok, so the task is to change the reported version format to follow geth/parity/other clients. We don't care about previous versions at this point.

**Comment by gumb0** [comment]
It's one letter fix, let's just do it :-)

(I will do it some time soon, if no one does before me)
