### ISSUE TITLE
how to use aleth???

### ISSUE THREAD

**Issue by songminkyu** [ethereum/aleth#5824]
Not the aleth homepage, where is the manual?

I want to send coins and tokens through libweb3jsonrpc. Is it possible?

**Comment by songminkyu** [comment]
libweb3jsonrpc을 통해 코인 및 토큰을 보낼려고 한다. 가능한가?

**Comment by gumb0** [comment]
@songminkyu not really, that library is a server side of the JSON-RPC implementation, you need a client side code, I guess.
